### ISSUE TITLE
Missing dependency on importlib-metadata

### ISSUE THREAD

**Issue by jhaiduce** [samschott/maestral#1022]
**Describe the bug**
Installing maestral as described in the documentation results in an error `ModuleNotFoundError: No module named 'importlib_metadata'` when the maestral executable is run.

Full output:
```
$ maestral
Traceback (most recent call last):
  File "/home/jhaiduce/.local/lib/maestral/venv/bin/maestral", line 5, in <module>
    from maestral.cli import main
  File "/home/jhaiduce/.local/lib/maestral/venv/lib64/python3.12/site-packages/maestral/cli/__init__.py", line 6, in <module>
    from .cli_main import main
  File "/home/jhaiduce/.local/lib/maestral/venv/lib64/python3.12/site-packages/maestral/cli/cli_main.py", line 6, in <module>
    from .cli_core import start, stop, gui, pause, resume, auth, sharelink
  File "/home/jhaiduce/.local/lib/maestral/venv/lib64/python3.12/site-packages/maestral/cli/cli_core.py", line 15, in <module>
    from .common import (
  File "/home/jhaiduce/.local/lib/maestral/venv/lib64/python3.12/site-packages/maestral/cli/common.py", line 13, in <module>
    from ..constants import DEFAULT_CONFIG_NAME
  File "/home/jhaiduce/.local/lib/maestral/venv/lib64/python3.12/site-packages/maestral/constants.py", line 11, in <module>
    from importlib_metadata import metadata, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib_metadata'
```

**To Reproduce**
1. Install maestral in a Python venv as described in the [installation instructions](https://maestral.app/docs/installation):
```
$ python3 -m venv maestral-venv
$ source maestral-venv/bin/activate
(maestral-venv)$ python3 -m pip install --upgrade maestral
```
2. Run the maestral executable from the venv, with no arguments

**Expected behaviour**
Maestral should print usage information

**System:**

 - Maestral version: 1.8.8
 - Python version: 3.12.1
 - OS: fedora 39
 - Desktop environment: Gnome 45.4
 - PyQt version (for Linux GUI): n/a

**Additional context**

maestral works as expected after manually installing importlib-metadata with `pip install importlib-metadata`.

**Comment by samschott** [comment]
Thanks for the report! This is fixed in v1.9.0 now.
