### ISSUE TITLE
Insufficient read or write permissions for .Spotlight-V100 folder

### ISSUE THREAD

**Issue by Maestro-James** [samschott/maestral#1045]
**Describe the bug**
When syncing to an external 8TB drive, it stops syncing stating that "Path: /Volumes/Projects/.Spotlight-V100
Insufficient read or write permissions for this location." The dropbox drive itself is around 7.3TB, but I am selectively syncing around 1TB.

**Expected behaviour**
Syncing the entire drive without issue.

**System:**

 - Maestral version: 1.9.3
 - Python version: 3.12
 - OS: MacOS 13.5.2 

**Additional context**
Here is the section of the log file that details where it went wrong - 

2024-05-03 08:23:48 sync INFO: Indexing 119840...
2024-05-03 08:23:48 sync INFO: Up to date
2024-05-03 08:23:48 sync INFO: Indexing local changes...
2024-05-03 08:23:48 manager ERROR: Could not sync file or folder
Traceback (most recent call last):
  File "app_packages/maestral/sync.py", line 1700, in upload_local_changes_while_inactive
  File "app_packages/maestral/sync.py", line 1747, in _get_local_changes_while_inactive
  File "app_packages/maestral/utils/path.py", line 436, in walk
  File "app_packages/maestral/utils/path.py", line 428, in walk
  File "app_packages/maestral/sync.py", line 3814, in _scandir_with_ignore
PermissionError: [Errno 1] Operation not permitted: '/Volumes/Projects/.Spotlight-V100'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app_packages/maestral/manager.py", line 767, in _handle_sync_thread_errors
  File "app_packages/maestral/manager.py", line 753, in startup_worker
  File "app_packages/maestral/sync.py", line 1705, in upload_local_changes_while_inactive
maestral.exceptions.InsufficientPermissionsError: Could not sync file or folder. Insufficient read or write permissions for this location.
2024-05-03 08:23:48 manager INFO: Shutting down threads...
2024-05-03 08:23:48 sync INFO: Sync aborted
2024-05-03 08:23:48 manager INFO: Paused

The permissions of the drive are set to allow everyone to read and write so I'm not sure how else to deal with the permissions issue. The dropbox client is currently also installed and running on the computer, but even after quitting the dropbox client the issue still persists.

**Comment by samschott** [comment]
Have you selected the entire top-level volume as a local dropbox folder to sync? I seem to recall that the `.Spotlight-V100` folder is (a) at the top-level of a volume and (b) only accessible with root permissions. The latter explains your permission error.

To mitigate, you could either create a folder _inside_ the volume and sync that folder, or tell Maestral to ignore local `.Spotlight-V100` folders by adding them to an `.mignore` file (see https://maestral.app/docs/mignore).

From the Maestral side, it would make sense to ignore some system files and folders by default. This is already done with `.DS_Store` files for example.

**Comment by fabiovin70** [comment]
My fault, I remounted the ntfs drive with the flag "permissions" in etc/fstab and changed the owner to user:user and now the problem disappeared. Problem solved. Thank you.
