### ISSUE TITLE
"An unexpected error occurred"

### ISSUE THREAD

**Issue by mcdado** [samschott/maestral#1065]
**Describe the bug**
Recently this window started popping up.
![Screenshot 2024-07-22 at 18 07 31](https://github.com/user-attachments/assets/ae8de740-9e36-4105-a8bf-cafab34b20e3)

**To Reproduce**
No idea! 🤷🏻‍♂️ Happens from time to time.

**Expected behaviour**
It shouldn't happen, I guess.

**System:**

 - Maestral version: 1.9.4
 - Python version:  `python3 -V` => Python 3.12.4
 - OS: macOS 14.5 (23F79)
 - Desktop environment: Finder

**Additional context**
Let me know where to get the logs and how to get them to you privately (I have no idea if they contain sensitive info).

**Comment by mcdado** [comment]
OK, through Console.app I found the log reports, and they seem ok to share (I removed what looked like a token)

```
2024-07-22 17:32:52 manager INFO: Syncing...
2024-07-22 17:32:52 sync INFO: Fetching remote changes
2024-07-22 17:32:53 manager INFO: Up to date
2024-07-22 18:04:44 manager ERROR: An unexpected error occurred
Traceback (most recent call last):
  File "app_packages/maestral/errorhandling.py", line 90, in convert_api_errors
  File "app_packages/maestral/client.py", line 632, in get_account_info
  File "app_packages/dropbox/base.py", line 5870, in users_get_current_account
  File "app_packages/dropbox/dropbox_client.py", line 326, in request
  File "app_packages/dropbox/dropbox_client.py", line 476, in request_json_string_with_retry
  File "app_packages/maestral/client.py", line 165, in request_json_string
  File "app_packages/dropbox/dropbox_client.py", line 595, in request_json_string
  File "app_packages/dropbox/dropbox_client.py", line 638, in raise_dropbox_error_for_resp
dropbox.exceptions.AuthError: AuthError('[...]', AuthError('route_access_denied', None))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app_packages/maestral/manager.py", line 767, in _handle_sync_thread_errors
  File "app_packages/maestral/manager.py", line 615, in download_worker
  File "app_packages/maestral/manager.py", line 391, in check_and_update_path_root
  File "app_packages/maestral/manager.py", line 414, in _needs_path_root_update
  File "app_packages/maestral/client.py", line 627, in get_account_info
  File "support/python-stdlib/contextlib.py", line 155, in __exit__
  File "app_packages/maestral/errorhandling.py", line 92, in convert_api_errors
maestral.exceptions.MaestralApiError: An unexpected error occurred. Please contact the developer with the traceback information from the logs.
2024-07-22 18:04:44 manager INFO: Shutting down threads...
2024-07-22 18:04:44 sync INFO: Sync aborted
2024-07-22 18:04:44 manager INFO: Paused
```

This was the second time, in a few days the same error occurred, the previous one was at 2024-07-19 19:14:55

**Comment by samschott** [comment]
That is very strange. From your traces, it appears that the failing call is to the `users/get_current_account` endpoint. According to [Dropbox docs](https://www.dropbox.com/developers/documentation/http/documentation#users-get_current_account), that endpoint requires the `account_info.read` permission, which all apps are granted by default.

Are you using Dropbox with a team account? And did you recently join or leave a Dropbox team? The error seems to be occurring in the context of the Dropbox folder layout changing.

**Comment by mcdado** [comment]
No, I use my Dropbox account since a long time, never had a paid or team
account, and I don’t move around many files.
The only uncommon thing recently has been deleting two root folders that
start with a @ sign , I have the feeling that could have something to do
with it.

**Comment by mcdado** [comment]
<img width="700" alt="Screenshot_2024-07-22_at_23_23_26" src="https://github.com/user-attachments/assets/3f71ecf7-9df4-4ed8-99c9-6557a7675d39">

**Comment by Taimar** [comment]
I’m seeing the same error recently, probaly 3–4 times already.

I’m *not* using a Dropbox team account.

Please let me know how can I investigate further.

**Comment by samschott** [comment]
Thanks for the infos! In this case, the `_needs_path_root_update` call in the stack trace may be misleading. This function is called before every sync cycle to ensure that user's root folder has not moved in or out of a team drive, but this seems to be not directly related to the root cause.

Could you increase the log level to DEBUG and wait until you see the error again? The logs for the error should then contain a request ID. If you can share this, I'll forward it to Dropbox support to investigate.

**Comment by mcdado** [comment]
How do I set the debug level to DEBUG?

**Comment by needleshaped** [comment]
> How do I set the debug level to DEBUG?
> […](#)
> Message ID: ***@***.***>

See https://maestral.app/cli/log

**Comment by akaihola** [comment]
I got the `route_access_denied` traceback for the first time just now. Nothing unusual has been happening with my Dropbox account today or recently. I'll enable debug logging and report back if I get the same again. See my log excerpt below.

<details>
<summary>maestral.log</summary>

```python
2024-07-24 19:24:00 sync DEBUG: Waiting for local changes since cursor: 1721834519.5139976
2024-07-24 19:24:31 sync DEBUG: Detected remote changes: False
...skipping...
  File "/nix/store/8fd7ch5lrhqggj8yfapi2psfpxpr1z2l-python3.11-dropbox-12.0.0/lib/python3.11/site-packages/dropbox/dropbox_client.py", line 326, in request
    res = self.request_json_string_with_retry(host,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8fd7ch5lrhqggj8yfapi2psfpxpr1z2l-python3.11-dropbox-12.0.0/lib/python3.11/site-packages/dropbox/dropbox_client.py", line 476, in request_json_string_with_r>
    return self.request_json_string(host,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7n060rjpakwa6zhqmrz8km96fqm96bya-python3.11-maestral-1.9.3/lib/python3.11/site-packages/maestral/client.py", line 165, in request_json_string
    return super().request_json_string(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/8fd7ch5lrhqggj8yfapi2psfpxpr1z2l-python3.11-dropbox-12.0.0/lib/python3.11/site-packages/dropbox/dropbox_client.py", line 595, in request_json_string
    self.raise_dropbox_error_for_resp(r)
  File "/nix/store/8fd7ch5lrhqggj8yfapi2psfpxpr1z2l-python3.11-dropbox-12.0.0/lib/python3.11/site-packages/dropbox/dropbox_client.py", line 638, in raise_dropbox_error_for_re>
    raise AuthError(request_id, err)
dropbox.exceptions.AuthError: AuthError('c0abb87efd86448584143fb73d19f6e3', AuthError('route_access_denied', None))
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/nix/store/7n060rjpakwa6zhqmrz8km96fqm96bya-python3.11-maestral-1.9.3/lib/python3.11/site-packages/maestral/manager.py", line 767, in _handle_sync_thread_errors
    yield
  File "/nix/store/7n060rjpakwa6zhqmrz8km96fqm96bya-python3.11-maestral-1.9.3/lib/python3.11/site-packages/maestral/manager.py", line 615, in download_worker
    if self.check_and_update_path_root():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7n060rjpakwa6zhqmrz8km96fqm96bya-python3.11-maestral-1.9.3/lib/python3.11/site-packages/maestral/manager.py", line 391, in check_and_update_path_root
    if self._needs_path_root_update():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7n060rjpakwa6zhqmrz8km96fqm96bya-python3.11-maestral-1.9.3/lib/python3.11/site-packages/maestral/manager.py", line 414, in _needs_path_root_update
    account_info = self.sync.client.get_account_info()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7n060rjpakwa6zhqmrz8km96fqm96bya-python3.11-maestral-1.9.3/lib/python3.11/site-packages/maestral/client.py", line 627, in get_account_info
    with convert_api_errors():
  File "/nix/store/4rf5qybw37b4lh1g0xczlv14sqdbmnpm-python3-3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/nix/store/7n060rjpakwa6zhqmrz8km96fqm96bya-python3.11-maestral-1.9.3/lib/python3.11/site-packages/maestral/errorhandling.py", line 92, in convert_api_errors
    raise dropbox_to_maestral_error(exc, dbx_path, local_path)
maestral.exceptions.MaestralApiError: An unexpected error occurred. Please contact the developer with the traceback information from the logs.
2024-07-29 18:08:30 manager INFO: Shutting down threads...
2024-07-29 18:08:30 sync INFO: Sync aborted
2024-07-29 18:08:30 manager INFO: Paused
```
</details>

**Comment by aryehsanders** [comment]
Just adding another stack trace that appears to be the same issue:
```
2024-07-30 16:07:33 sync INFO: Syncing ↓ 3/3
2024-07-30 16:07:33 sync INFO: Up to date
2024-07-30 16:07:33 manager INFO: Up to date
2024-07-30 16:07:36 manager ERROR: An unexpected error occurred
Traceback (most recent call last):
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/maestral/errorhandling.py", line 90, in convert_api_errors
    yield
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/maestral/client.py", line 663, in get_space_usage
    res = self.dbx_base.users_get_space_usage()
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/dropbox/base.py", line 5888, in users_get_space_usage
    r = self.request(
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/dropbox/dropbox_client.py", line 326, in request
    res = self.request_json_string_with_retry(host,
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/dropbox/dropbox_client.py", line 476, in request_json_string_with_retry
    return self.request_json_string(host,
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/maestral/client.py", line 165, in request_json_string
    return super().request_json_string(
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/dropbox/dropbox_client.py", line 595, in request_json_string
    self.raise_dropbox_error_for_resp(r)
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/dropbox/dropbox_client.py", line 638, in raise_dropbox_error_for_resp
    raise AuthError(request_id, err)
dropbox.exceptions.AuthError: AuthError('[...removed...]', AuthError('route_access_denied', None))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/maestral/manager.py", line 767, in _handle_sync_thread_errors
    yield
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/maestral/manager.py", line 628, in download_worker
    self.sync.client.get_space_usage()
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/maestral/client.py", line 663, in get_space_usage
    res = self.dbx_base.users_get_space_usage()
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/maestral-venv/lib/python3.8/site-packages/maestral/errorhandling.py", line 92, in convert_api_errors
    raise dropbox_to_maestral_error(exc, dbx_path, local_path)
maestral.exceptions.MaestralApiError: An unexpected error occurred. Please contact the developer with the traceback information from the logs.
2024-07-30 16:07:36 manager INFO: Shutting down threads...
2024-07-30 16:07:39 sync INFO: Syncing ↑ 1/1

```

**Comment by JoshIBrown** [comment]
I have the same issue.

**Comment by lukefor** [comment]
This is also happening to me roughly every 24-48 hours since this issue was opened, so likely a change on Dropbox's end. I use an account that has always been free and personal (not team).

At the moment it seems Maestral gets stuck after the error rather than terminating and allowing itself to be restarted

**Comment by aryehsanders** [comment]
The route_access_denied issue has been discussed on the Dropbox Forums, with no resolution yet:
https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/route-access-denied/td-p/785422

**Comment by aryehsanders** [comment]
And yesterday it was updated with a message from Dropbox staff that it has been fixed:

> That team has deployed a fix to address this. Please let us know if you're still see any more instances of this now. (If so, please share samples of the 'X-Dropbox-Request-Id' response header values.) Thanks!
