### ISSUE TITLE
[BUG] Maestral seems to stop after a few minutes on WSL 1

### ISSUE THREAD

**Issue by arisboch** [SamSchott/maestral#132]
**Describe the bug**
Under WSL 1, after the daemon is started and runs a few minutes, it suddenly stops and needs to be manually restarted.

**To Reproduce**
Install maestral under WSL 1 and start it.

**Expected behaviour**
The daemon should keep on running in the background.

**System (please complete the following information):**
 - Maestral version: 0.6.4
 - OS: Ubuntu 18.04.4 LTS
 - Desktop environment: None
 - Qt version: _Don't know where to look_

**Additional context**
It was said before, but I'm running the program under the WSL 1 environment.

**Comment by SamSchott** [comment]
Interesting, I don't have any experience with WSL (I assume it stands for Windows Subsystem for Linux). Could you check the following:

1. Are you starting the daemon with systemd or directly with `maestral start`?
2. Are there any error messages in the log? You can show it with `maestral log show`.
3. How about running the Maestral in the foreground with `maestral start --foreground --verbose`? Does it crash as well?

**Comment by arisboch** [comment]
Sorry, but it is on my work computer, so I'm gonna be able to check it next Tuesday earliest.

**Comment by arisboch** [comment]
@SamSchott 
1) I was using `maestral start` (this may sound like a beginner question, but how would I run maestral via systemd?)
2) I filtered the "INFO: etc." lines from the log and here's what it showed me:

```
2020-04-30 08:43:21 maestral.sync WARNING: Could not sync rev:40b330044e220
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 280, in download
    md, http_resp = self.dbx.files_download(dbx_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dropbox/base.py", line 1287, in files_download
    None,
  File "/usr/local/lib/python3.6/dist-packages/dropbox/dropbox.py", line 296, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('8b98440e3669ad29b9d78c3bec0ce89f', DownloadError('path', LookupError('restricted_content', None)))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2372, in create_local_entry
    md = self.client.download(f'rev:{entry.rev}', tmp_fname)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 112, in wrapper
    raise dropbox_to_maestral_error(exc, dbx_path, local_path) from exc
maestral.errors.RestrictedContentError: Could not download file. The file cannot be transferred because the content is restricted. For example, sometimes there are legal restrictions due to copyright claims.
2020-04-30 08:57:36 maestral.sync WARNING: Could not sync rev:40b330044e220
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 280, in download
    md, http_resp = self.dbx.files_download(dbx_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dropbox/base.py", line 1287, in files_download
    None,
  File "/usr/local/lib/python3.6/dist-packages/dropbox/dropbox.py", line 296, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('2360a7303c915eb90c8d2b8099d55dac', DownloadError('path', LookupError('restricted_content', None)))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2372, in create_local_entry
    md = self.client.download(f'rev:{entry.rev}', tmp_fname)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 112, in wrapper
    raise dropbox_to_maestral_error(exc, dbx_path, local_path) from exc
maestral.errors.RestrictedContentError: Could not download file. The file cannot be transferred because the content is restricted. For example, sometimes there are legal restrictions due to copyright claims.
2020-04-30 09:31:30 maestral.sync WARNING: Could not sync rev:40b330044e220
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 280, in download
    md, http_resp = self.dbx.files_download(dbx_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dropbox/base.py", line 1287, in files_download
    None,
  File "/usr/local/lib/python3.6/dist-packages/dropbox/dropbox.py", line 296, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('72c65f487a9b5f1bcd544d810111a725', DownloadError('path', LookupError('restricted_content', None)))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2372, in create_local_entry
    md = self.client.download(f'rev:{entry.rev}', tmp_fname)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 112, in wrapper
    raise dropbox_to_maestral_error(exc, dbx_path, local_path) from exc
maestral.errors.RestrictedContentError: Could not download file. The file cannot be transferred because the content is restricted. For example, sometimes there are legal restrictions due to copyright claims.
2020-04-30 09:33:39 maestral.sync WARNING: Could not sync rev:40b330044e220
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 280, in download
    md, http_resp = self.dbx.files_download(dbx_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dropbox/base.py", line 1287, in files_download
    None,
  File "/usr/local/lib/python3.6/dist-packages/dropbox/dropbox.py", line 296, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('0a1c82b76ac5e82947e0c871bff2413d', DownloadError('path', LookupError('restricted_content', None)))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2372, in create_local_entry
    md = self.client.download(f'rev:{entry.rev}', tmp_fname)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 112, in wrapper
    raise dropbox_to_maestral_error(exc, dbx_path, local_path) from exc
maestral.errors.RestrictedContentError: Could not download file. The file cannot be transferred because the content is restricted. For example, sometimes there are legal restrictions due to copyright claims.
2020-04-30 09:39:03 maestral.sync WARNING: Could not sync rev:40b330044e220
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 280, in download
    md, http_resp = self.dbx.files_download(dbx_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dropbox/base.py", line 1287, in files_download
    None,
  File "/usr/local/lib/python3.6/dist-packages/dropbox/dropbox.py", line 296, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('e7341825a42e7db1d187a3eb384fb4ad', DownloadError('path', LookupError('restricted_content', None)))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2372, in create_local_entry
    md = self.client.download(f'rev:{entry.rev}', tmp_fname)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 112, in wrapper
    raise dropbox_to_maestral_error(exc, dbx_path, local_path) from exc
maestral.errors.RestrictedContentError: Could not download file. The file cannot be transferred because the content is restricted. For example, sometimes there are legal restrictions due to copyright claims.
2020-04-30 09:40:58 maestral.sync WARNING: Could not sync rev:40b330044e220
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 280, in download
    md, http_resp = self.dbx.files_download(dbx_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dropbox/base.py", line 1287, in files_download
    None,
  File "/usr/local/lib/python3.6/dist-packages/dropbox/dropbox.py", line 296, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('94a50ec4ee4558e67920d23e6cd368a0', DownloadError('path', LookupError('restricted_content', None)))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2372, in create_local_entry
    md = self.client.download(f'rev:{entry.rev}', tmp_fname)
  File "/usr/local/lib/python3.6/dist-packages/maestral/client.py", line 112, in wrapper
    raise dropbox_to_maestral_error(exc, dbx_path, local_path) from exc
maestral.errors.RestrictedContentError: Could not download file. The file cannot be transferred because the content is restricted. For example, sometimes there are legal restrictions due to copyright claims.
```
3) When I started it with these parameters, it didn't crash.

**Comment by SamSchott** [comment]
1. That is a fair question. When you run `maestral autostart`, it will automatically create a systemd service for you which is run on login (in Linux, not Windows...). Manually creating a service is also possible and documented in [wiki](https://github.com/SamSchott/maestral/wiki/Systemd-Integration) but its really only for people you are quite comfortable with Linux and want to tweak things themselves.

2. The warnings in the log are absolutely fine. Those are from DMCA protected files. Dropbox does not allow downloading them through their public API, only the official client can sync them. When you run `maestral status`, you will see a list of the corresponding sync issues.

3. That is a good sign.

I can see two possibly issues on WSL:

1. There may be an issue with spawning a separate process in WSL which prevents `maestral start` from working. That would explain why `maestral start --foreground` works. But this should result in a failed startup instead of crashing after a few minutes.

2. It may be possible that sending desktop notifications fails on WSL and causes a crash. Those notifications are triggered by remote file changes only and may therefore occur at an "arbitrary" time after starting the daemon. In this case, it may be coincidental that `maestral start --foreground` seemed to work. To clarify, how long does it take until Maestral crashes? And can you trigger a crash by adding a file to Dropbox remotely?

**Comment by arisboch** [comment]
2) I didn't really look at how many minutes exactly it ran until crash, but I **think** it was a few minutes at best. I'll be back at work the day after tomorrow and will then try that theory out by starting the client using just the ``maestral start`` command and then use the client on my cellphone to upload some random crap on my Dropbox to see if it will really crash the client.

**Comment by arisboch** [comment]
I now did exactly that (starting maestral via ``maestral start`` and uploading some random crap via the client on my cellphone), but it didn't crash maestral.

**Comment by arisboch** [comment]
I updated the client a few minutes ago, maybe it'll help.

**Comment by arisboch** [comment]
It didn't help, the client still crashed after a few minutes 😭

**Comment by SamSchott** [comment]
Ok, thanks for checking. I'll try to reproduce the crash myself on WSL then, but it won't be immediately...

**Comment by SamSchott** [comment]
I have tried this on WSL myself but cannot reproduce the issue. The sync daemon has been running for more than a day without crashing and both uploads and downloads are working. And you are sure that you cannot reproduce the crash with the `--foreground` option?

**Comment by jeanmonet** [comment]
Trying to use with WSL2, where the dropbox dir is linked to directory outside WSL itself: `/mnt/c/Users/[user]/Dropbox`.

After a few minutes of syncing on existing files, it stops with the following error message:

(I've tried launching it with `maestral start --foreground` as well, with same result)

```
2023-03-25 16:15:38 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/errorhandling.py", line 90, in convert_api_errors
    yield
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 1059, in get_local_hash
    hash_str, mtime = content_hash(local_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/utils/path.py", line 455, in content_hash
    raise exc
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/utils/path.py", line 443, in content_hash
    chunk = f.read(chunk_size)
            ^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 3352, in _create_local_entry
    res = self._on_remote_file(event)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 3418, in _on_remote_file
    conflict_check = self._check_download_conflict(event)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 3149, in _check_download_conflict
    event.content_hash == self.get_local_hash(event.local_path)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 1058, in get_local_hash
    with convert_api_errors():
  File "/opt/miniconda3/envs/py11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/errorhandling.py", line 107, in convert_api_errors
    raise os_to_maestral_error(exc, dbx_path, local_path)
maestral.exceptions.FileReadError: Could not sync file or folder. Could not access file. Errno 5: Input/output error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/manager.py", line 802, in _handle_sync_thread_errors
    yield
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/manager.py", line 781, in startup_worker
    self.sync.download_sync_cycle()
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 2876, in download_sync_cycle
    downloaded = self.apply_remote_changes(changes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 3025, in apply_remote_changes
    results.extend(res)
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 3751, in do_parallel
    yield f.result()
          ^^^^^^^^^^
  File "/opt/miniconda3/envs/py11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/miniconda3/envs/py11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 3364, in _create_local_entry
    self._handle_sync_error(e, direction=SyncDirection.Down)
  File "/opt/miniconda3/envs/py11/lib/python3.11/site-packages/maestral/sync.py", line 1512, in _handle_sync_error
    raise ValueError("Sync error has an unknown path")
ValueError: Sync error has an unknown path
2023-03-25 16:15:38 manager INFO: Shutting down threads...
2023-03-25 16:15:38 sync INFO: Sync aborted
2023-03-25 16:15:38 manager INFO: Paused
```
