### ISSUE TITLE
[BUG] pip3 install maestral[gui] fails on Linux Mint 19.3

### ISSUE THREAD

**Issue by duckworthd** [SamSchott/maestral#168]
**Describe the bug**

Attempting to install `maestral[gui]` on Linux. It seems that one of the upstream dependencies (PyQt5-5.15.0) fails to install with pip.

**To Reproduce**
Steps to reproduce the behaviour.

```
python3 -m pip install "maestral[gui]"
```

**Expected behaviour**

Successful installation.

**System (please complete the following information):**
 - Maestral version: 1.1.0
 - OS: [e.g. Ubuntu] Linux Mint 19.3 Tricia
 - Desktop environment: [e.g. Gnome 3.32] xfce
 - Qt version: PyQt5 version 5.15.0. Unknown version of Qt

**Additional context**

```
➜  dotfiles git:(master) python3 -m pip install "maestral[gui]"
Collecting maestral[gui]
Collecting Pyro5>=5.7 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/98/34/d99aac02feb207a57eb3b946fc7890cdc74ce4151f58bbdf43b0dd6c2da3/Pyro5-5.10-py3-none-any.whl
Collecting keyrings.alt>=3.1.0 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/0c/3e/a39c3fb722ffdee50db5dff1e794a01cab7e0408bba1aa0e02e28a87667d/keyrings.alt-3.4.0-py2.py3-none-any.whl
Collecting click>=7.1.1 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting requests (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting watchdog>=0.10.0 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/0e/06/121302598a4fc01aca942d937f4a2c33430b7181137b35758913a8db10ad/watchdog-0.10.3.tar.gz
Collecting packaging (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting dropbox>=10.0.0 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/f2/68/037016cf1b227cc2ae0a7b962f69a14e60e50fa1e94f1ba9d297893de924/dropbox-10.3.0-py3-none-any.whl
Collecting fasteners (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/18/bd/55eb2d6397b9c0e263af9d091ebdb756b15756029b3cededf6461481bc63/fasteners-0.15-py2.py3-none-any.whl
Collecting keyring>=19.0.0 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/59/4d/469272124b46456c425a505a8b5f2d42d2fe95d1181de2d888d684506cf7/keyring-21.3.0-py3-none-any.whl
Collecting pathspec>=0.5.8 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/5d/d0/887c58853bd4b6ffc7aa9cdba4fc57d7b979b45888a6bd47e4568e1cf868/pathspec-0.8.0-py2.py3-none-any.whl
Collecting sdnotify (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/ce/d8/9fdc36b2a912bf78106de4b3f0de3891ff8f369e7a6f80be842b8b0b6bd5/sdnotify-0.3.2.tar.gz
Collecting jeepney; sys_platform == "linux" (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/79/31/2e8d42727595faf224c6dbb748c32b192e212f25495fe841fb7ce8e168b8/jeepney-0.4.3-py3-none-any.whl
Collecting bugsnag>=3.4.0 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/32/b2/bd807b0fbeaae9aba11e10723e22979386f16061c4d932302171d5049e4b/bugsnag-3.7.1-py2.py3-none-any.whl
Collecting atomicwrites>=1.0.0 (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/2c/a0/da5f49008ec6e9a658dbf5d7310a4debd397bce0b4db03cf8a410066bb87/atomicwrites-1.4.0-py2.py3-none-any.whl
Collecting importlib-metadata; python_version < "3.8" (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/8e/58/cdea07eb51fc2b906db0968a94700866fc46249bdc75cac23f9d13168929/importlib_metadata-1.7.0-py2.py3-none-any.whl
Collecting setuptools (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/ed/16/e9f5c5b86696da09298ea10c32d68ad8ea21f888e45b11aa9e615adda6c9/setuptools-49.2.1-py3-none-any.whl
Collecting maestral-qt>=1.0.3; sys_platform == "linux" and extra == "gui" (from maestral[gui])
  Using cached https://files.pythonhosted.org/packages/9d/f1/bcb1bd43fc38b449e9e9f09ea548b1fb3f4de3d59369fdfa3d3aacc31924/maestral_qt-1.1.0-py3-none-any.whl
Collecting serpent>=1.27 (from Pyro5>=5.7->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/b4/a1/24871492bfc34ea18aee3bf38e0cee22d8c11d8d5e765ccc921103140747/serpent-1.30.2-py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog>=0.10.0->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/e7/7f/470d6fcdf23f9f3518f6b0b76be9df16dcc8630ad409947f8be2eb0ed13a/pathtools-0.1.2.tar.gz
Collecting pyparsing>=2.0.2 (from packaging->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting six (from packaging->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting monotonic>=0.1 (from fasteners->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting SecretStorage>=3; sys_platform == "linux" (from keyring>=19.0.0->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/c3/50/8a02cad020e949e6d7105f5f4530d41e3febcaa5b73f8f2148aacb3aeba5/SecretStorage-3.1.2-py3-none-any.whl
Collecting webob (from bugsnag>=3.4.0->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/18/3c/de37900faff3c95c7d55dd557aa71bd77477950048983dcd4b53f96fde40/WebOb-1.8.6-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
Collecting markdown2 (from maestral-qt>=1.0.3; sys_platform == "linux" and extra == "gui"->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/00/cb/9f4b1fc03ceaffb944ab0016e6b071b0c81459b679cc29cd237b83b5d4a8/markdown2-2.3.9-py2.py3-none-any.whl
Collecting PyQt5>=5.9 (from maestral-qt>=1.0.3; sys_platform == "linux" and extra == "gui"->maestral[gui])
  Using cached https://files.pythonhosted.org/packages/8c/90/82c62bbbadcca98e8c6fa84f1a638de1ed1c89e85368241e9cc43fcbc320/PyQt5-5.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-w3ghd8ml/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w3ghd8ml/PyQt5/
```

**Comment by SamSchott** [comment]
@duckworthd, thanks for the report. Which version of pip are you using and can you upgrade to the latest?

**Comment by duckworthd** [comment]
That did it! Thank you, @SamSchott :). When I obtained the error above, I was using pip==9.0.1

```
duckworthd@kiwi:~/Desktop/craftwerk/craftdoor-ui$ python3 -m pip --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

I upgraded to the latest version,

```
duckworthd@kiwi:~/Desktop/craftwerk/craftdoor-ui$ python3 -m pip install pip --upgrade
Collecting pip
  Downloading https://files.pythonhosted.org/packages/bd/b1/56a834acdbe23b486dea16aaf4c27ed28eb292695b90d01dff96c96597de/pip-20.2.1-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 1.3MB/s
Installing collected packages: pip
Successfully installed pip-20.2.1
```

And then succesfully installed `maestral[gui]`,

```
duckworthd@kiwi:~/Desktop/craftwerk/craftdoor-ui$ python3 -m pip install 'maestral[gui]'
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: maestral[gui] in /home/duckworthd/.local/lib/python3.6/site-packages (1.1.0)
Requirement already satisfied: pathspec>=0.5.8 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (0.8.0)
Requirement already satisfied: atomicwrites>=1.0.0 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (1.4.0)
Requirement already satisfied: bugsnag>=3.4.0 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (3.7.1)
Requirement already satisfied: keyring>=19.0.0 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (21.3.0)
Requirement already satisfied: packaging in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (20.4)
Requirement already satisfied: Pyro5>=5.7 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (5.10)
Requirement already satisfied: watchdog>=0.10.0 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (0.10.3)
Requirement already satisfied: sdnotify in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (0.3.2)
Requirement already satisfied: jeepney; sys_platform == "linux" in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (0.4.3)
Requirement already satisfied: setuptools in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (49.2.1)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (1.7.0)
Requirement already satisfied: dropbox>=10.0.0 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (10.3.0)
Requirement already satisfied: requests in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (2.24.0)
Requirement already satisfied: fasteners in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (0.15)
Requirement already satisfied: click>=7.1.1 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (7.1.2)
Requirement already satisfied: keyrings.alt>=3.1.0 in /home/duckworthd/.local/lib/python3.6/site-packages (from maestral[gui]) (3.4.0)
Collecting maestral-qt>=1.0.3; sys_platform == "linux" and extra == "gui"
  Using cached maestral_qt-1.1.0-py3-none-any.whl (1.5 MB)
Requirement already satisfied: webob in /home/duckworthd/.local/lib/python3.6/site-packages (from bugsnag>=3.4.0->maestral[gui]) (1.8.6)
Requirement already satisfied: six<2,>=1.9 in /home/duckworthd/.local/lib/python3.6/site-packages (from bugsnag>=3.4.0->maestral[gui]) (1.15.0)
Requirement already satisfied: SecretStorage>=3; sys_platform == "linux" in /home/duckworthd/.local/lib/python3.6/site-packages (from keyring>=19.0.0->maestral[gui]) (3.1.2)
Requirement already satisfied: pyparsing>=2.0.2 in /home/duckworthd/.local/lib/python3.6/site-packages (from packaging->maestral[gui]) (2.4.7)
Requirement already satisfied: serpent>=1.27 in /home/duckworthd/.local/lib/python3.6/site-packages (from Pyro5>=5.7->maestral[gui]) (1.30.2)
Requirement already satisfied: pathtools>=0.1.1 in /home/duckworthd/.local/lib/python3.6/site-packages (from watchdog>=0.10.0->maestral[gui]) (0.1.2)
Requirement already satisfied: zipp>=0.5 in /home/duckworthd/.local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->maestral[gui]) (3.1.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/duckworthd/.local/lib/python3.6/site-packages (from requests->maestral[gui]) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/duckworthd/.local/lib/python3.6/site-packages (from requests->maestral[gui]) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/duckworthd/.local/lib/python3.6/site-packages (from requests->maestral[gui]) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/duckworthd/.local/lib/python3.6/site-packages (from requests->maestral[gui]) (1.25.10)
Requirement already satisfied: monotonic>=0.1 in /home/duckworthd/.local/lib/python3.6/site-packages (from fasteners->maestral[gui]) (1.5)
Collecting PyQt5>=5.9
  Downloading PyQt5-5.15.0-5.15.0-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl (76.6 MB)
     |████████████████████████████████| 76.6 MB 142 kB/s
Collecting markdown2
  Using cached markdown2-2.3.9-py2.py3-none-any.whl (34 kB)
Requirement already satisfied: cryptography in /home/duckworthd/.local/lib/python3.6/site-packages (from SecretStorage>=3; sys_platform == "linux"->keyring>=19.0.0->maestral[gui]) (3.0)
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.8.0-cp36-cp36m-manylinux1_x86_64.whl (277 kB)
     |████████████████████████████████| 277 kB 364 kB/s
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/duckworthd/.local/lib/python3.6/site-packages (from cryptography->SecretStorage>=3; sys_platform == "linux"->keyring>=19.0.0->maestral[gui]) (1.14.1)
Requirement already satisfied: pycparser in /home/duckworthd/.local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography->SecretStorage>=3; sys_platform == "linux"->keyring>=19.0.0->maestral[gui]) (2.20)
Installing collected packages: PyQt5-sip, PyQt5, markdown2, maestral-qt
Successfully installed PyQt5-5.15.0 PyQt5-sip-12.8.0 maestral-qt-1.1.0 markdown2-2.3.9
```
```
