### ISSUE TITLE
maestral throws an error related to DBusDesktopNotifier

### ISSUE THREAD

**Issue by sahilseth** [SamSchott/maestral#183]
**Describe the bug**
After indexing maestral throws an error related to DBusDesktopNotifier
**To Reproduce**

```
maestral start

maestral status

Usage:        67.6% of 7.2 GB used
Status:       Indexing local changes...
Sync threads: Running
Sync errors:  0

maestral status

Usage:        67.6% of 7.2 GB used
Status:       Indexing local changes...
Sync threads: Running
Sync errors:  0

Traceback (most recent call last):
  File "apps/conda/3/envs/maestral/lib/python3.8/site-packages/maestral/utils/notify_linux.py", line 81, in _send
    platform_nid = await self.interface.call_notify(
AttributeError: 'DBusDesktopNotifier' object has no attribute 'interface'
maestral status

Usage:        67.6% of 7.2 GB used
Status:       Unexpected error
Sync threads: Stopped
Sync errors:  0

An unexpected error occurred
Please restart Maestral to continue syncing.
```

**Expected behaviour**

```
maestral status

Usage:        67.6% of 7.2 GB used
Status:       Indexing local changes...
Sync threads: Running
Sync errors:  0
```

**System (please complete the following information):**
 - Maestral version: 1.2.0
 - OS: redhat
 - Desktop environment: cli/server
 - Qt version: NA

**Additional context**

**Comment by SamSchott** [comment]
Could you paste the log out given by `maestral log show`?

Trying to send a desktop notification will of course fail on a headless setup but this should only result in a warning printed to the log. I suspect that there is a preceding error which stops the sync threads and which actually triggered the (failed) desktop notification.

**Comment by dragoshenron** [comment]
I'm posting here instead to open a new issue because I think it's related.
I'm installing maestral on an headless setup (AWS EC2) without errors. Then 'maestral start' raise an exception:
```
Could not connect to DBUS interface
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/maestral/notify/notify_linux.py", line 58, in _init_dbus
    introspection = await self.bus.introspect(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dbus_next/aio/message_bus.py", line 216, in introspect
    return await asyncio.wait_for(future, timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dbus_next/message_bus.py", line 196, in reply_notify
    BaseMessageBus._check_method_return(reply, err, 's')
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dbus_next/message_bus.py", line 609, in _check_method_return
    raise DBusError._from_message(msg)
dbus_next.errors.DBusError: The name org.freedesktop.Notifications was not provided by any .service files
- Linking new account for 'maestral' config
- Retrieving auth code from Dropbox
? How would you like to you link your account? 
```

Also, the link for the account pairing isn't printed on screen so I can't move further.

FYI, 'maestral log show' is empty.

Any idea? Thanks

**Comment by SamSchott** [comment]
@dragoshenron, the dbus error safe to ignore. It just means that you won't get any desktop notifications (obviously, on a headless setup). Though I should probably suppress the error message, it can be confusing.

> Also, the link for the account pairing isn't printed on screen so I can't move further.

This appears to be a different issue. The CLI dialog should offer you a choice between "Open Dropbox website" (for desktop environments) and "Print auth URL to console" (for headless setups), similar to what is shown in the [wiki](https://github.com/SamSchott/maestral/wiki/Initial-Setup). The dialog is "interactive", i.e., you can choose between those options with the arrow keys. If this is not working, it will point to a more serious issue with interactive dialogs on some setups. What shell are you using? I am not at all familiar with AWS EC2.

**Comment by dragoshenron** [comment]
@SamSchott 
Quick response!
- dbus error: indeed it's confusing. Maybe you can use a try / except construct to catch the exception?

- link not printed: my bad. OF COURSE I can't open the browser from my CLI. Stupid me.

FYI, my EC2 is Ubuntu 5.4.0 / bash 5.0.17

**Comment by SamSchott** [comment]
I'm glad it's working!

> Maybe you can use a try / except construct to catch the exception?

That's already in place. But a warning message is emitted from within the except block and this warning, including the traceback, is printed to the console. It really should only end up in the logs...

**Comment by dragoshenron** [comment]
redirect of stderr?
`sys.stderr = open('logfile', 'w')
`
Just an idea...

**Comment by SamSchott** [comment]
That's pretty much already happing. It was an issue of timing: a single DesktopNotifier instance was initialised on module import while the logging setup is performed later, when the Maestral instance is initialised and we know which config file to load to determine log levels, etc.

**Comment by the-wes** [comment]
alternative suggestion: made the message clearer. something more like:

Warning: Could not connect to DBUS interface. Desktop notifications will not be delivered

that way we know what it's about and can decide whether it's a problem. changing the wording might be easier than altering the behavior.
