### ISSUE TITLE
Unexpected error due to failing unique constaint in SQLLite database

### ISSUE THREAD

**Issue by SamSchott** [SamSchott/maestral#184]
## Error in Maestral

**RuntimeError** in **.local/lib/python3.6/site-packages/maestral_qt/main.py:535**
IntegrityError

[View on Bugsnag](https://app.bugsnag.com/university-of-cambridge/maestral/errors/5f6f8632bc3aca0017b1be2f?event_id=5f6f8632005e07eed9b20000&i=gh&m=ci)

## Stacktrace

	
Traceback (most recent call last):
  File "\~/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "\~/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: index.dbx_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: index.dbx_id
[SQL: INSERT INTO "index" (dbx_path_cased, dbx_path_lower, dbx_id, item_type, last_sync, rev, content_hash) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('/Bierbrauen/Technik/kleiner_brauhelfer/kb_daten_2.sqlite', '/bierbrauen/technik/kleiner_brauhelfer/kb_daten_2.sqlite', 'id:2hHHRx4nu_YAAAAAAAAzmA', 'File', None, '015b033e0d3f1c300000001a97a5d60', 'bd4e5d0bc09c709275d11924354e1a80661dc0a2914f499429cca20df975a2bf')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

[View full stacktrace](https://app.bugsnag.com/university-of-cambridge/maestral/errors/5f6f8632bc3aca0017b1be2f?event_id=5f6f8632005e07eed9b20000&i=gh&m=ci)

*Created by Sam Schott via Bugsnag*

**Comment by SamSchott** [comment]
fixed in v1.2.1
