### ISSUE TITLE
Endless connecting-indexing loop

### ISSUE THREAD

**Issue by rnavroze** [SamSchott/maestral#186]
Maetral has suddenly decided not to work any more. The GUI icon switches between indexing files and connecting every few seconds.

Log output shows nothing significant like a connection error:
2020-09-29 20:06:35 maestral.sync INFO: Connecting...
2020-09-29 20:06:37 maestral.sync INFO: Indexing local changes...
2020-09-29 20:06:55 maestral.sync INFO: Connecting...
2020-09-29 20:06:56 maestral.sync INFO: Indexing local changes...
2020-09-29 20:07:15 maestral.sync INFO: Connecting...
2020-09-29 20:07:17 maestral.sync INFO: Indexing local changes...
2020-09-29 20:07:37 maestral.sync INFO: Connecting...
2020-09-29 20:07:38 maestral.sync INFO: Indexing local changes...
2020-09-29 20:08:03 maestral.sync INFO: Connecting...
2020-09-29 20:08:05 maestral.sync INFO: Indexing local changes...
2020-09-29 20:08:26 maestral.sync INFO: Connecting...
2020-09-29 20:08:27 maestral.sync INFO: Indexing local changes...

How can I help debug this further?

**Comment by SamSchott** [comment]
I assume your internet connection is working and you are not blocking some apps from accessing it?

If you are comfortable with Python, you can run the following in a Python terminal and check if it raises any errors:

```Python
import socket

hostname = "www.dropbox.com"
host = socket.gethostbyname(hostname)
s = socket.create_connection((host, 80), 2)
s.close()
```

If this works, there is no fundamental problem with connecting to Dropbox servers. The next step would be to query for information:

```Python
from maestral.main import Maestral

m = Maestral()
account_info = m.get_account_info()
```

This should show a very long stack of tracebacks if something goes wrong.

**Comment by rnavroze** [comment]
The first script runs and gives me no errors.
The second script also runs and does not give me any errors.

The good news is, somewhere in the middle of all this, Maestral has stopped behaving weirdly and is now staying connected.
It may have just been my internet acting weird (I did try going to dropbox.com and it worked correctly though). Unfortunately I was not able to get you any more information to debug this.

If I run into this error again, I'll run the scripts above and post their output.

**Comment by SamSchott** [comment]
Excellent. Maybe this really was a transient issue with the internet connection.

I'll close this for now, feel free to reopen if it reoccurs and suspect it really is an issue with Maestral.

**Comment by rnavroze** [comment]
This happened to me again this week, and I was able to debug it better with the improved logging:

```
2021-01-11 14:12:21 maestral.sync DEBUG: Lost connection
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1c989a3610>: Failed to establish a new connection: [Errno -3] Tempora
ry failure in name resolution
```

After trying your scripts above to ensure I was connecting to Dropbox correctly and getting no errors, I googled it and found an article pointing to `/etc/resolv.conf`, which when I opened had a nameserver entry to 192.168.0.1. I commented that out and restarted systemd-resolved and it works great now.
