### ISSUE TITLE
[BUG] Bad oauth token error after partially successful initial synch

### ISSUE THREAD

**Issue by DMR-coding** [SamSchott/maestral#223]
**Describe the bug**
I linked my account and began synching. After the first couple of directories are synched, I get the following error.
```
2020-11-16 15:25:41 maestral.sync INFO: Downloading your Dropbox
2020-11-16 15:25:42 maestral.sync INFO: Creating folders...
2020-11-16 15:25:43 maestral.sync INFO: Downloading 65/67...
2020-11-16 15:25:44 maestral.client INFO: Indexing 117...
2020-11-16 15:25:44 maestral.sync INFO: Creating folders...
2020-11-16 15:25:46 maestral.sync INFO: Downloading 14/16...
2020-11-16 15:25:46 maestral.sync ERROR: Bad input to API call
Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/client.py", line 177, in convert_api_errors
  File "Contents/Resources/app_packages/maestral/client.py", line 207, in wrapper
  File "Contents/Resources/app_packages/maestral/client.py", line 488, in download
  File "Contents/Resources/app_packages/dropbox/base.py", line 1275, in files_download
  File "Contents/Resources/app_packages/dropbox/dropbox.py", line 313, in request
  File "Contents/Resources/app_packages/dropbox/dropbox.py", line 463, in request_json_string_with_retry
  File "Contents/Resources/app_packages/dropbox/dropbox.py", line 571, in request_json_string
dropbox.exceptions.BadInputError: BadInputError('`REDACTED`', 'Error in call to API function "files/download": The given OAuth 2 access token is malformed.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/sync.py", line 3834, in startup_worker
  File "Contents/Resources/app_packages/maestral/sync.py", line 2745, in get_remote_folder
  File "Contents/Resources/app_packages/maestral/sync.py", line 2985, in apply_remote_changes
  File "Contents/Resources/Python/lib/python3.8/concurrent/futures/_base.py", line 432, in result
  File "Contents/Resources/Python/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
  File "Contents/Resources/Python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "Contents/Resources/app_packages/maestral/sync.py", line 3283, in _create_local_entry
  File "Contents/Resources/app_packages/maestral/sync.py", line 3336, in _on_remote_file
  File "Contents/Resources/app_packages/maestral/client.py", line 207, in wrapper
  File "Contents/Resources/Python/lib/python3.8/contextlib.py", line 131, in __exit__
  File "Contents/Resources/app_packages/maestral/client.py", line 179, in convert_api_errors
maestral.errors.BadInputError: Bad input to API call. Error in call to API function "files/download": The given OAuth 2 access token is malformed.
```

**To Reproduce**
Install version `1.2.2`
`maestral link`
Follow linking steps
`maestral log clear`
`maestral start`
Wait several seconds
`maestral log show`.

**Expected behaviour**
Either a successful synch, or a failure after 0 items indicating an actually bad token has been supplied.

**System (please complete the following information):**
 - Maestral version: 1.2.2 (.app build)
 - OS: macOS `10.15.7 (19H15)`
 - Desktop environment: n/a
 - Qt version: n/a

**Additional context**
This issue first occurs in `1.2.2`. I have successfully synched by downgrading to `1.2.1`.

When run in gui mode, I also get an issue where I can't quit the GUI after this error occurrs; I suspect this may be an unrelated issue, though.

Also, the redacted token in the log is NOT the access token string provided by dropbox and entered in the `link` step; I assume that's expected and it is some encoded or session-specific token, but I felt I should mention it just in case.

**Comment by SamSchott** [comment]
Thanks for the report and apologies for the issue. I'm afraid this will be very hard to debug, especially since I cannot reproduce the the error myself.

How reproducible is this with v1.2.2? Does this happen every time you link a new account and perform the initial sync? And does the sync resume after force-quitting and restarting Maestral? Or does it just occur once?

The token which is used to authenticate is a short-lived token (valid for about 4h) which is generated from a long-lived refresh token (saved in Keychain) every time the daemon is started. When the short-lived token expires or Maestral is restarted the SDK should automatically generate a new one.

BTW, the value which you redacted in the traceback is just the request ID. But it's better to be safe than sorry!

**Comment by DMR-coding** [comment]
I have 100% reproduction of this issue. Whenever I link my account w/ 1.2.2 and start the sync, it occurs. After quitting and restarting Maestral, the sync begins again and then fails again after roughly the same number of operations. (It doesn't seem to be entirely deterministic how many, though.)

Is there some verbosity option or the like I could use to gather more information about the issue for you?

**Comment by SamSchott** [comment]
You could increase the log level to debug with the CLI command `maestral log level DEBUG` but the resulting output will mostly inform you about which individual files are syncing and how conflict resolution is handled for them. This could help to identify how this error is triggered.

You can also run a couple of checks directly in bundled Python interpreter. Typing the following in Terminal should launch it:

`/Applications/Maestral.app/Contents/MacOS/Maestral --run-python`

Then you can check which authentication type is used as follows:

```Python
from maestral.main import Maestral
m = Maestral()
print(m.client.auth.token_access_type)
print(m.client.auth.refresh_token)
print(m.client.auth.access_token)
```

This should return a `token_access_type` of `'offline'`, an alphanumeric `refresh_token` and no `access_token`. If this is all ok, you can generate a short-lived access token with:

```Python
m.client.dbx.refresh_access_token()
print(m.client.dbx._oauth2_access_token)
```

The last command should print a token that starts with `sl.*`. If this looks good as well, the next step would be to manually try some API calls...

**Comment by SamSchott** [comment]
Following up on the last command, you can confirm the lifetime of the access token with:

```Python
print(m.client.dbx._oauth2_access_token_expiration)
```

**Comment by DMR-coding** [comment]
Well, that figures. My 100% reproduction has vanished. 🤷 I can no longer provoke the issue.

**Comment by SamSchott** [comment]
Glad it worked out it, though I am still very confused about this. It may have been an issue on Dropbox's side.

Feel free to reopen if it occurs again.
