### ISSUE TITLE
[BUG] Crashes when KWallet is disabled.

### ISSUE THREAD

**Issue by samuel-w** [SamSchott/maestral#245]
**Describe the bug**
When starting up for the first time, I try to link my account, and get an exception after pasting the token.

**To Reproduce**
1. Disable KWallet
2. Start maestral, go through steps until pasting token
3. Paste token, press enter
Observe that it crashes with this exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.kwalletd5': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/keyring/backends/kwallet.py", line 85, in connected
    remote_obj = bus.get_object(self.bus_name, self.object_path)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 183, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.kwalletd5': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/maestral/cli.py", line 191, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/maestral/cli.py", line 544, in start
    link_dialog(m)
  File "/home/user/.local/lib/python3.8/site-packages/maestral/cli.py", line 139, in link_dialog
    res = m.link(auth_code)
  File "/home/user/.local/lib/python3.8/site-packages/maestral/main.py", line 206, in link
    return self.client.link(token)
  File "/home/user/.local/lib/python3.8/site-packages/maestral/client.py", line 308, in link
    self.auth.save_creds()
  File "/home/user/.local/lib/python3.8/site-packages/maestral/oauth.py", line 347, in save_creds
    self.keyring.set_password("Maestral", self._account_id, token)
  File "/home/user/.local/lib/python3.8/site-packages/keyring/backends/kwallet.py", line 110, in set_password
    if not self.connected(service):
  File "/home/user/.local/lib/python3.8/site-packages/keyring/backends/kwallet.py", line 89, in connected
    raise InitError('Failed to open keyring: %s.' % e)
keyring.errors.InitError: Failed to open keyring: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.kde.kwalletd5': no such name.
```

**Expected behaviour**
For it to not crash.

**System (please complete the following information):**
 - Maestral version: 1.3.0.dev0
 - OS: Ubuntu 20.04
 - Desktop environment: KDE Plasma 5
 - Qt version: PyQt 5.15.0

**Additional context**

**Comment by SamSchott** [comment]
Oh, that's an interesting one. Thanks for spotting it!

`maestral.auth.OAuth2Session.save_creds()` only catches and handles `KeyringLocked` errors, assuming that a viable backend has already been chosen. But I see that other DBus backends such as `keyring.backends.SecretService` may also raise an `InitError` when attempting to save or load a password.

This should definitely be during save and retrieval. I am wondering if we should even go a step further and catch all `KeyringError`s.

**Comment by samuel-w** [comment]
Now I'm getting
```
ERROR:dbus.proxies:Introspect error on :1.240:/modules/kwalletd5: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
ERROR:maestral.oauth:Could not load auth token, kwallet DBusKeyring is locked
```

**Comment by SamSchott** [comment]
Yes, this is much better! It indicates that Maestral previously saved  a token in the Keyring (unsuccessfully in your case...) and now tries to load it but cannot. It then fails with an appropriate `maestral.errors.KeyringAccessError`.

In your case, it thinks it is already linked, even though it is not, due to previously unhandled error. If you run `maestral unlink` or manually delete the config file and try again, it should work.

**Comment by SamSchott** [comment]
Also, I do recommend saving the token in KWallet. The fallback will be plain text storage...

**Comment by samuel-w** [comment]
I have secretstorage set up, but its not being detected.

**Comment by samuel-w** [comment]
Yeah, it just skips over kwallet to plaintext.
Maybe reverse the order so secretstorage goes first?

**Comment by samuel-w** [comment]
Is there a reason you can't just use keyring.get_keyring() instead of trying to detect it yourself?

**Comment by SamSchott** [comment]
It should go first. The order of priorities is:

* macOS Keychain
* Any keyring implementing the SecretService Dbus specification
* KWallet
* Gnome Keyring
* Plain text storage

Typically KWallet and Gnome keyring both implement the SecretService specification and will therefore not be used directly.

> Is there a reason you can't just use keyring.get_keyring() instead of trying to detect it yourself?

The order of priorities is automatically taken from the `keyring` package:

https://github.com/SamSchott/maestral/blob/ddf9c3f7079cc09d5ed76b285f2c9232ecd83128/src/maestral/oauth.py#L171

Keyrings which are not available will not be returned by `keyring.backend.get_all_keyring()` in the first place.  The main differences in Maestral's handling are the following:

1. It restricts usage to the above options. This reduces the number of obscure errors from possibly installed 3rd party backends.
2. Once a token has been saved in a specific keyring, it will always try to load it from there until the account is unlinked.

**Comment by samuel-w** [comment]
Ah, turns out the keyring package I had is out of date. https://github.com/jaraco/keyring/commit/b92abf90b7956b3f3e950ddeb039197c4507a879 fixes my error.

**Comment by SamSchott** [comment]
Ah, ok. Good to know! This seems to be a very recent fix.
