### ISSUE TITLE
Mess with upgrade to python 3.9: Arch

### ISSUE THREAD

**Issue by coxackie** [SamSchott/maestral#249]
**Describe the bug**
Today Arch upgraded python to 3.9. Now, `maestral` fails to run. With `maestral start`, I get
```
Traceback (most recent call last):
  File "/usr/bin/maestral", line 33, in <module>
    sys.exit(load_entry_point('maestral==1.2.2', 'console_scripts', 'maestral')())
  File "/usr/bin/maestral", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/maestral/cli.py", line 25, in <module>
    import Pyro5.errors  # type: ignore
ModuleNotFoundError: No module named 'Pyro5'
```
Could you help debug this? For sure, `pyro5` 5.11 is installed, so not sure what the last part is all about.

**To Reproduce**
Latest Arch, with python 3.9, start `maestral`

**System (please complete the following information):**
 - Maestral version: 1.2.2
 - OS: Arch
 - Desktop environment: Gnome 3.38.1
 - Qt version: N/A

**Comment by SamSchott** [comment]
Oh, that is strange. I've been running Python 3.9 and Pyro 5.11 for some time now without issues.

Does a manual import of `Pyro5.errors` or `Pyro5.errors` in the Python console work?

**Comment by coxackie** [comment]
No, the console still gives me `ModuleNotFoundError: No module named 'Pyro5'`. Did you mean to any other import I should check - you have `Pyro5.errors` twice... I cannot understand, as it was working OK with python 3.8.6 before.

 What about the previous importlib mess?

 To be honest, it must be something wrong with the Arch update. It may take some time for the dust to settle. Just wondering whether I can do anything from my side to debug.

**Comment by SamSchott** [comment]
> What about the previous importlib mess?

Which importlib mess? I think this is just how console entry points work. They have a very roundabout way of loading the actual modules.

Yeah, I suspect that this is an issue with the Arch update. I think `Pyro5.errors` is the second non-builtin module which is imported. The `click` import works but it may still be a larger issue. Can you try importing some of the other dependencies listed in setup.py?

Otherwise, I can only recommend investigating the hard way. Check your PYTHONPATH, see which modules are available and check where Pyro5 has been installed...

**Comment by coxackie** [comment]
Closing this - turns out packages just needed to be "rebuilt".
