### ISSUE TITLE
exception during Maestral startup

### ISSUE THREAD

**Issue by nalim** [SamSchott/maestral#329]
**Describe the bug**

exception during Maestral startup

Traceback (most recent call last):
  File "/home/votava/.local/lib/python3.9/site-packages/maestral/sync.py", line 3509, in handle_sync_thread_errors
    yield
  File "/home/votava/.local/lib/python3.9/site-packages/maestral/sync.py", line 3678, in startup_worker
    sync.download_sync_cycle()
  File "/home/votava/.local/lib/python3.9/site-packages/maestral/sync.py", line 2682, in download_sync_cycle
    self.notify_user(downloaded)
  File "/home/votava/.local/lib/python3.9/site-packages/maestral/sync.py", line 2912, in notify_user
    self.notifier.notify("Items synced", msg, actions=buttons)
TypeError: notify() got an unexpected keyword argument 'actions'

**To Reproduce**

occassionally, during the system boot, Maestral throws the exception

**Expected behaviour**

Maestral started without an exception

**System:**

 - Maestral version: 1.4.2
 - OS: Fedora 33
 - Desktop environment: Cinnamon 4.8.6
 - PyQt version (for Linux GUI): python3-qt5-5.15.0

**Additional context**

**Comment by SamSchott** [comment]
The error occurs when trying to send a desktop notification about a changed file. You should be able to trigger it by adding a file or folder through the web interface and waiting for it sync. But it is very strange, "actions" should very much be an expected keyword argument!

Is it possible that one of the modules didn't get updated properly? Could you uninstall, delete the folder `/home/votava/.local/lib/python3.9/site-packages/maestral/` if it still exists, and reinstall and see if the problem persists?

**Comment by SamSchott** [comment]
Closing this is an issue with the installation.
