### ISSUE TITLE
LibQt 5.15 missing

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#335]
I am receiving the following exception:
```
$ maestral_qt
Traceback (most recent call last):
  File "/home/raffaele/.local/bin/maestral_qt", line 5, in <module>
    from maestral_qt.__main__ import main
  File "/home/raffaele/.local/lib/python3.8/site-packages/maestral_qt/__main__.py", line 7, in <module>
    from maestral_qt.main import run
  File "/home/raffaele/.local/lib/python3.8/site-packages/maestral_qt/main.py", line 18, in <module>
    from PyQt5 import QtCore, QtWidgets, QtGui
ImportError: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/raffaele/.local/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so)
```

Here is my Qt version:
```
$ qmake --version
QMake version 3.1
Using Qt version 5.14.2 in /usr/lib/x86_64-linux-gnu
```

**Comment by raffaem** [comment]
Fixed by

```
pip3 uninstall maestral
pip3 uninstall pyqt5
pip3 install maestral[gui]
```

Don't update pyqt, I guess

**Comment by SamSchott** [comment]
The latest version of PyQt5 should work just fine. This may be an issue of PyQt5 from PyPI vs from the distro repository. PyQt5 from PyPI would not look for libs in `/lib/x86_64-linux-gnu/` AFAIK but rather ship its own.
