### ISSUE TITLE
Connection lost - no syncing possible

### ISSUE THREAD

**Issue by walterheisenberg** [samschott/maestral#336]
**Describe the bug**
maestral shows "syncing 1/15" bit in the log there are connection errors.
maestral does not sync

**To Reproduce**
don't know. It showed up, after I set "inotify max_users ..." like in the window from maestral

**Expected behaviour**
maestral should sync

**System:**

 - Maestral version:
 - OS: Kubuntu 20.10
 - Desktop environment: KDE 5.19 (?) - Qt 5.12.8 - KDE Frameworks 5.68.0
 - PyQt version (for Linux GUI): PyQt5>=5.9 in /usr/lib/python3/dist-packages (from maestral-qt) (5.14.1)
**Additional context**
Log File:
```
2021-03-06 11:44:26 maestral.sync DEBUG: Modification of "/Schule/Schule/12/12 Verkauf/Weinkunde - /AB - Willkommen in besten Lagen .docx" detected but file content is the same as on Dropbox
2021-03-06 11:46:07 maestral.sync INFO: Connection lost
2021-03-06 11:46:07 maestral.sync DEBUG: Connection error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/client.py", line 180, in convert_api_errors
    yield
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/client.py", line 535, in upload
    session_start = self.dbx.files_upload_session_start(data)
  File "/home/ralf/.local/lib/python3.8/site-packages/dropbox/base.py", line 2993, in files_upload_session_start
    r = self.request(
  File "/home/ralf/.local/lib/python3.8/site-packages/dropbox/dropbox.py", line 313, in request
    res = self.request_json_string_with_retry(host,
  File "/home/ralf/.local/lib/python3.8/site-packages/dropbox/dropbox.py", line 463, in request_json_string_with_retry
    return self.request_json_string(host,
  File "/home/ralf/.local/lib/python3.8/site-packages/dropbox/dropbox.py", line 559, in request_json_string
    r = self._session.post(url,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/sync.py", line 3509, in handle_sync_thread_errors
    yield
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/sync.py", line 3685, in startup_worker
    sync.upload_local_changes_while_inactive()
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/sync.py", line 1563, in upload_local_changes_while_inactive
    self.apply_local_changes(sync_events)
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/sync.py", line 1784, in apply_local_changes
    for n, r in enumerate(res):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/sync.py", line 2135, in _create_remote_entry
    res = self._on_local_created(event)
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/sync.py", line 2326, in _on_local_created
    md_new = self.client.upload(
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/client.py", line 591, in upload
    raise exc
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ralf/.local/lib/python3.8/site-packages/maestral/client.py", line 185, in convert_api_errors
    raise ConnectionError("Cannot connect to Dropbox")
ConnectionError: Cannot connect to Dropbox
2021-03-06 11:46:07 maestral.sync INFO: Connecting...
2021-03-06 11:46:09 maestral.sync INFO: Fetching remote changes
2021-03-06 11:46:09 maestral.sync DEBUG: Fetching remote changes since cursor: AAFfuhxN00pjB6ATiHMy-SpxhsEWW8Pz1UWwV92dcGBpHRJqG_1vQHpE8x2wPiy435UcE2HTQAy24s5mWTrAdfHjFezXMmQavd-kvINwJecGwC5LWrZjCz51dBlWO6YtAK4yyRSG1Nkq5zK2Ii6QAYO2HeZr24hGaYX2fNXuYa0dWAQNxiRcqlC27QT89Nw0kws
2021-03-06 11:46:09 maestral.sync DEBUG: Listed remote changes:
...
```
If you need the whole debug-log, please let me know and where to find it ;)

**Comment by walterheisenberg** [comment]
As you can see above, there was an error with this file:
`/Schule/Schule/12/12 Verkauf/Weinkunde - /AB - Willkommen in besten Lagen .docx" detected but file content is the same as on Dropbox`
There was another file in the same folder:
`/Schule/Schule/12/12 Verkauf/Weinkunde - /AB - Willkommen in besten Lagen .odt`
The difference is the fileformat: docx vs odt
Maybe the space before the dot/file-ending is causing the issue?

After deleting the docx-file and removing the space before the dot, maestral does sync again ...
atm it seems to work. I'll report back

**Comment by SamSchott** [comment]
@walterheisenberg, I’m not sure I understand the problem. Occasional connection errors are expected if the internet connection is temporarily interrupted, they are nothing to worry about. This is why they show up with the log level “DEBUG” instead of “WARNING” or “ERROR”. When the connection fails, the sync daemon will immediately attempt to reconnect and resume syncing.

Any spaces in the file name should not be problematic unless the space come after the file extension, in which case there will be a sync issue notification in the GUI. Are you consistently seeing errors with a particular file name?

**Comment by walterheisenberg** [comment]
Connection errors: Why are they appearing? My internet connection is stable
Sorry for the noise, but "connection errors" on a stable connection does mean in the  most cases there is something wrong. They appear in the "normal" log also, btw.
I thought something broke the connection ... be it Dropbox or maestral ... and filed a bug-report.

before opening this bug-report, I let maestral run for about 2 hours (for 15 files).
After the 2 hours I the mentioned file was abut 12-15 times "queued", checked with "maestral activity".
Deleting this file, does a sync in a few minutes afterwards.

I had no sync errors with any file before, but I have to admit, the file was freshly added by the dropbox daemon on a windows-machine. maestral was not running while adding the file and dropbox-daemon sync.

If this is no bug, please close the bug-report.
Thx for maestral.
