### ISSUE TITLE
An unexpected error occurred - please restart maestral to continue syncing

### ISSUE THREAD

**Issue by dhdurgee** [SamSchott/maestral#388]
Linux mint x64 20.1 running current maestral.

This just popped up on my system:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/maestral/sync.py", line 3603, in handle_sync_thread_errors
    yield
  File "/usr/local/lib/python3.8/dist-packages/maestral/sync.py", line 3644, in download_worker
    has_changes = sync.wait_for_remote_changes(
  File "/usr/local/lib/python3.8/dist-packages/maestral/sync.py", line 2698, in wait_for_remote_changes
    has_changes = client.wait_for_remote_changes(last_cursor, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/maestral/client.py", line 959, in wait_for_remote_changes
    res = self.dbx.files_list_folder_longpoll(last_cursor, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/dropbox/base.py", line 2083, in files_list_folder_longpoll
    r = self.request(
  File "/usr/local/lib/python3.8/dist-packages/dropbox/dropbox_client.py", line 299, in request
    self.check_and_refresh_access_token()
  File "/usr/local/lib/python3.8/dist-packages/dropbox/dropbox_client.py", line 366, in check_and_refresh_access_token
    self.refresh_access_token(scope=self._scope)
  File "/usr/local/lib/python3.8/dist-packages/dropbox/dropbox_client.py", line 406, in refresh_access_token
    res.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.dropboxapi.com/oauth2/token

maestral status shows as paused.  I see no restart command, so I guess I need to stop, wait and start.

**Comment by SamSchott** [comment]
Thanks for the report! This probably should have been converted to an `InternalServerError` by the Dropbox SDK instead of being raised as a raw HTTP error. Maestral then would have known how to deal with it. I've opened a ticket with Dropbox at https://github.com/dropbox/dropbox-sdk-python/issues/360 but I can certainly work around it in Maestral itself in the meantime.

Dropbox servers were undergoing scheduled maintenance some time yesterday which may explain the issue. I assume it is all working again now?
