### ISSUE TITLE
Unexpected error / error message 

### ISSUE THREAD

**Issue by ChristinaGahn** [SamSchott/maestral#395]
**Describe the bug**

After a few seconds of syncing, I get notification with "Unexpected error. Please restart Maestral to continue syncing". If I click on it, I get the following error message, where it is suggested that I post it here as a bug: 

> Traceback (most recent call last):
> File "Contents/Resources/app_packages/maestral/sync.py", line 3603, in handle_sync_thread_errors
> File "Contents/Resources/app_packages/maestral/sync.py", line 3787, in startup_worker
> File "Contents/Resources/app_packages/maestral/sync.py", line 1578, in upload_local_changes_while_inactive
> File "Contents/Resources/app_packages/maestral/sync.py", line 1806, in apply_local_changes
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 440, in result
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/thread.py", line 52, in run
> File "Contents/Resources/app_packages/maestral/sync.py", line 2163, in _create_remote_entry
> File "Contents/Resources/app_packages/maestral/sync.py", line 2381, in _on_local_created
> File "Contents/Resources/app_packages/maestral/sync.py", line 1285, in to_local_path
> File "Contents/Resources/app_packages/maestral/sync.py", line 1217, in correct_case
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/typing.py", line 693, in __getattr__
> AttributeError: '_SpecialForm' object has no attribute 'get_metadata

I then have to restart Maestral to further sync it. Sometimes "Rebuilding the index" helps for a few minutes. I then get the error-message again and the whole process is repeated.

**To Reproduce**
I'm not sure, sorry. 

**Expected behaviour**
To sync my whole dropbox without error messages and restarting all the time. 

**System:**
 - Maestral version: c1.4.3
 - OS: Big Sur

**Additional context**
My user does not have administrative rights on the Mac I am using Maestral on. 
I have a Dropbox Pro account.

**Comment by SamSchott** [comment]
Oh, this is unusual error. It looks like you are using the app bundle and not the Python package, right? That should provide a very reproducible environment, but I am struggling to reproduce this issue. Are you seeing the upload error when uploading a specific file or folder or on any local change?

Could you try and see if it persists with the nightly guild from [here](https://nightly.link/SamSchott/maestral-cocoa/actions/runs/909880708/Maestral-1.4.4.dev2.dmg.zip)?

**Comment by ChristinaGahn** [comment]
Hi, 
thanks for the help! Yes, I am using the app bundle. 
I just installed the new version and it works way better than before, thanks - I am "up to date" now. 

Nevertheless, the following error message appeared two times in the process, but after restarting it worked for way longer than in the last version. I will try to provide more details when/for which files exactly the error occurs by testing it out the next days: 

> Traceback (most recent call last):
> File "Contents/Resources/app_packages/maestral/manager.py", line 557, in _handle_sync_thread_errors
> File "Contents/Resources/app_packages/maestral/manager.py", line 542, in startup_worker
> File "Contents/Resources/app_packages/maestral/sync.py", line 1580, in upload_local_changes_while_inactive
> File "Contents/Resources/app_packages/maestral/sync.py", line 1813, in apply_local_changes
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 438, in result
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/thread.py", line 52, in run
> File "Contents/Resources/app_packages/maestral/sync.py", line 2167, in _create_remote_entry
> File "Contents/Resources/app_packages/maestral/sync.py", line 2385, in _on_local_created
> File "Contents/Resources/app_packages/maestral/sync.py", line 1281, in to_local_path
> File "Contents/Resources/app_packages/maestral/sync.py", line 1187, in correct_case
> File "Contents/Resources/app_packages/maestral/sync.py", line 1226, in _correct_case_helper
> File "Contents/Resources/Support/Python/Resources/lib/python3.9/typing.py", line 693, in __getattr__
> AttributeError: '_SpecialForm' object has no attribute 'get_metadata'
>

**Comment by SamSchott** [comment]
NVM, I figured out where the issue comes from. It's just a typo in the type hints 🤦

https://github.com/SamSchott/maestral/blob/8e58b25cbefc7a84cc63cb79bf4409e99daa800f/src/maestral/sync.py#L1264

It didn't show up before because this particular function call occurs only when trying to upload an apparently new local file while there is a conflicting remote file. Most of the time, conflicting copies arise when both the local and remote versions where modified but the local file does not appear to be *completely new*. I will add a test case for this.
