### ISSUE TITLE
Maestral daemon fails to start on macOS Big Sur

### ISSUE THREAD

**Issue by rafidka** [SamSchott/maestral#411]
**Describe the bug**

I used to be able to run Maestral on macOS, but not anymore, and I wonder whether it is related to macOS Big Sur upgrade (or perhaps another upgrade?).

**To Reproduce**
1. Install `miniconda`.
2. Create a Python environment: `conda create -n dropbox python=3.8`, then activate it.
3. Start maestral with `maestral start`.

At this point, I got this error:

```
Starting Maestral...        [FAILED]
Please check logs for more information.
```

**Expected behaviour**
Maestral daemon should run.

**System:**

 - Maestral version: 1.4.4
 - Python version: 3.8
 - OS: [e.g. Ubuntu] macOS
 - Desktop environment: [e.g. Gnome 3.32] macOS
 - PyQt version (for Linux GUI): N/A

**Additional context**

When I show the logs with `maestral logs show`, I see the following:

```
2021-06-20 12:08:29 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 278, in connect_and_handshake
    sock = socketutil.create_socket(connect=connect_location,
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/socketutil.py", line 283, in create_socket
    sock.connect(connect)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 617, in start_maestral_daemon_process
    wait_for_startup(config_name, timeout)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 407, in wait_for_startup
    raise exc
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 403, in wait_for_startup
    maestral_daemon._pyroBind()
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 182, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 342, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 304, in connect_and_handshake
    raise errors.CommunicationError(err) from x
Pyro5.errors.CommunicationError: cannot connect to /Users/rafidka/Library/Application Support/maestral/maestral.sock: [Errno 2] No such file or directory
2021-06-20 12:08:29 daemon ERROR: Daemon stopped with return code -6
2021-06-20 12:12:02 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 278, in connect_and_handshake
    sock = socketutil.create_socket(connect=connect_location,
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/socketutil.py", line 283, in create_socket
    sock.connect(connect)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 617, in start_maestral_daemon_process
    wait_for_startup(config_name, timeout)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 407, in wait_for_startup
    raise exc
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 403, in wait_for_startup
    maestral_daemon._pyroBind()
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 182, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 342, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 304, in connect_and_handshake
    raise errors.CommunicationError(err) from x
Pyro5.errors.CommunicationError: cannot connect to /Users/rafidka/Library/Application Support/maestral/maestral.sock: [Errno 2] No such file or directory
2021-06-20 12:12:02 daemon ERROR: Daemon stopped with return code -6
2021-06-20 12:29:30 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 278, in connect_and_handshake
    sock = socketutil.create_socket(connect=connect_location,
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/socketutil.py", line 283, in create_socket
    sock.connect(connect)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 617, in start_maestral_daemon_process
    wait_for_startup(config_name, timeout)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 407, in wait_for_startup
    raise exc
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/maestral/daemon.py", line 403, in wait_for_startup
    maestral_daemon._pyroBind()
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 182, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 342, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.8/site-packages/Pyro5/client.py", line 304, in connect_and_handshake
    raise errors.CommunicationError(err) from x
Pyro5.errors.CommunicationError: cannot connect to /Users/rafidka/Library/Application Support/maestral/maestral.sock: [Errno 2] No such file or directory
2021-06-20 12:29:30 daemon ERROR: Daemon stopped with return code -6

```

I tried to manually execute the daemon from Python and this is what I see:

```
>>> import maestral.daemon
>>> maestral.daemon.start_maestral_daemon('maestral', True)
2021-06-20 12:26:11.732 python[43518:841675] *** Assertion failure in +[UNUserNotificationCenter currentNotificationCenter], UNUserNotificationCenter.m:54
2021-06-20 12:26:11.732 python[43518:841675] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bundleProxyForCurrentProcess is nil: mainBundle.bundleURL file:///Users/rafidka/miniconda3/envs/dropbox/bin/'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2079887b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff204d0d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff207c19e2 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff2157d512 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UserNotifications                   0x00007fff2a691540 __53+[UNUserNotificationCenter currentNotificationCenter]_block_invoke + 985
	5   libdispatch.dylib                   0x00007fff2047b806 _dispatch_client_callout + 8
	6   libdispatch.dylib                   0x00007fff2047c98c _dispatch_once_callout + 20
	7   UserNotifications                   0x00007fff2a691165 +[UNUserNotificationCenter currentNotificationCenter] + 101
	8   libffi.7.dylib                      0x000000010fb45ead ffi_call_unix64 + 85
	9   ???                                 0x00007ffee0e07210 0x0 + 140732671226384
)
libc++abi: terminating with uncaught exception of type NSException
[1]    43518 abort      python
```

**Comment by SamSchott** [comment]
Thanks for the report and the detailed tracebacks! The segfault appears to come from trying to initialise the notification center in [desktop-notifier](https://github.com/samschott/desktop-notifier).

I suspect that the issue is related to the miniconda Python installation compared to an installation with homebrew or the installer from python.org. The two latter options install a "framework" build which, in case of python.org, is properly signed. macOS requires an app bundle or framework to send desktop notifications because it wants to identify all apps that send notifications and allow users to block them. macOS 11 even goes further and requires the framework or bundle to be signed. It appears like miniconda Python installation are neither, therefore the segfault:
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bundleProxyForCurrentProcess is nil: mainBundle.bundleURL file:///Users/rafidka/miniconda3/envs/dropbox/bin/'
```

Ideally, we would want to detect this situation and just not send desktop notifications instead of crashing (or fall back to the deprecated `NSUserNotificationCenter` with less stringent requirements).

Could you check output of the following script to confirm that the above is actually correct?

```python
from rubicon.objc import ObjCClass

NSBundle = ObjCClass("NSBundle")

main_bundle = NSBundle.mainBundle

print(main_bundle.bundleURL)
print(main_bundle.bundleIdentifier)
```
