### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by erseco** [SamSchott/maestral#413]
**Describe the bug**
After install the new bundled macOS maestral I can't start the daemon

**To Reproduce**
Maestral was not starting

**Expected behaviour**
Maestral start without errors

**System:**
 - Maestral version: 1.4.5
 - Python version: Bundled
 - OS: [e.g. Ubuntu] MacOS
 - Desktop environment: [e.g. Gnome 3.32] Cocoa
 - PyQt version (for Linux GUI):

**Additional context**
```
2021-07-02 07:01:20 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/manager.py", line 557, in _handle_sync_thread_errors
  File "Contents/Resources/app_packages/maestral/manager.py", line 535, in startup_worker
  File "Contents/Resources/app_packages/maestral/sync.py", line 2774, in download_sync_cycle
  File "Contents/Resources/app_packages/maestral/sync.py", line 2905, in apply_remote_changes
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 608, in result_it
erator
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 445, in result
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_res
ult
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "Contents/Resources/app_packages/maestral/sync.py", line 3275, in _create_local_entry
  File "Contents/Resources/app_packages/maestral/sync.py", line 3471, in _on_remote_deleted
  File "Contents/Resources/app_packages/maestral/sync.py", line 3092, in _check_download_conflict
  File "Contents/Resources/app_packages/maestral/sync.py", line 3154, in _ctime_newer_than_last_sync
  File "Contents/Resources/app_packages/maestral/sync.py", line 1363, in is_excluded
IndexError: list index out of range
```

**Comment by erseco** [comment]
I removed the bundled installation, installed againt the PyPi version and after starting  I get this log

```
2021-07-02 07:12:54 sync INFO: Sync aborted
2021-07-02 07:12:54 manager INFO: Paused
2021-07-02 07:13:09 daemon INFO: Starting daemon
2021-07-02 07:13:09 daemon DEBUG: Environment:
{'COLORFGBG': '7;0',
 'COLORTERM': 'truecolor',
 'COMMAND_MODE': 'unix2003',
 'HOME': '/Users/*****',
 'HOMEBREW_CELLAR': '/opt/homebrew/Cellar',
 'HOMEBREW_PREFIX': '/opt/homebrew',
 'HOMEBREW_REPOSITORY': '/opt/homebrew',
 'INFOPATH': '/opt/homebrew/share/info:',
 'ITERM_PROFILE': 'Default',
 'ITERM_SESSION_ID': 'w0t0p0:0AC073C9-C0AD-4BD2-9756-DBCBDF956DEE',
 'LANG': 'es_ES.UTF-8',
 'LC_TERMINAL': 'iTerm2',
 'LC_TERMINAL_VERSION': '3.4.8',
 'LESS': '-R',
 'LOGNAME': '*****',
 'LSCOLORS': 'Gxfxcxdxbxegedabagacad',
 'LaunchInstanceID': 'AB557DF5-6A56-4029-AFC0-20B7293336BA',
 'MANPATH': '/opt/homebrew/share/man::',
 'OLDPWD': '/Users/ernesto',
 'PAGER': 'less',
 'PATH': '/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin',
 'PWD': '/Users/*****',
 'PYTHONOPTIMIZE': '2',
 'SECURITYSESSIONID': '186a4',
 'SHELL': '/bin/zsh',
 'SHLVL': '1',
 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.JrXisRKFYe/Listeners',
 'TERM': 'xterm-256color',
 'TERM_PROGRAM': 'iTerm.app',
 'TERM_PROGRAM_VERSION': '3.4.8',
 'TERM_SESSION_ID': 'w0t0p0:0AC073C9-C0AD-4BD2-9756-DBCBDF956DEE',
 'TMPDIR': '/var/folders/ly/hw_h04x100s84dbbm7ml75zm0000gn/T/',
 'USER': '*****',
 'XPC_FLAGS': '0x0',
 'XPC_SERVICE_NAME': '0',
 'ZSH': '/Users/ernesto/.oh-my-zsh',
 '_': '/opt/homebrew/bin/maestral',
 '__CFBundleIdentifier': 'com.googlecode.iterm2',
 '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x8'}
2021-07-02 07:13:09 daemon DEBUG: Acquired daemon lock: /Users/ernesto/Library/Application Support/maestral/maestral.lock
2021-07-02 07:13:09 daemon DEBUG: Integrating with CFEventLoop
2021-07-02 07:13:09 daemon DEBUG: Socket path: '/Users/ernesto/Library/Application Support/maestral/maestral.sock'
2021-07-02 07:13:09 daemon DEBUG: Creating Pyro daemon
2021-07-02 07:13:09 sync DEBUG: Could not load mignore rules: No such file or directory
2021-07-02 07:13:09 daemon DEBUG: Starting event loop
2021-07-02 07:13:09 manager INFO: Connected
2021-07-02 07:13:10 oauth DEBUG: Using keyring: keyring.backends.macOS.Keyring (priority: 5)
2021-07-02 07:13:10 sync DEBUG: Could not load mignore rules: No such file or directory
2021-07-02 07:13:10 sync INFO: Fetching remote changes
2021-07-02 07:13:10 sync DEBUG: Fetching remote changes since cursor: AAFpXzO2QyWpIMNUO4PHBd-6XUmEkHhyCi4T5p-3fHdiZMzMAi3ZfKEN-yuHobWA-lpr4fTZsrOUtm7dAPa6J5N8aOyF2l6SVtUD623oieivTvjrOuunKvIAmh1Kgozh_WNQWCcCEZ-iQCLNxMYUKHQH7E1AMnhuct71tB4WPXUfW-JpgkUe1XYmtPeRKF_PrmmODeviTpgLpg_FrR2cx5P_3ZlSIqQwhFlHlYHbnmPGZaFNVd97VLP_ZEj4zJ9Tvjtngqa2tSfJEIINPMhTI8OZLip9s0QkaZQoyDCBg8yDbPB87eDqDa0IK0WYfOGgyMlYqirawlntzvYtln6Y6uE4cO2rowGdFVNwAiSh-BwoKDsa1glp_Jo54pXAi4AqcswL5N_ZEzosDNGrhIwP_YTtiTnfLy0dP1HkCWBphVi-StYXEkHqTiBjRqpR58yamg3wn75pVXbR-I5qMW-pI8Ad2OZ4sV67LD-ZsGyklBvMOBsJxGbU2BgQQaAolkfoeAcDlbUaZTiJMeZG-nJeiMxv
2021-07-02 07:13:10 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/manager.py", line 557, in _handle_sync_thread_errors
    yield
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/manager.py", line 535, in startup_worker
    self.sync.download_sync_cycle(client)
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 2767, in download_sync_cycle
    for changes, cursor in changes_iter:
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 2826, in list_remote_changes_iterator
    for changes in changes_iter:
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/client.py", line 1019, in list_remote_changes_iterator
    result = self.dbx.files_list_folder_continue(last_cursor)
  File "/opt/homebrew/lib/python3.9/site-packages/dropbox/base.py", line 1976, in files_list_folder_continue
    r = self.request(
  File "/opt/homebrew/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 321, in request
    res = self.request_json_string_with_retry(host,
  File "/opt/homebrew/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 477, in request_json_string_with_retry
    return self.request_json_string(host,
  File "/opt/homebrew/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 564, in request_json_string
    raise BadInputException('Unhandled auth type: {}'.format(auth_type))
dropbox.dropbox_client.BadInputException: Unhandled auth type: app, user
```

Thank you in advance

**Comment by SamSchott** [comment]
Thanks for the report. The second issue seems to in Python Dropbox SDK and was introduced in their latest release. I've opened a ticket upstream at https://github.com/dropbox/dropbox-sdk-python/issues/369. For now, downgrading to the previous version with `pip install dropbox==11.12` should work.

The first issue is definitely on our side. I'll need to investigate.

**Comment by erseco** [comment]
After downwrading to dropbox==11.12 I get this on log:

```
2021-07-02 16:36:02 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/manager.py", line 557, in _handle_sync_thread_errors
    yield
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/manager.py", line 535, in startup_worker
    self.sync.download_sync_cycle(client)
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 2774, in download_sync_cycle
    downloaded = self.apply_remote_changes(changes)
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 2921, in apply_remote_changes
    for n, r in enumerate(res):
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/future
s/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/future
s/_base.py", line 445, in result
    return self.__get_result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/future
s/_base.py", line 390, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/future
s/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 3280, in _create_local_entry
    res = self._on_remote_folder(event)
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 3415, in _on_remote_folder
    self.update_index_from_sync_event(event)
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 928, in update_index_from_sync_event
    last_sync=self._get_ctime(event.local_path),
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 3182, in _get_ctime
    child_ctime = self._get_ctime(entry.path)
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 3183, in _get_ctime
    elif not self.is_excluded(entry.name):
  File "/opt/homebrew/lib/python3.9/site-packages/maestral/sync.py", line 1363, in is_excluded
    if dirname.split("/", 2)[1] in EXCLUDED_DIR_NAMES:
IndexError: list index out of range
```

**Comment by SamSchott** [comment]
As I send, the the `BadInputException` is problem with the Dropbox SDK which I reported earlier today and which has been since fixed.

The `IndexError` however is an actual bug in Maestral. I've just merged a pull request which should fix it and released a "pre-release" version. You can install it with `pip3 install -U --pre maestral` to try it out. If it works for you, I can release an actual update.

**Comment by erseco** [comment]
It works! Thank you so much!!!

```
Status:       Up to date
Sync errors:  0
```

```
2021-07-02 20:22:25 sync INFO: Up to date
2021-07-02 20:22:25 manager INFO: Up to date
```
