### ISSUE TITLE
maestarl UI doesn't proceed beyond the folder selection window

### ISSUE THREAD

**Issue by rafidka** [SamSchott/maestral#415]
**Describe the bug**

Cannot finish the folder selection step.

**To Reproduce**
1. Install `miniconda`.
2. Create a Python environment: `conda create -n dropbox python=3.9`, then activate it.
3. Start maestral with `maestral gui`.
4. Obtain an authentication token and proceed to the folder selection dialog.
5. Select some folders, then click "Select".

**Expected behaviour**
I should be able to finish the folder selection step and move to the next step. Instead, the Select button doesn't do anything.

**System:**

 - Maestral version: 1.4.6
 - Python version: 3.9
 - OS: [e.g. Ubuntu] macOS
 - Desktop environment: [e.g. Gnome 3.32] macOS
 - PyQt version (for Linux GUI): N/A
 

**Additional context**
In the terminal where I ran `maestral gui`, I got the following error when I clicked the "Select" button:

```
Error in async handler: 'Node' object has no attribute 'path'
Traceback (most recent call last):
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.9/site-packages/toga/handlers.py", line 25, in handler_with_cleanup
    await handler(interface, *args, **kwargs)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.9/site-packages/maestral_cocoa/private/widgets.py", line 121, in new_handler
    return await handler(widget.label)
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.9/site-packages/maestral_cocoa/setup.py", line 160, in on_items_selected
    excluded_paths = [node.path for node in excluded_nodes]
  File "/Users/rafidka/miniconda3/envs/dropbox/lib/python3.9/site-packages/maestral_cocoa/setup.py", line 160, in <listcomp>
    excluded_paths = [node.path for node in excluded_nodes]
AttributeError: 'Node' object has no attribute 'path'
```

**Comment by SamSchott** [comment]
Hrmp. I keep introducing bugs while improving things. Type hints for `maestral-cocoa` would have avoided this. I've released v1.4.7 of the macOS GUI only now. You can get it with `pip3 install -U maestral-cocoa`. 

Thanks for the report!
