### ISSUE TITLE
Unexpected error pop-up, Maestral 1.4.6 on linux mint 20.1 x64

### ISSUE THREAD

**Issue by dhdurgee** [SamSchott/maestral#432]
Had a pop-up error a little bit ago.  Contents of the window were:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/maestral/client.py", line 152, in convert_api_errors
    yield
  File "/usr/local/lib/python3.8/dist-packages/maestral/client.py", line 977, in wait_for_remote_changes
    res = self.dbx.files_list_folder_longpoll(last_cursor, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/dropbox/base.py", line 2083, in files_list_folder_longpoll
    r = self.request(
  File "/usr/local/lib/python3.8/dist-packages/dropbox/dropbox_client.py", line 299, in request
    self.check_and_refresh_access_token()
  File "/usr/local/lib/python3.8/dist-packages/dropbox/dropbox_client.py", line 367, in check_and_refresh_access_token
    self.refresh_access_token(scope=self._scope)
  File "/usr/local/lib/python3.8/dist-packages/dropbox/dropbox_client.py", line 407, in refresh_access_token
    res.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.dropboxapi.com/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/maestral/manager.py", line 557, in _handle_sync_thread_errors
    yield
  File "/usr/local/lib/python3.8/dist-packages/maestral/manager.py", line 401, in download_worker
    has_changes = self.sync.wait_for_remote_changes(
  File "/usr/local/lib/python3.8/dist-packages/maestral/sync.py", line 2723, in wait_for_remote_changes
    has_changes = client.wait_for_remote_changes(last_cursor, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/maestral/client.py", line 977, in wait_for_remote_changes
    res = self.dbx.files_list_folder_longpoll(last_cursor, timeout=timeout)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/maestral/client.py", line 154, in convert_api_errors
    raise dropbox_to_maestral_error(exc, dbx_path, local_path)
  File "/usr/local/lib/python3.8/dist-packages/maestral/client.py", line 1550, in dropbox_to_maestral_error
    if exc.request is not None and exc.request.status_code >= 500:
AttributeError: 'PreparedRequest' object has no attribute 'status_code'

**Comment by SamSchott** [comment]
Thanks for the report! This appears to be an issue with the Dropbox Auth API not being available which we are handling incorrectly. I'll look into what needs to be changed here.

Hopefully the Auth API will be up and running again soon and any corresponding Maestral errors will disappear.

**Comment by dhdurgee** [comment]
I restarted Maestral as indicated by the pop-up error and it appears to be running.

**Comment by SamSchott** [comment]
Yeah, I expected as much. But instead of raising an unexpected error with a long traceback, it should show a "Dropbox server error" with the message:

> Something went wrong on Dropbox’s end. Please check on status.dropbox.com if their services are up and running and try again later.

So in a sense this is a bug with Maestral incorrectly handling a server outage...
