### ISSUE TITLE
Can't start Maestral 1.42 or 1.46 on Mac OS Big Sur 11.5.1

### ISSUE THREAD

**Issue by wescpy** [SamSchott/maestral#436]
**Describe the bug**
I had been running 1.42 for quite awhile without issue. Today, I couldn't stop then restart the server. I upgraded to 1.46 but get the same result. Traceback looks like this:

```$ maestral gui
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/maestral/cli.py", line 708, in gui
    run(config_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/maestral_cocoa/app.py", line 595, in run
    return app.main_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/toga/app.py", line 448, in main_loop
    self._impl.main_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/toga_cocoa/app.py", line 234, in main_loop
    self.create()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/maestral_cocoa/private/implementation/cocoa/factory.py", line 737, in create
    self.interface.startup()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/maestral_cocoa/app.py", line 159, in startup
    self.load_maestral()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/maestral_cocoa/app.py", line 189, in load_maestral
    self.mdbx = self.get_or_start_maestral_daemon()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/maestral_cocoa/app.py", line 243, in get_or_start_maestral_daemon
    return MaestralProxy(self.config_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/maestral/daemon.py", line 747, in __init__
    raise CommunicationError(f"Could not get proxy for '{config_name}'")
Pyro5.errors.CommunicationError: Could not get proxy for 'maestral'```

**To Reproduce**
Both `maestral start` and `maestral gui` fail to start.

**Expected behaviour**
The server starts-up and starts syncing.

**System:**
 - Maestral version: 1.42 and 1.46
 - Python version: 3.9.1
 - OS: MacOS 11.5.1
 - Desktop environment: normal Mac Cocoa

**Additional context**
<!--- Add any other context about the problem here. --->

**Comment by SamSchott** [comment]
Thanks for the detailed report! It appears that the daemon hangs before it can create the socket for communication with frontends, though without printing any useful information to the logs itself. The hanging daemon process is then killed.

There is a similar startup issue #416 which was caused by a bug in the logging set and resulted in a hang on startup when the log level in set to `WARNING`. However, from your logs it looks like the log level is set to `INFO` here.

There are a few things which you could try:

1. Set the log level to `DEBUG`. This might hopefully show some log messages before the daemon process hangs.
2. Start the daemon with `maestral start -f -v` which will start the daemon process in the foreground (`-f | --foreground`) and print all stderr / logs directly to the console (`-v | --verbose`). If this hangs or crashes as well, it should at least give some more useful information.
3. Install the latest pre-release version from PyPI. The GUI still has a few bugs (mostly in dialogs for setup and error recovery) but the daemon startup has slightly changed. This might well your issues.

Let me know if any of this helps!
