### ISSUE TITLE
Taskbar icon not visible

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#445]
**Describe the bug**
The icon is not visible in the taskbar

**To Reproduce**
Open Maestral

**Expected behaviour**
There should be an icon in the taskbar

**System:**

 - Maestral version: 1.4.8
 - Python version: 3.9.6
 - OS: [e.g. Ubuntu] Fedora 34 Workstation
 - Desktop environment: [e.g. Gnome 3.32] GNOME 40.4.0
 - PyQt version (for Linux GUI): 5.15.4

**Additional context**

Log when I try to start maestral_qt:

```
$ maestral_qt
QSocketNotifier: Can only be used with threads started with QThread
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
^CTraceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.9/site-packages/maestral_qt/main.py", line 163, in show_when_systray_available
    def show_when_systray_available(self):
KeyboardInterrupt
^CTraceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.9/site-packages/maestral_qt/main.py", line 152, in update_ui
    def update_ui(self):
KeyboardInterrupt
^C^Z
[1]+  Stopped                 maestral_qt
```

I'm back :D

**Comment by raffaem** [comment]
If I install `python3-qt5` with `sudo dnf install python3-qt5` things get a bit better, in the sense that there is a black icon in the tray that is unresponsive to mouse clicks:

![image](https://user-images.githubusercontent.com/54762742/131730888-b3d984b4-45aa-4f00-b835-90922345e039.png)

**Comment by raffaem** [comment]
It works with GNOME on XOrg. It's only on Wayland that it doesn't work:

![image](https://user-images.githubusercontent.com/54762742/131734862-98241e0e-ecbb-4fc8-bf09-94f721bdd59f.png)

**Comment by raffaem** [comment]
It's showing now also on Wayland. 

Probably you need to reboot or something like that
