### ISSUE TITLE
maestral pauses sync when a dropbox server error is encountered

### ISSUE THREAD

**Issue by the-wes** [samschott/maestral#463]
**Describe the bug**
While a sync is in progress, this stack trace is generated:

...
2021-10-04 17:04:09 sync INFO: Indexing 957324...
...
2021-10-04 17:05:58 sync INFO: Syncing â 461/500
2021-10-04 17:06:18 manager ERROR: Dropbox server error
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.8/site-packages/maestral/client.py", line 126, in convert_api_errors
    yield
  File "/home/anaconda3/lib/python3.8/site-packages/maestral/client.py", line 1155, in list_remote_changes_iterator
    result = self.dbx.files_list_folder_continue(result.cursor)
  File "/home/anaconda3/lib/python3.8/site-packages/dropbox/base.py", line 1976, in files_list_folder_continue
    r = self.request(
  File "/home/anaconda3/lib/python3.8/site-packages/dropbox/dropbox_client.py", line 323, in request
    res = self.request_json_string_with_retry(host,
  File "/home/anaconda3/lib/python3.8/site-packages/dropbox/dropbox_client.py", line 479, in request_json_string_with_retry
    return self.request_json_string(host,
  File "/home/anaconda3/lib/python3.8/site-packages/dropbox/dropbox_client.py", line 602, in request_json_string
    raise InternalServerError(request_id, r.status_code, r.text)
dropbox.exceptions.InternalServerError: InternalServerError('593a9ccaf0c94894a0d057c39ae9d615', 500, '')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.8/site-packages/maestral/manager.py", line 791, in _handle_sync_thread_errors
    yield
  File "/home/anaconda3/lib/python3.8/site-packages/maestral/manager.py", line 769, in startup_worker
    self.sync.download_sync_cycle(client)
  File "/home/anaconda3/lib/python3.8/site-packages/maestral/sync.py", line 2829, in download_sync_cycle
    for changes, cursor in changes_iter:
  File "/home/anaconda3/lib/python3.8/site-packages/maestral/sync.py", line 2888, in list_remote_changes_iterator
    for changes in changes_iter:
  File "/home/anaconda3/lib/python3.8/site-packages/maestral/client.py", line 1156, in list_remote_changes_iterator
    yield result
  File "/home/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anaconda3/lib/python3.8/site-packages/maestral/client.py", line 128, in convert_api_errors
    raise dropbox_to_maestral_error(exc, dbx_path, local_path)
maestral.errors.DropboxServerError: Dropbox server error. Something went wrong on Dropboxâs end. Please check on status.dropbox.com if their services are up and running and try again later.
2021-10-04 17:06:18 manager INFO: Shutting down threads...
2021-10-04 17:06:18 sync INFO: Sync aborted
2021-10-04 17:06:18 manager INFO: Paused
2021-10-05 04:58:31 manager INFO: Connecting...
2021-10-05 04:58:41 manager INFO: Connected

**To Reproduce**
I don't know for sure, but I suspect the root cause of this is the absurdly large number of files I'm trying to sync. Dropbox's native sync daemon handles this level of volume well, it just doesn't run on Centos 7 like I need. So I don't think this is necessarily a limitation in Dropbox's API.

**Expected behaviour**
Maestral should wait a random amount of time and attempt to continue the sync from where it left off.

**System:**
 - Maestral version: 1.5.0
 - Python version: 3.8.3
 - OS: Centos 7
 - Desktop environment: none, running headless
 - PyQt version (for Linux GUI): none

**Additional context**
none

**Comment by the-wes** [comment]
as you can see, it aborted yesterday, and when I noticed it today, I restarted it. it ran for about an hour before aborting again with the same output. I should probably grab that log output and compare to see if it dies at exactly the same spot, which could indicate a problem with a particular file it's trying to sync.

**Comment by SamSchott** [comment]
> I suppose at this point this bug report should become a feature request. should I open a new one and close this one for that?

Leaving this as a bug report is fine. I'll discuss the issue with Dropbox support as well but some retry logic on our side makes sense to me.
