### ISSUE TITLE
Can't start daemon on Ubuntu 20.04

### ISSUE THREAD

**Issue by bjubes** [samschott/maestral#470]
**Describe the bug**
Maestral fails to connect to daemon and gives an error dialog

**To Reproduce**
launch maestral via gui or using `maestral gui` or `maestral start`

I get this output:
```
 maestral gui
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/brian/.local/lib/python3.8/site-packages/maestral/daemon.py", line 376, in start_maestral_daemon
    from .main import Maestral
  File "/home/brian/.local/lib/python3.8/site-packages/maestral/main.py", line 40, in <module>
    from .client import CONNECTION_ERRORS, DropboxClient, convert_api_errors
  File "/home/brian/.local/lib/python3.8/site-packages/maestral/client.py", line 47, in <module>
    from .oauth import OAuth2Session
  File "/home/brian/.local/lib/python3.8/site-packages/maestral/oauth.py", line 35, in <module>
    keyring.backends.macOS.Keyring,
AttributeError: module 'keyring.backends.macOS' has no attribute 'Keyring'
Traceback (most recent call last):
  File "/home/brian/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/home/brian/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/brian/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/brian/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/brian/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/brian/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/brian/.local/lib/python3.8/site-packages/maestral/cli.py", line 708, in gui
    run(config_name)
  File "/home/brian/.local/lib/python3.8/site-packages/maestral_qt/main.py", line 631, in run
    maestral_gui.load_maestral()
  File "/home/brian/.local/lib/python3.8/site-packages/maestral_qt/main.py", line 183, in load_maestral
    self.mdbx = self.get_or_start_maestral_daemon()
  File "/home/brian/.local/lib/python3.8/site-packages/maestral_qt/main.py", line 219, in get_or_start_maestral_daemon
    return MaestralProxy(self.config_name)
  File "/home/brian/.local/lib/python3.8/site-packages/maestral/daemon.py", line 655, in __init__
    raise CommunicationError(f"Could not get proxy for '{config_name}'")
Pyro5.errors.CommunicationError: Could not get proxy for 'maestral'
```

**System:**

 - Maestral version: 5.15.4
 - Python version: 3.8.10
 - OS: Ubuntu 20.04
 - Desktop environment: Gnome
 - PyQt version (for Linux GUI): 5.15.4

**Comment by SamSchott** [comment]
Which version of the `keyring` package do you have installed? Could you try updating to the latest?
