### ISSUE TITLE
Bulk deletion of files when underlying storage disappears

### ISSUE THREAD

**Issue by techman83** [samschott/maestral#473]
**Describe the bug**
This might be better as a feature request, but when syncing a large amount of deletes it may be prudent to check that the storage can be accessed. Though the storage disappearing from underneath the client is probably rather edge case and not sure this could even be handled gracefully!
```
2021-10-17 06:03:27 sync INFO: Deleting 49773/49779...
2021-10-17 06:03:29 manager INFO: Up to date
2021-10-17 06:03:33 manager INFO: Syncing...
2021-10-17 06:03:33 sync INFO: Fetching remote changes
2021-10-17 06:03:35 sync INFO: Indexing 993...
2021-10-17 06:03:35 sync INFO: Applying deletions...
2021-10-17 06:03:35 sync INFO: Deleting 1/1...
2021-10-17 06:03:37 sync INFO: Deleting 8/337...
2021-10-17 06:03:39 sync INFO: Deleting 235/337...
2021-10-17 06:03:41 sync INFO: Deleting 110/345...
2021-10-17 06:03:43 sync INFO: Deleting 337/345...
2021-10-17 06:03:45 manager ERROR: Cannot create cache directory: Transport endpoint is not connected
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 1144, in _new_tmp_file
    with NamedTemporaryFile(dir=self.file_cache_path, delete=False) as f:
  File "/usr/lib/python3.6/tempfile.py", line 690, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 107] Transport endpoint is not connected: '/data/Dropbox/Dropbox/.maestral.cache/tmp324zkcdb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/manager.py", line 791, in _handle_sync_thread_errors
    yield
  File "/usr/local/lib/python3.6/dist-packages/maestral/manager.py", line 636, in download_worker
    self.sync.download_sync_cycle(client)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2836, in download_sync_cycle
    downloaded = self.apply_remote_changes(changes)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 3004, in apply_remote_changes
    for n, r in enumerate(res):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 3328, in _create_local_entry
    res = self._on_remote_file(event, client)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 3384, in _on_remote_file
    tmp_fname = self._new_tmp_file()
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 1155, in _new_tmp_file
    "Please check if you have write permissions for "
maestral.errors.CacheDirError: Cannot create cache directory: Transport endpoint is not connected. Please check if you have write permissions for /data/Dropbox/Dropbox/.maestral.cache.
2021-10-17 06:03:45 manager INFO: Shutting down threads...
2021-10-17 06:03:45 sync INFO: Sync aborted
2021-10-17 06:03:45 manager INFO: Paused
```

**To Reproduce**
1. Maestral pointed Remote storage
2. Disconnect storage from underneath the OS

**Expected behaviour**
Maestral to fail gracefully if it can't read/write to the Dropbox location that is configured

**System:**
 - Maestral version: 1.5.0
 - Python version: 3.6.9
 - OS: Ubuntu 18.04.6 LTS
 - Desktop environment: N/A - headless
 - PyQt version (for Linux GUI): N/A

**Additional context**
These are glusterfs bricks mounted via glusterfs 3.13.2. It's all pretty low performance and sketchy (couple of BananaPi boards, built when not many SBCs had Sata) and a x86 box based on an AMD Jaguar. It has been working really well, albeit a little slow due to the storage bottleneck since the early releases of maestral after dropbox decided to end support for non ext4 drives.

The only trouble is the rewind feature is either currently broken or can't deal with a changeset with 60,000+ files, so I'm waiting for support to roll it back (though I keep multiple offline external backups of the files as well).

**Additional Additional context**
Dropbox were pretty responsive and rolled back things to just before it happened, so no harm done. But it has run like this for a very long time, including with the official dropbox client before it got kneecapped. Now it's possible I've gotten lucky, but I know for sure at least a few times the storage layer has gone wonky and the client just bailed out. I just re-mounted and restarted the services. This is the first time I've encountered anything beyond a sync conflict and it was pretty soon after upgrading to 1.5.0.

**Comment by techman83** [comment]
After the rollback I got around to turning maestral back on. Before that I dug into the Filesystem and the gluster host it was mapped against was quite wonky. So the FS was kinda mapped, but kinda not.

```
2021-10-21 10:11:10 sync INFO: Up to date
2021-10-21 10:11:10 sync INFO: Indexing local changes...
2021-10-21 10:29:11 sync INFO: Syncing ↑ 1/1
2021-10-21 10:29:11 manager INFO: Up to date
2021-10-21 10:29:12 manager INFO: Syncing...
2021-10-21 10:29:14 sync INFO: Syncing ↑ 1/2
2021-10-21 10:29:15 manager INFO: Up to date
2021-10-21 10:29:16 manager INFO: Syncing...
2021-10-21 10:29:16 sync INFO: Fetching remote changes
2021-10-21 10:29:16 sync INFO: Indexing 1...
2021-10-21 10:29:16 sync INFO: Syncing ↓ 1/1
2021-10-21 10:29:17 sync INFO: Up to date
2021-10-21 10:29:17 manager INFO: Up to date
```

If this is well in "Won't Fix" territory, I don't mind if it's closed. If it happens again I might dive into the deletion code and see if there is a way to guard against it :slightly_smiling_face:

**Comment by samschott** [comment]
Closing since this is indeed a very niche issue and in the Won't Fix territory for me.
