### ISSUE TITLE
Indexing remote Dropbox forever

### ISSUE THREAD

**Issue by chrisdrackett** [samschott/maestral#491]
**Describe the bug**
I just set the app up yesterday afternoon and was hoping to get my fairly small dropbox synced. However its now ~24 hours later and the app is still reporting `Indexing remote Dropbox`

**To Reproduce**
install app and login to dropbox

**Expected behaviour**
files download

**System:**

 - Maestral version: 1.5.1
 - Python version: 3.8.9
 - OS: [e.g. Ubuntu] macOS
 - Desktop environment: [e.g. Gnome 3.32]
 - PyQt version (for Linux GUI):

**Additional context**

**Comment by tjluoma** [comment]
I am having the same issue.

Here is my DEBUG-level log: [maestral.zip](https://github.com/SamSchott/maestral/files/7532247/maestral.zip)

**Comment by tjluoma** [comment]
I just tried this again with a fresh set of preferences, and it ran overnight but never produced any output at all, and never sync'd anything either.

I've had to install the regular Dropbox app for the time being, as this just is not working at all, and I don't know what else to try.

**Comment by SamSchott** [comment]
@tjluoma, sorry for the slow response, I'm in the process of moving between countries at the moment and did not have much time to look into this. The DBUG logs are very helpful, it appears that the Dropbox API call to list remote items consistently raises an `InternalServerError` in your case and Maestral defaults to just retrying the request. This explains the constant indexing loop which you are seeing.

The next step will be to find out why this error specifically occurs for your account. The massive HTML dump in the response from Dropbox servers, as logged in the file which you provided, just renders as a webpage showing the following message:

> Something went wrong. Don't worry, your files are still safe and the Dropboxers have been notified. Check out our Help Center and forums for help, or head back to home.

The actual html from the logs also includes a cute image.

<details>
  <summary>Click to expand HTML source</summary>
```html
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Dropbox - 5xx</title>
<link href="https://cfl.dropboxstatic.com/static/css/error.css" rel="stylesheet" type="text/css"/>
<link rel="shortcut icon" href="https://cfl.dropboxstatic.com/static/images/favicon.ico"/>

</head>
<body>
<div class="figure">
<img src="https://cfl.dropboxstatic.com/static/images/illustration_catalog/sickbox-illo_m1.png" srcset="https://cfl.dropboxstatic.com/static/images/illustration_catalog/sickbox-illo_m1@2x.png 2x" alt="Error: 5xx"/>
</div>
<div id="errorbox">
<h1>Error (5xx)</h1>Something went wrong. Don't worry, your files are still safe and the Dropboxers have been notified. Check out our <a href="https://www.dropbox.com/help">Help Center</a> and <a href="https://forums.dropbox.com">forums</a> for help, or head back to <a href="https://www.dropbox.com/home">home</a>.
</div>

<script>
message = {"ru": "\u003ch1\u003e\u041e\u0448\u0438\u0431\u043a\u0430 (5xx)\u003c/h1\u003e\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u0430\u044f \u043e\u0448\u0438\u0431\u043a\u0430. \u041d\u0435 \u0431\u0435\u0441\u043f\u043e\u043a\u043e\u0439\u0442\u0435\u0441\u044c, \u0432\u0430\u0448\u0438 \u0444\u0430\u0439\u043b\u044b \u043d\u0435 \u043f\u043e\u0441\u0442\u0440\u0430\u0434\u0430\u043b\u0438, \u0430 \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u0438 Dropbox \u043f\u043e\u043b\u0443\u0447\u0438\u043b\u0438 \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u0435. \u041f\u0435\u0440\u0435\u0439\u0434\u0438\u0442\u0435 \u0432 \u003ca href=\"https://www.dropbox.com/help\"\u003e\u0441\u043f\u0440\u0430\u0432\u043e\u0447\u043d\u044b\u0439 \u0446\u0435\u043d\u0442\u0440\u003c/a\u003e \u0438\u043b\u0438 \u043d\u0430 \u003ca href=\"https://forums.dropbox.com\"\u003e\u0444\u043e\u0440\u0443\u043c\u044b\u003c/a\u003e \u0434\u043b\u044f \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u043f\u043e\u043c\u043e\u0449\u0438 \u0438\u043b\u0438 \u0432\u0435\u0440\u043d\u0438\u0442\u0435\u0441\u044c \u043d\u0430 \u003ca href=\"https://www.dropbox.com/home\"\u003e\u0434\u043e\u043c\u0430\u0448\u043d\u044e\u044e \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443\u003c/a\u003e.", "fr": "\u003ch1\u003eErreur (5xx)\u003c/h1\u003eUn probl\u00e8me est survenu. Ne vous inqui\u00e9tez pas, vos fichiers sont toujours en s\u00e9curit\u00e9 et les Dropboxeurs ont \u00e9t\u00e9 avertis. Consultez notre \u003ca href=\"https://www.dropbox.com/help\"\u003ecentre d'assistance\u003c/a\u003e et nos \u003ca href=\"https://forums.dropbox.com\"\u003eforums\u003c/a\u003e pour obtenir de l'aide, ou retournez sur la \u003ca href=\"https://www.dropbox.com/home\"\u003epage d'accueil\u003c/a\u003e.", "zh_TW": "\u003ch1\u003e\u932f\u8aa4 (5xx)\u003c/h1\u003e\u767c\u751f\u932f\u8aa4\u3002\u5225\u64d4\u5fc3\uff0c\u60a8\u7684\u6a94\u6848\u5b89\u5168\u7121\u865e\uff0c\u5df2\u901a\u77e5 Dropbox \u54e1\u5de5\u3002\u8acb\u5230\u6211\u5011\u7684\u003ca href=\"https://www.dropbox.com/help\"\u003e\u8aaa\u660e\u4e2d\u5fc3\u003c/a\u003e\u548c\u003ca href=\"https://forums.dropbox.com\"\u003e\u8a0e\u8ad6\u5340\u003c/a\u003e\u53d6\u5f97\u5354\u52a9\uff0c\u6216\u662f\u56de\u5230\u003ca href=\"https://www.dropbox.com/home\"\u003e\u9996\u9801\u003c/a\u003e\u3002", "th_TH": "\u003ch1\u003e\u0e02\u0e49\u0e2d\u0e1c\u0e34\u0e14\u0e1e\u0e25\u0e32\u0e14 5xx\u003c/h1\u003e\u0e21\u0e35\u0e1a\u0e32\u0e07\u0e2d\u0e22\u0e48\u0e32\u0e07\u0e17\u0e35\u0e48\u0e44\u0e21\u0e48\u0e16\u0e39\u0e01\u0e15\u0e49\u0e2d\u0e07 \u0e44\u0e21\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e40\u0e1b\u0e47\u0e19\u0e2b\u0e48\u0e27\u0e07 \u0e44\u0e1f\u0e25\u0e4c\u0e02\u0e2d\u0e07\u0e04\u0e38\u0e13\u0e22\u0e31\u0e07\u0e1b\u0e25\u0e2d\u0e14\u0e20\u0e31\u0e22\u0e41\u0e25\u0e30 Dropboxer \u0e44\u0e14\u0e49\u0e23\u0e31\u0e1a\u0e01\u0e32\u0e23\u0e41\u0e08\u0e49\u0e07\u0e40\u0e15\u0e37\u0e2d\u0e19\u0e41\u0e25\u0e49\u0e27 \u0e42\u0e1b\u0e23\u0e14\u0e14\u0e39\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14\u0e17\u0e35\u0e48 \u003ca href=\"https://www.dropbox.com/help\"\u003e\u0e28\u0e39\u0e19\u0e22\u0e4c\u0e04\u0e27\u0e32\u0e21\u0e0a\u0e48\u0e27\u0e22\u0e40\u0e2b\u0e25\u0e37\u0e2d\u003c/a\u003e \u0e41\u0e25\u0e30 \u003ca href=\"https://forums.dropbox.com\"\u003e\u0e1f\u0e2d\u0e23\u0e31\u0e21\u003c/a\u003e \u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e02\u0e2d\u0e04\u0e27\u0e32\u0e21\u0e0a\u0e48\u0e27\u0e22\u0e40\u0e2b\u0e25\u0e37\u0e2d \u0e2b\u0e23\u0e37\u0e2d\u0e01\u0e25\u0e31\u0e1a\u0e44\u0e1b\u0e17\u0e35\u0e48 \u003ca href=\"https://www.dropbox.com/home\"\u003e\u0e2b\u0e19\u0e49\u0e32\u0e41\u0e23\u0e01\u003c/a\u003e", "pt_BR": "\u003ch1\u003eErro ( 5xx ).\u003c/h1\u003eDeu algo errado, mas n\u00e3o se preocupe. Os seus arquivos permanecem em seguran\u00e7a, e a equipe do Dropbox j\u00e1 foi notificada. Confira nossa \u003ca href=\"https://www.dropbox.com/help\"\u003eCentral de ajuda\u003c/a\u003e e \u003ca href=\"https://forums.dropbox.com\"\u003enossos f\u00f3runs\u003c/a\u003e para obter ajuda ou volte para a \u003ca href=\"https://www.dropbox.com/home\"\u003ep\u00e1gina inicial\u003c/a\u003e.", "zh_CN": "\u003ch1\u003e\u9519\u8bef (5xx)\u003c/h1\u003e \u51fa\u73b0\u95ee\u9898\u3002\u522b\u62c5\u5fc3\uff0c\u60a8\u7684\u6587\u4ef6\u4ecd\u5b89\u5168\uff0c\u800c\u4e14 Dropbox \u5458\u5de5\u5df2\u6536\u5230\u901a\u77e5\u3002\u8bf7\u67e5\u9605\u6211\u4eec\u7684\u003ca href=\"https://www.dropbox.com/help\"\u003e\u5e2e\u52a9\u4e2d\u5fc3\u003c/a\u003e\u548c \u003ca href=\"https://forums.dropbox.com\"\u003e\u8bba\u575b\u003c/a\u003e\u83b7\u53d6\u5e2e\u52a9\uff0c\u6216\u8fd4\u56de \u003ca href=\"https://www.dropbox.com/home\"\u003e\u4e3b\u9875\u003c/a\u003e\u3002", "da_DK": "\u003ch1\u003eFejl (5xx)\u003c/h1\u003e Noget gik galt. Men ingen grund til bekymring, dine filer er sikre, og Dropboxerne har f\u00e5et besked. Tjek vores \u003ca href=\"https://www.dropbox.com/help\"\u003eHj\u00e6lpecenter\u003c/a\u003e og \u003ca href=\"https://forums.dropbox.com\"\u003eforummer\u003c/a\u003e for hj\u00e6lp, eller g\u00e5 tilbage til \u003ca href=\"https://www.dropbox.com/home\"\u003estart\u003c/a\u003e.", "de": "\u003ch1\u003eFehler (5xx)\u003c/h1\u003eEtwas ist schiefgelaufen. Ihre Dateien sind aber immer noch sicher und Dropbox wurde benachrichtigt. Schauen Sie sich im \u003ca href=\"https://www.dropbox.com/help\"\u003eHilfecenter\u003c/a\u003e und in den \u003ca href=\"https://forums.dropbox.com\"\u003eForen\u003c/a\u003e um, wenn Sie Hilfe ben\u00f6tigen, oder kehren Sie zur\u00fcck auf die \u003ca href=\"https://www.dropbox.com/home\"\u003eStartseite\u003c/a\u003e.", "ko": "\u003ch1\u003e\uc624\ub958(5xx)\u003c/h1\u003e\ubb38\uc81c\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4. \ud30c\uc77c\uc740 \uc548\uc804\ud558\uac8c \ubcf4\uad00\ub418\uc5b4 \uc788\uc73c\ub2c8 \uc548\uc2ec\ud558\uc138\uc694. \uc774 \ubb38\uc81c\ub294 Dropbox \ub2f4\ub2f9\uc790\uc5d0\uac8c \uc804\ub2ec\ub418\uc5c8\uc73c\uba70, \ub3c4\uc6c0\uc774 \ud544\uc694\ud55c \uacbd\uc6b0 Dropbox\uc758 \u003ca href=\"https://www.dropbox.com/help\"\u003e\ub3c4\uc6c0\ub9d0 \uc13c\ud130\u003c/a\u003e \ubc0f \u003ca href=\"https://forums.dropbox.com\"\u003e\ud3ec\ub7fc\u003c/a\u003e\uc744 \ucc38\uc870\ud558\uac70\ub098 \u003ca href=\"https://www.dropbox.com/home\"\u003e\ud648\u003c/a\u003e\uc73c\ub85c \ub3cc\uc544\uac00\uc138\uc694.", "it": "\u003ch1\u003eErrore (5xx)\u003c/h1\u003eQualcosa \u00e8 andato storto. Non ti preoccupare i tuoi file sono comunque al sicuro e i Dropboxer sono stati notificati. Consulta il \u003ca href=\"https://www.dropbox.com/help\"\u003eCentro assistenza\u003c/a\u003e e \u003ca href=\"https://forums.dropbox.com\"\u003ei forum\u003c/a\u003e per assistenza oppure torna alla \u003ca href=\"https://www.dropbox.com/home\"\u003ehomepage\u003c/a\u003e.", "ja": "\u003ch1\u003e\u30a8\u30e9\u30fc\uff085xx\uff09\u304c\u767a\u751f\u3057\u307e\u3057\u305f\u3002\u003c/h1\u003e\u30d5\u30a1\u30a4\u30eb\u306f\u5b89\u5168\u3067\u3059\u306e\u3067\u3054\u5b89\u5fc3\u304f\u3060\u3055\u3044\u3002Dropbox \u306b\u306f\u65e2\u306b\u901a\u77e5\u3055\u308c\u3066\u3044\u307e\u3059\u3002\u003ca href=\"https://www.dropbox.com/help\"\u003e\u30d8\u30eb\u30d7\u30bb\u30f3\u30bf\u30fc\u003c/a\u003e\u3084\u003ca href=\"https://forums.dropbox.com\"\u003e\u30d5\u30a9\u30fc\u30e9\u30e0\u003c/a\u003e\u3092\u53c2\u7167\u3059\u308b\u304b\u3001[\u003ca href=\"https://www.dropbox.com/home\"\u003e\u30db\u30fc\u30e0\u003c/a\u003e] \u30da\u30fc\u30b8\u306b\u623b\u3063\u3066\u304f\u3060\u3055\u3044\u3002", "uk_UA": "\u003ch1\u003e\u041f\u043e\u043c\u0438\u043b\u043a\u0430 (5xx)\u003c/h1\u003e\u0429\u043e\u0441\u044c \u043f\u0456\u0448\u043b\u043e \u043d\u0435 \u0442\u0430\u043a. \u041d\u0435 \u0445\u0432\u0438\u043b\u044e\u0439\u0442\u0435\u0441\u044f, \u0432\u0430\u0448\u0456 \u0444\u0430\u0439\u043b\u0438 \u0432 \u0431\u0435\u0437\u043f\u0435\u0446\u0456, \u0430 \u043f\u0440\u0430\u0446\u0456\u0432\u043d\u0438\u043a\u0438 Dropbox \u0443\u0436\u0435 \u0432 \u043a\u0443\u0440\u0441\u0456 \u043f\u043e\u0434\u0456\u0439. \u041f\u0435\u0440\u0435\u0433\u043b\u044f\u043d\u044c\u0442\u0435 \u003ca href=\"https://www.dropbox.com/help\"\u003e\u0426\u0435\u043d\u0442\u0440 \u0434\u043e\u0432\u0456\u0434\u043a\u0438\u003c/a\u003e \u0442\u0430 \u003ca href=\"https://forums.dropbox.com\"\u003e\u0444\u043e\u0440\u0443\u043c\u0438\u003c/a\u003e \u0430\u0431\u043e \u043f\u043e\u0432\u0435\u0440\u043d\u0456\u0442\u044c\u0441\u044f \u043d\u0430 \u003ca href=\"https://www.dropbox.com/home\"\u003e\u0433\u043e\u043b\u043e\u0432\u043d\u0443 \u0441\u0442\u043e\u0440\u0456\u043d\u043a\u0443\u003c/a\u003e.", "nl_NL": "\u003ch1\u003eFout (5xx).\u003c/h1\u003eEr is iets misgegaan. Maak je geen zorgen, je bestanden zijn veilig en de Dropboxers zijn op de hoogte gesteld. Kijk in ons \u003ca href=\"https://www.dropbox.com/help\"\u003eHelpcentrum\u003c/a\u003e en de \u003ca href=\"https://forums.dropbox.com\"\u003eforums\u003c/a\u003e voor hulp of ga terug naar de \u003ca href=\"https://www.dropbox.com/home\"\u003estartpagina\u003c/a\u003e.", "pl": "\u003ch1\u003eB\u0142\u0105d (5xx)\u003c/h1\u003eWyst\u0105pi\u0142y problemy. Nie martw si\u0119, Twoje pliki s\u0105 nadal bezpieczne, a\u00a0pracownicy us\u0142ugi Dropbox zostali powiadomieni. Odwied\u017a \u003ca href=\"https://www.dropbox.com/help\"\u003eCentrum pomocy\u003c/a\u003e i\u00a0\u003ca href=\"https://forums.dropbox.com\"\u003efora\u003c/a\u003e, aby uzyska\u0107 pomoc, lub przejd\u017a do \u003ca href=\"https://www.dropbox.com/home\"\u003estrony g\u0142\u00f3wnej\u003c/a\u003e.", "sv_SE": "\u003ch1\u003eFel (5xx)\u003c/h1\u003e N\u00e5got gick fel. Oroa dig inte. Dina filer \u00e4r fortfarande s\u00e4kra och Dropboxare har meddelats. Kolla in v\u00e5rt \u003ca href=\"https://www.dropbox.com/help\"\u003eHj\u00e4lpcenter\u003c/a\u003e och \u003ca href=\"https://forums.dropbox.com\"\u003ev\u00e5ra forum\u003c/a\u003e f\u00f6r att f\u00e5 hj\u00e4lp eller g\u00e5 tillbaka till \u003ca href=\"https://www.dropbox.com/home\"\u003estartsidan.\u003c/a\u003e", "en_GB": "\u003ch1\u003eError (5xx)\u003c/h1\u003eSomething went wrong. Don't worry, your files are still safe and the Dropboxers have been notified. Check out our \u003ca href=\"https://www.dropbox.com/help\"\u003eHelp Centre\u003c/a\u003e and \u003ca href=\"https://forums.dropbox.com\"\u003eforums\u003c/a\u003e for help, or head back \u003ca href=\"https://www.dropbox.com/home\"\u003ehome\u003c/a\u003e.", "ms": "\u003ch1\u003eRalat (5xx)\u003c/h1\u003eAda sesuatu yang tidak kena. Jangan risau, fail masih selamat dan Dropboxer telah dimaklumkan. Lihat \u003ca href=\"https://www.dropbox.com/help\"\u003ePusat Bantuan\u003c/a\u003e dan \u003ca href=\"https://forums.dropbox.com\"\u003eforum\u003c/a\u003e kami untuk bantuan, atau kembali ke \u003ca href=\"https://www.dropbox.com/home\"\u003eutama\u003c/a\u003e.", "es_ES": "\u003ch1\u003eError (5xx)\u003c/h1\u003eSe ha producido un error. No te preocupes, los archivos est\u00e1n a salvo y los Dropboxers est\u00e1n al tanto. Visita nuestro \u003ca href=\"https://www.dropbox.com/help\"\u003eCentro de ayuda\u003c/a\u003e y los \u003ca href=\"https://forums.dropbox.com\"\u003eforos\u003c/a\u003e si necesitas que te echen una mano, o bien vuelve a la \u003ca href=\"https://www.dropbox.com/home\"\u003ep\u00e1gina principal\u003c/a\u003e.", "nb_NO": "\u003ch1\u003eFeilmelding (5xx)\u003c/h1\u003eNoe gikk galt. Ikke bekymre deg, filene dine er trygge og Dropbox er varslet. Sjekk ut v\u00e5rt \u003ca href=\"https://www.dropbox.com/help\"\u003ehjelpesenter\u003c/a\u003e og \u003ca href=\"https://forums.dropbox.com\"\u003efora\u003c/a\u003e for hjelp, eller g\u00e5 tilbake til \u003ca href=\"https://www.dropbox.com/home\"\u003ehjemmesiden\u003c/a\u003e.", "id": "\u003ch1\u003eKesalahan(5xx)\u003c/h1\u003eAda yang salah. Jangan cemas, file Anda tetap aman dan Dropboxer sudah diberi tahu. Kunjungi \u003ca href=\"https://www.dropbox.com/help\"\u003ePusat Bantuan\u003c/a\u003e dan \u003ca href=\"https://forums.dropbox.com\"\u003eforum\u003c/a\u003e kami untuk mendapatkan bantuan, atau kembalilah ke \u003ca href=\"https://www.dropbox.com/home\"\u003ehalaman awal\u003c/a\u003e.", "es": "\u003ch1\u003eError (5xx)\u003c/h1\u003eSe ha producido un error. No te preocupes, los archivos est\u00e1n a salvo y los Dropboxers est\u00e1n al tanto. Visita nuestro \u003ca href=\"https://www.dropbox.com/help\"\u003eCentro de ayuda\u003c/a\u003e y los \u003ca href=\"https://forums.dropbox.com\"\u003eforos\u003c/a\u003e si necesitas que te echen una mano, o bien vuelve a la \u003ca href=\"https://www.dropbox.com/home\"\u003ep\u00e1gina principal\u003c/a\u003e."};
function read_cookie (name) {
        var nameEQ = name + "=";
        var ca = document.cookie.split(';');
        for (var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1, c.length);
            }
            if (c.indexOf(nameEQ) === 0) {
                return c.substring(nameEQ.length, c.length);
            }
        }
        return null;
}
function localize() {
    var locale = read_cookie('locale');
    if (locale) {
       var msg = message[locale];
       if (msg) {
           var elem = document.getElementById('errorbox');
           if (elem) {
               elem.innerHTML = msg;
           }
       }
    }
}
localize();
</script>

</body>
</html>
```
</details>

I'll contact Dropbox with one of the request IDs from the log and see if they can check what went wrong on their end.

**Comment by tjluoma** [comment]
FWIW, I tried it again tonight with the same DEBUG log level and `maestral activity` shows no output at all.

I would love to know what's happening and how to fix it.

**Comment by SamSchott** [comment]
I've reported the error together with a few request IDs from the log to Dropbox now. They should be able to trace the API calls and check what went wrong, though I don't expect a response before tomorrow.

**Comment by SamSchott** [comment]
@tjluoma, can you check if the selective sync dialog succeeds in listing remotes folders? You can open it under "Preferences > Select Files and Folders...".

**Comment by tjluoma** [comment]
Selective Sync does list them, almost immediately, but I cannot change any of them. It says "Try again when idle" whenever I try.

**Comment by SamSchott** [comment]
Thanks for the info! The selective sync dialog uses the same Dropbox API endpoint like indexing but with different parameters (indexing recurses over folder contents while selective sync only loads one level at a time). Dropbox have replied that they are looking into the problem as it appears to be on their server. Let's see what they come back with.

**Comment by tjluoma** [comment]
Any news on this one?

**Comment by SamSchott** [comment]
Sorry, no news so far. Dropbox has been silent on this and there is nothing I can do on my end. I'll poke them again.

**Comment by tjluoma** [comment]
In case anyone was wondering, based on my testing, you cannot fix this issue by removing all files and folders from your Dropbox account.

It still appears to not be able to index my Dropbox account, even though there is nothing in my Dropbox account.

Oh well, it was worth a shot.

**Comment by tjluoma** [comment]
Please ask them again. We've been waiting for a very long time.

**Comment by samschott** [comment]
I have just now. I'll let you know as soon as there are any updates.

In the meantime, since you now have the Python package installed, could check if the following commands work for you:

```Python

from maestral.main import Maestral

m = Maestral()
m.client.list_folder("/")
m.client.list_folder("/", recursive=True)
```

I would expect the second command to reproduce the `InternalServerError` that you have been seeing.

**Comment by tjluoma** [comment]
`m.client.list_folder("/", recursive=True)` just hung there, and gave no response whatsoever. 

(The first command gave a lot of output, seemingly about top-level items in my Dropbox.)

**Comment by samschott** [comment]
> The first command gave a lot of output, seemingly about top-level items in my Dropbox.

Yes, it successfully lists the top level items together with some metadata.

> `m.client.list_folder("/", recursive=True)` just hung there, and gave no response whatsoever.

For how log did you wait? Could you try the following command instead?

```Python
m.client.dbx.files_list_folder("/", recursive=True)
```

This lists at most ~ 500 items and therefore returns earlier for a large Dropbox folder. If this returns successfully, please try the initial command again until it either raises a timeout error, completes successfully, or raises any other type of error. It may take a few minutes to complete since it attempts to list the entire contents of your Dropbox folder.

**Comment by tjluoma** [comment]
I guess we're at the mercy of Dropbox, inc. who shows no interest in helping a 3rd-party developer. I've given up and gone back to the official app, which is still terrible, in case anyone wondered. (Now it wants me to backup external hard drives? Are they serious?!)

**Comment by samschott** [comment]
I'm afraid so 😔 I've tried to follow up with them multiple times but they have their own priorities, which is understandable.

**Comment by dmusican** [comment]
I'm also having this problem, which just started today, though I've been having slower and slower performance through Maestral over the last few days. I enabled debug, and the log is showing that I'm stuck in this infinite loop:

```
2023-04-15 09:05:45 dropbox_client DEBUG: Request to files/get_metadata
2023-04-15 09:05:45 dropbox_client DEBUG: Request to files/get_metadata
2023-04-15 09:05:45 dropbox_client DEBUG: Request to files/get_metadata
2023-04-15 09:05:46 dropbox_client DEBUG: Request to files/get_metadata
2023-04-15 09:05:46 dropbox_client DEBUG: Request to files/get_metadata
```

**Comment by dmusican** [comment]
Ignore the above, I guess? It finally kicked in and everything synced, but U had a good hour this morning where nothing was working. Maybe something was wacky on the Dropbox side.

**Comment by XiaoHippo** [comment]
I've also been having this issue for the past few months:
```
2025-04-03 11:28:21 sync INFO: Indexing remote Dropbox
2025-04-03 11:28:21 dropbox_client DEBUG: Request to files/list_folder
2025-04-03 11:29:51 dropbox_client DEBUG: HttpError status_code=504: Retrying in 0.2 seconds
2025-04-03 11:29:51 dropbox_client DEBUG: Request to files/list_folder
2025-04-03 11:31:21 dropbox_client DEBUG: HttpError status_code=504: Retrying in 2.3 seconds
2025-04-03 11:31:23 dropbox_client DEBUG: Request to files/list_folder
2025-04-03 11:32:53 dropbox_client DEBUG: HttpError status_code=504: Retrying in 3.2 seconds
```
This totally stops Maestral from completing the setup process.

**Comment by andrewxhonson** [comment]
Just for some information, I am seeing the same thing as XiaoHippo.

It looks like the previous dropbox_client requests were successful, it's just the `Request to files/list_folder` that's having trouble, getting `HttpError status_code=504`. That should mean there's an issue on Dropbox's end, but [Dropbox Status](https://status.dropbox.com/) shows All Systems Operational. Since XiaoHippo saw this five months ago (I'm just installing now for the first time, using the MacOS package), there may be some issue there other than their systems just being down.

```
2025-09-20 00:02:19 dropbox_client DEBUG: Refreshing access token.
2025-09-20 00:02:19 dropbox_client DEBUG: Request to users/get_space_usage
2025-09-20 00:02:19 manager DEBUG: Checking path root...
2025-09-20 00:02:19 dropbox_client DEBUG: Request to users/get_current_account
2025-09-20 00:02:21 manager DEBUG: Path root is up to date
2025-09-20 00:02:21 sync INFO: Indexing remote Dropbox
2025-09-20 00:02:21 dropbox_client DEBUG: Refreshing access token.
2025-09-20 00:02:21 dropbox_client DEBUG: Request to files/list_folder
2025-09-20 00:03:51 dropbox_client DEBUG: HttpError status_code=504: Retrying in 0.2 seconds
2025-09-20 00:03:51 dropbox_client DEBUG: Request to files/list_folder
2025-09-20 00:05:21 dropbox_client DEBUG: HttpError status_code=504: Retrying in 0.6 seconds
2025-09-20 00:05:22 dropbox_client DEBUG: Request to files/list_folder
2025-09-20 00:06:52 dropbox_client DEBUG: HttpError status_code=504: Retrying in 4.3 seconds
2025-09-20 00:06:57 dropbox_client DEBUG: Request to files/list_folder
2025-09-20 00:08:27 dropbox_client DEBUG: HttpError status_code=504: Retrying in 15.6 seconds
2025-09-20 00:08:42 dropbox_client DEBUG: Request to files/list_folder
2025-09-20 00:10:12 manager DEBUG: Connection error
Traceback (most recent call last):
  File "app_packages/maestral/errorhandling.py", line 90, in convert_api_errors
  File "app_packages/maestral/client.py", line 1423, in list_folder_iterator
  File "app_packages/dropbox/base.py", line 2149, in files_list_folder
  File "app_packages/dropbox/dropbox_client.py", line 326, in request
  File "app_packages/dropbox/dropbox_client.py", line 476, in request_json_string_with_retry
  File "app_packages/maestral/client.py", line 165, in request_json_string
  File "app_packages/dropbox/dropbox_client.py", line 595, in request_json_string
  File "app_packages/dropbox/dropbox_client.py", line 620, in raise_dropbox_error_for_resp
dropbox.exceptions.InternalServerError: InternalServerError('fff1b2d1c62e4425a77d809a68ce36da', 504, '<!DOCTYPE html>\n<html>\n<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1" />\n<title>Dropbox - 504</title>\n<link href="https://cfl.dropboxstatic.com/static/metaserver/static/css/error.css" rel="stylesheet" type="text/css"/>\n<link rel="shortcut icon" href="https://cfl.dropboxstatic.com/static/images/favicon.ico"/>\n</head>\n<body>\n<div class="figure">\n<img src="https://assets.dropbox.com/www/en-us/illustrations/spot/target-miss.svg" alt="Error: 504"/>\n</div>\n<div id="errorbox">\n<h1>Error (504)</h1>Something went wrong. Don\'t worry, your files are still safe and the Dropbox team has been notified. Check out our <a href="https://status.dropbox.com">Status Page</a> to see if there is a known incident, our <a href="https://www.dropbox.com/help">Help Center</a> and <a href="https://forums.dropbox.com">forums</a> for help, or head back to <a href="https://www.dropbox.com/home">home</a>.\n</div>\n\n</body>\n</html>\n')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app_packages/maestral/manager.py", line 767, in _handle_sync_thread_errors
  File "app_packages/maestral/manager.py", line 746, in startup_worker
  File "app_packages/maestral/sync.py", line 2926, in download_sync_cycle
  File "app_packages/maestral/sync.py", line 2979, in list_remote_changes_iterator
  File "app_packages/maestral/client.py", line 1420, in list_folder_iterator
  File "support/python-stdlib/contextlib.py", line 155, in __exit__
  File "app_packages/maestral/errorhandling.py", line 92, in convert_api_errors
maestral.exceptions.DropboxServerError: Dropbox server error. Something went wrong on Dropbox’s end. Please check on status.dropbox.com if their services are up and running and try again later.
2025-09-20 00:10:12 manager INFO: Connection lost
2025-09-20 00:10:12 manager INFO: Shutting down threads...
2025-09-20 00:10:12 sync INFO: Sync aborted
2025-09-20 00:10:12 manager INFO: Paused
2025-09-20 00:10:12 manager INFO: Connecting...
2025-09-20 00:10:14 sync DEBUG: Could not load mignore rules: No such file or directory
2025-09-20 00:10:14 dropbox_client DEBUG: Request to users/get_space_usage
2025-09-20 00:10:14 manager DEBUG: Checking path root...
2025-09-20 00:10:14 dropbox_client DEBUG: Request to users/get_current_account
2025-09-20 00:10:15 manager DEBUG: Path root is up to date
2025-09-20 00:10:15 sync INFO: Indexing remote Dropbox
2025-09-20 00:10:15 dropbox_client DEBUG: Request to files/list_folder
2025-09-20 00:11:46 dropbox_client DEBUG: HttpError status_code=504: Retrying in 0.1 seconds
2025-09-20 00:11:46 dropbox_client DEBUG: Request to files/list_folder
```

**Comment by andrewxhonson** [comment]
FYI @samschott, here was Dropbox's response on the support request I raised for that issue.

> If I understand this correctly, you are seeing sync errors in the Maestral app  
> Dropbox has an open API - which means that anyone can create custom third-party solutions that integrate with Dropbox accounts and the Maestral app is one of these solutions as you stated correctly. If the Dropbox app is syncing as normal, however, on your device, then the problem you’re experiencing appears to be caused by Maestral and not by Dropbox. We’re unable to provide support for third-party apps or services.
> The best way for you to get assistance with the problem is to reach out to the company that created Maestral. They'll be a better resource for you to review this in more depth.
> If ultimately the developer of this integration suspects this may be an issue on Dropbox's end, please request that they reach out to our developer support here: 
> http://www.dropbox.com/developer
> This way, our team can better understand the specifics of the third-party app, analyze the requests made to Dropbox, and review the feedback the third-party app is receiving.
