### ISSUE TITLE
Error reading files when path contains a `*` character (?)

### ISSUE THREAD

**Issue by madrobby** [SamSchott/maestral#496]
**Describe the bug**
Can't read files when path contains a `*` character (?)
_Note: I don't know if that causes the problem, but it's the only unusual thing I could spot._

```
OSError: [Errno 5] Input/output error: '/Users/thomasfuchs/Dropbox (Slash7)/JFS - Materials/* Cheat Sheet/Fonts/Rush I_Hadcrafted_Pattern_Collection by Miglena Spasova/Rush I_Hadcrafted_Pattern_Collection_Pattern.eps'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/sync.py", line 3333, in _create_local_entry
  File "Contents/Resources/app_packages/maestral/sync.py", line 3406, in _on_remote_file
  File "Contents/Resources/app_packages/maestral/sync.py", line 3130, in _check_download_conflict
  File "Contents/Resources/app_packages/maestral/sync.py", line 842, in get_local_hash
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/contextlib.py", line 135, in __exit__
  File "Contents/Resources/app_packages/maestral/client.py", line 143, in convert_api_errors
maestral.errors.FileReadError: Could not sync file or folder. Could not access file. Errno 5: Input/output error.
```

**To Reproduce**
Add a `*` to path names (maybe). Note the folder was previously synced by the official Dropbox client, maybe they messed something up?

**Expected behaviour**
No error, duh.

**System:**
 - Maestral version: 1.5.1
 - Python version: 5.15.4
 - OS: macOS Monterey 12.0.1 (21A559) on Intel

**Comment by madrobby** [comment]
I think this was a false alert, issues are most likely caused by the behavior I described in #497.
