### ISSUE TITLE
OSError: [Errno 63] File name too long

### ISSUE THREAD

**Issue by asmeurer** [SamSchott/maestral#506]
**Describe the bug**

I'm trying to sync maestral with an existing Dropbox account and existing Dropbox folder on my Mac. After day or so I get the "an unexpected error occured" popup with the following

```
Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
File "Contents/Resources/app_packages/maestral/manager.py", line 773, in startup_worker
File "Contents/Resources/app_packages/maestral/sync.py", line 2841, in download_sync_cycle
File "Contents/Resources/app_packages/maestral/sync.py", line 2998, in apply_remote_changes
File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 445, in result
File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
File "Contents/Resources/Support/Python/Resources/lib/python3.9/concurrent/futures/thread.py", line 52, in run
File "Contents/Resources/app_packages/maestral/sync.py", line 3335, in _create_local_entry
File "Contents/Resources/app_packages/maestral/sync.py", line 3512, in _on_remote_folder
File "Contents/Resources/app_packages/maestral/sync.py", line 936, in update_index_from_sync_event
File "Contents/Resources/app_packages/maestral/sync.py", line 3236, in _get_ctime
File "Contents/Resources/app_packages/maestral/sync.py", line 3236, in _get_ctime
File "Contents/Resources/app_packages/maestral/sync.py", line 3236, in _get_ctime
[Previous line repeated 122 more times]
File "Contents/Resources/app_packages/maestral/sync.py", line 3238, in _get_ctime
OSError: [Errno 63] File name too long: '<path>'
```

I've replaced the actual path with `<path>` The path is a highly nested set of folders and the full path length is 1034 characters. I tried deleting the folder from my local Dropbox and it still gives the error.

**To Reproduce**

**Expected behaviour**

**System:**

 - Maestral version: 1.5.1
 - Python version: 
 - OS: [e.g. Ubuntu] macOS 11.6.1
 - Desktop environment: [e.g. Gnome 3.32]
 - PyQt version (for Linux GUI):

**Additional context**

**Comment by SamSchott** [comment]
Thanks for the report! To my knowledge, macOS 11 with APFS only supports file names of up to 255 characters and file paths of up to 1024 characters. Though this may be different on M1 macs. You therefore won't be able to sync that specific file / path.

However, the error should be handled as an individual sync issue with a more informative text instead of an unexpected error which stops all other sync jobs.

**Comment by asmeurer** [comment]
OK, I didn't look closely enough. The problem is that this is a cyclical symlink (a directory containing a directory containing a symlink to the first directory). I know Dropbox used to support symlinks but it doesn't any more. Does maestral support them? If so, it needs to handle this case. 

By the way this is on an Intel Mac (2019 MacBook Pro).

**Comment by asmeurer** [comment]
Oh I didn't know that. That's actually nice that Maestral supports that feature still. But I understand if you want to get rid of it, probably for the same reasons Dropbox did. Although I'm guessing this would make some Maestral users unhappy. 

Even so, I think this particular instance is something that I had in an old symlinked folder from back when Dropbox did support this, so I suspect even Dropbox was handling cyclic links correctly at that point.
