### ISSUE TITLE
Unable to launch the gui

### ISSUE THREAD

**Issue by ddund** [samschott/maestral#509]
**Describe the bug**
On a fresh Fedora 35 install I'm unable to launch the Maestral gui.

**To Reproduce**
Install Fedora 35.
Install maestral with `python3 -m pip install --upgrade maestral[gui]`
Run `maestral gui` in the terminal

**Expected behaviour**

**System:**

 - Maestral version: 1.5.1
 - Python version: 3.10.0
 - OS: Fedora 35
 - Desktop environment: Gnome 41
 - PyQt version (for Linux GUI): 5.15.6

**Additional context**
```
$ maestral gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/username/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/maestral/cli.py", line 711, in gui
    run(config_name)
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/main.py", line 631, in run
    maestral_gui.load_maestral()
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/main.py", line 192, in load_maestral
    self.loading_done = SetupDialog.configureMaestral(self.mdbx)
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/setup_dialog.py", line 384, in configureMaestral
    fsd = SetupDialog(mdbx, parent)
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/setup_dialog.py", line 81, in __init__
    b.setMinimumWidth(width)
TypeError: setMinimumWidth(self, int): argument 1 has unexpected type 'float'
```

**Comment by SamSchott** [comment]
Thanks for the report! I believe this is due to a change in Python 3.10. From their release notes:

> Builtin and extension functions that take integer arguments no longer accept Decimals, Fractions and other objects that can be converted to integers only with a loss

If you fancy submitting a PR against https://github.com/samschott/maestral-qt, this should be an easy fix.

**Comment by ddund** [comment]
Oh, sorry! Didn't even realize that I opened a issue in the wrong repo. Ill open a new issue in the correct.

**Comment by SamSchott** [comment]
Reopening this to prevent duplicate issues. Many users will look in this repo first.

**Comment by The-Big-V** [comment]
I'm also getting GUI crash on macOS (with python 3.10). Is it likely to be the same problem/same fix, or should I open a new issue?

**Comment by samschott** [comment]
Closing since this has been fixed some time ago.
