### ISSUE TITLE
Maestral GUI fails to run on Fedora 35/Gnome 41 - returns this error:

### ISSUE THREAD

**Issue by RistrettoMike** [SamSchott/maestral#510]
On a fresh install of Fedora 35/Gnome 41, installing maestral with the gui tag and then running "maestral gui" returns this error:

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/home/ristretto/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/ristretto/.local/lib/python3.10/site-packages/maestral/cli.py", line 711, in gui
    run(config_name)
  File "/home/ristretto/.local/lib/python3.10/site-packages/maestral_qt/main.py", line 631, in run
    maestral_gui.load_maestral()
  File "/home/ristretto/.local/lib/python3.10/site-packages/maestral_qt/main.py", line 192, in load_maestral
    self.loading_done = SetupDialog.configureMaestral(self.mdbx)
  File "/home/ristretto/.local/lib/python3.10/site-packages/maestral_qt/setup_dialog.py", line 384, in configureMaestral
    fsd = SetupDialog(mdbx, parent)
  File "/home/ristretto/.local/lib/python3.10/site-packages/maestral_qt/setup_dialog.py", line 81, in __init__
    b.setMinimumWidth(width)
TypeError: setMinimumWidth(self, int): argument 1 has unexpected type 'float'

Not sure where to go from there, hope this is helpful getting it working again on Fedora!
~M

**Comment by SamSchott** [comment]
Thanks for the report! This is due to a change in how Python 3.10 passes on floats to extension modules. The issue was already reported in #509 and is currently being tracked with the GUI at https://github.com/SamSchott/maestral-qt/issues/18.
