### ISSUE TITLE
OSError: [Errno 41] Protocol wrong type for socket

### ISSUE THREAD

**Issue by jmfd** [SamSchott/maestral#549]
Whenever my computer (M1 Pro MBP 14" running macOS 12.0.1 as well as 12.1) restarts, Maestral gets this exception:

```
Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
File "Contents/Resources/app_packages/maestral/manager.py", line 619, in download_worker
File "Contents/Resources/app_packages/maestral/client.py", line 375, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 369, in close
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 701, in close
File "Contents/Resources/app_packages/requests/sessions.py", line 747, in close
File "Contents/Resources/app_packages/requests/adapters.py", line 325, in close
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 222, in clear
File "Contents/Resources/app_packages/urllib3/_collections.py", line 100, in clear
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 173, in 
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 492, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 954, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 502, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1332, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 496, in _real_close
OSError: [Errno 41] Protocol wrong type for socket
```

This always happens on restart.  Sometimes it happens randomly while using my computer too.  The errors/backtrace can be longer; attached that one:

[maestral-backtrace.txt](https://github.com/SamSchott/maestral/files/7688058/maestral-backtrace.txt)

I have a suspicion it may be related to my adblocker, [AdGuard](https://adguard.com/). This also gets launched on startup, and I feel like there might be a correlation between the intermittent failures and myself manually disabling/re-enabling the blocker.  I've done some tests and can trigger it mostly consistently, but not at the exact time I re-enable the ad blocker.

**Comment by Lionjin** [comment]
Same issue at restart here : MacPro7,1 Big Sur 11.6.2

Traceback (most recent call last):
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 699, in urlopen
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 394, in _make_request
File "Contents/Resources/app_packages/urllib3/connection.py", line 239, in request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1276, in request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1322, in _send_request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1271, in endheaders
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1031, in _send_output
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 992, in send
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1236, in sendall
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 755, in urlopen
File "Contents/Resources/app_packages/urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /2/users/get_current_account (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2384)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/requests/adapters.py", line 439, in send
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 769, in urlopen
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 954, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 502, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1332, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 496, in _real_close
OSError: [Errno 41] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/client.py", line 127, in convert_api_errors
File "Contents/Resources/app_packages/maestral/client.py", line 489, in get_account_info
File "Contents/Resources/app_packages/dropbox/base.py", line 5293, in users_get_current_account
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 323, in request
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 479, in request_json_string_with_retry
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 592, in request_json_string
File "Contents/Resources/app_packages/requests/sessions.py", line 590, in post
File "Contents/Resources/app_packages/requests/sessions.py", line 542, in request
File "Contents/Resources/app_packages/requests/sessions.py", line 655, in send
File "Contents/Resources/app_packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: [Errno 41] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 627, in download_worker
File "Contents/Resources/app_packages/maestral/manager.py", line 376, in check_and_update_path_root
File "Contents/Resources/app_packages/maestral/manager.py", line 403, in _needs_path_root_update
File "Contents/Resources/app_packages/maestral/client.py", line 485, in get_account_info
File "Contents/Resources/Support/Python/Resources/lib/python3.10/contextlib.py", line 153, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 132, in convert_api_errors
maestral.errors.DropboxConnectionError: Cannot connect to Dropbox. Please check you internet connection and try again later.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
File "Contents/Resources/app_packages/maestral/manager.py", line 619, in download_worker
File "Contents/Resources/app_packages/maestral/client.py", line 375, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 369, in close
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 701, in close
File "Contents/Resources/app_packages/requests/sessions.py", line 747, in close
File "Contents/Resources/app_packages/requests/adapters.py", line 325, in close
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 222, in clear
File "Contents/Resources/app_packages/urllib3/_collections.py", line 100, in clear
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 173, in 
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 492, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 954, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 502, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1332, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 496, in _real_close
OSError: [Errno 41] Protocol wrong type for socket
