### ISSUE TITLE
Frequent sync errors on Mac OS Monterey

### ISSUE THREAD

**Issue by timocock** [samschott/maestral#555]
**Describe the bug**
Following error received when trying to sync:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
File "Contents/Resources/app_packages/maestral/manager.py", line 715, in upload_worker
File "Contents/Resources/app_packages/maestral/sync.py", line 1752, in upload_sync_cycle
File "Contents/Resources/app_packages/maestral/sync.py", line 1788, in list_local_changes
File "Contents/Resources/app_packages/maestral/sync.py", line 1996, in _clean_local_events
File "Contents/Resources/app_packages/maestral/sync.py", line 3695, in rescan
File "Contents/Resources/app_packages/maestral/sync.py", line 1274, in to_dbx_path_lower
File "Contents/Resources/app_packages/maestral/sync.py", line 1261, in to_dbx_path
ValueError: "</path/to>/Dropbox/.maestral.cache/tmpjbo0cg_h" is not in "</path/to>/DropBox"

(path changed for

Using latest 1.5.2 on Monterey on a 2021 MBP M1Pro

**System:**

 - Maestral version: 1.5.2
 - Python version: Monterey
 - OS: [e.g. Ubuntu] Monterey
 - Desktop environment: [e.g. Gnome 3.32]
 - PyQt version (for Linux GUI):

**Additional context**

**Comment by samschott** [comment]
Strange, it seems that Maestral has your local Dropbox path saved with the casing `DropBox` while the actual file changes report a folder name `Dropbox`. Could you check the following?

1. How does the actual folder appear in Finder?
2. If you have the CLI installed, what is the return value of `maestral config get path`?

The easiest fix will probably be to move the local Dropbox folder to a new location, for example `~/Dropbox_tmp`, with the CLI command `maestral move-dir` and to move it back again. This should ensure that actual path corresponds to the configured path.

MacOS is a bit strange when it comes to casing in file names: Unlike Linux, it typically does not discriminate between upper and lower case in file names (try creating two folders with names that only differ in casing...). However, some API will still be case-sensitive since it preserves the user's casing for display purposes.

**Comment by oecin** [comment]
Traceback (most recent call last):
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 699, in urlopen
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 394, in _make_request
File "Contents/Resources/app_packages/urllib3/connection.py", line 239, in request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1276, in request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1322, in _send_request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1271, in endheaders
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1031, in _send_output
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 992, in send
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1236, in sendall
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 755, in urlopen
File "Contents/Resources/app_packages/urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /2/users/get_current_account (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2384)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/requests/adapters.py", line 439, in send
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 769, in urlopen
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 954, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 502, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1332, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 496, in _real_close
OSError: [Errno 41] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/client.py", line 127, in convert_api_errors
File "Contents/Resources/app_packages/maestral/client.py", line 489, in get_account_info
File "Contents/Resources/app_packages/dropbox/base.py", line 5293, in users_get_current_account
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 323, in request
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 479, in request_json_string_with_retry
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 592, in request_json_string
File "Contents/Resources/app_packages/requests/sessions.py", line 590, in post
File "Contents/Resources/app_packages/requests/sessions.py", line 542, in request
File "Contents/Resources/app_packages/requests/sessions.py", line 655, in send
File "Contents/Resources/app_packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: [Errno 41] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 627, in download_worker
File "Contents/Resources/app_packages/maestral/manager.py", line 376, in check_and_update_path_root
File "Contents/Resources/app_packages/maestral/manager.py", line 403, in _needs_path_root_update
File "Contents/Resources/app_packages/maestral/client.py", line 485, in get_account_info
File "Contents/Resources/Support/Python/Resources/lib/python3.10/contextlib.py", line 153, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 132, in convert_api_errors
maestral.errors.DropboxConnectionError: Cannot connect to Dropbox. Please check you internet connection and try again later.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
File "Contents/Resources/app_packages/maestral/manager.py", line 619, in download_worker
File "Contents/Resources/app_packages/maestral/client.py", line 375, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 369, in close
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 701, in close
File "Contents/Resources/app_packages/requests/sessions.py", line 747, in close
File "Contents/Resources/app_packages/requests/adapters.py", line 325, in close
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 222, in clear
File "Contents/Resources/app_packages/urllib3/_collections.py", line 100, in clear
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 173, in 
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 492, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 954, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 502, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1332, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 496, in _real_close
OSError: [Errno 41] Protocol wrong type for socket
Traceback (most recent call last):
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 699, in urlopen
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 394, in _make_request
File "Contents/Resources/app_packages/urllib3/connection.py", line 239, in request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1276, in request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1322, in _send_request
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1271, in endheaders
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 1031, in _send_output
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 992, in send
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1236, in sendall
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 755, in urlopen
File "Contents/Resources/app_packages/urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /2/users/get_current_account (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2384)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/requests/adapters.py", line 439, in send
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 769, in urlopen
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 954, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 502, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1332, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 496, in _real_close
OSError: [Errno 41] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/client.py", line 127, in convert_api_errors
File "Contents/Resources/app_packages/maestral/client.py", line 489, in get_account_info
File "Contents/Resources/app_packages/dropbox/base.py", line 5293, in users_get_current_account
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 323, in request
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 479, in request_json_string_with_retry
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 592, in request_json_string
File "Contents/Resources/app_packages/requests/sessions.py", line 590, in post
File "Contents/Resources/app_packages/requests/sessions.py", line 542, in request
File "Contents/Resources/app_packages/requests/sessions.py", line 655, in send
File "Contents/Resources/app_packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: [Errno 41] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 627, in download_worker
File "Contents/Resources/app_packages/maestral/manager.py", line 376, in check_and_update_path_root
File "Contents/Resources/app_packages/maestral/manager.py", line 403, in _needs_path_root_update
File "Contents/Resources/app_packages/maestral/client.py", line 485, in get_account_info
File "Contents/Resources/Support/Python/Resources/lib/python3.10/contextlib.py", line 153, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 132, in convert_api_errors
maestral.errors.DropboxConnectionError: Cannot connect to Dropbox. Please check you internet connection and try again later.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
File "Contents/Resources/app_packages/maestral/manager.py", line 619, in download_worker
File "Contents/Resources/app_packages/maestral/client.py", line 375, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 369, in close
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 701, in close
File "Contents/Resources/app_packages/requests/sessions.py", line 747, in close
File "Contents/Resources/app_packages/requests/adapters.py", line 325, in close
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 222, in clear
File "Contents/Resources/app_packages/urllib3/_collections.py", line 100, in clear
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 173, in 
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 492, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/http/client.py", line 954, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 502, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/ssl.py", line 1332, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.10/socket.py", line 496, in _real_close
OSError: [Errno 41] Protocol wrong type for socket

but some app need  local Dropbox folder  to sync

**Comment by timocock** [comment]
Well, it's still a bug since it's using case insensitive filesystem. So, somewhere there's some buggy code that assumes case sensitivity.

**Comment by samschott** [comment]
@timocock, indeed, this is a bug. Answering the above questions will help to find out how and where it occured.

**Comment by timocock** [comment]
I had renamed the folder Dropbox from DropBox after configuring it. Changing it back has made the errors go away. I suppose at some point I'll just uninstall/reinstall it and change the folder name in between just because my OCD doesn't like the capital B. I don't have the command line installed sorry.

**Comment by samschott** [comment]
> I had renamed the folder Dropbox from DropBox after configuring it.

Ah, ok. This is a corner case which I had not considered. Typically, manually renaming the Dropbox folder will result in an error dialog, prompting the user to specify the new location. However, when changing just the casing, the location has not actually changed as far as macOS is concerned. This should definitely be handled better.

If you don't like to fiddle with command line tools, you could also do the following:

1. Stop Maestral.
2. Rename the Dropbox folder back to "Dropbox".
3. Open the config file at `~/Library/Application Support/maestral/maestral.ini` in TextEdit. You will see multiple configuration options are their values. Set the `path` value to the new local path with a lowercase B.

**Comment by timocock** [comment]
OK but surely whichever 'obtain folder handle' method you use should be case insensitive? The error occurs because some parts of the code CAN handle the change to case, and other parts CAN'T

**Comment by samschott** [comment]
Yes, exactly that was the problem. Some parts of Maestral are indeed case-sensitive, even if the the file system is not, because we want to be case-preserving. Even though two paths with different casing on macOS will point to the same location, they will still appear differently in Finder.

The name change was not detected, because the code checking for the local Dropbox folder was not case-sensitive on macOS. However, other parts of Maestral did require a correctly cased path.

This has been fixed now, the next update will handle case changes properly.
