### ISSUE TITLE
Pyro5.errors.SerializeError: unsupported serialized class: jeepney.wrappers.DBusErrorResponse

### ISSUE THREAD

**Issue by ceamac** [samschott/maestral#558]
**Describe the bug**

`maestral start` hangs for a while, then produces this stack trace
```
Starting Maestral...        [OK]
Traceback (most recent call last):
  File "/home/viorel/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/viorel/.local/lib/python3.9/site-packages/maestral/cli.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "/home/viorel/.local/lib/python3.9/site-packages/maestral/cli.py", line 655, in start
    startup_dialog()
  File "/home/viorel/.local/lib/python3.9/site-packages/maestral/cli.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "/home/viorel/.local/lib/python3.9/site-packages/maestral/cli.py", line 589, in startup_dialog
    if m.pending_link:
  File "/home/viorel/.local/lib/python3.9/site-packages/maestral/daemon.py", line 676, in __getattr__
    return self._m.__getattr__(item)
  File "/home/viorel/.local/lib/python3.9/site-packages/Pyro5/client.py", line 94, in __getattr__
    return self._pyroInvoke("__getattr__", (name,), None)
  File "/home/viorel/.local/lib/python3.9/site-packages/Pyro5/client.py", line 236, in _pyroInvoke
    data = serializer.loads(msg.data)
  File "/home/viorel/.local/lib/python3.9/site-packages/Pyro5/serializers.py", line 288, in loads
    return self.recreate_classes(serpent.loads(data))
  File "/home/viorel/.local/lib/python3.9/site-packages/Pyro5/serializers.py", line 254, in recreate_classes
    return self.dict_to_class(literal)
  File "/home/viorel/.local/lib/python3.9/site-packages/Pyro5/serializers.py", line 307, in dict_to_class
    return super(SerpentSerializer, cls).dict_to_class(data)
  File "/home/viorel/.local/lib/python3.9/site-packages/Pyro5/serializers.py", line 233, in dict_to_class
    raise errors.SerializeError("unsupported serialized class: " + classname)
Pyro5.errors.SerializeError: unsupported serialized class: jeepney.wrappers.DBusErrorResponse
```

**To Reproduce**

Simply start the daemon

**Expected behaviour**

**System:**

 - Maestral version: 1.5.2
 - Python version: 3.9.9
 - OS: Gentoo
 - Desktop environment: tried in Gnome 40.0 and XFCE 4.16
 - PyQt version (for Linux GUI): no gui

**Additional context**

The daemon is running, but cannot do anything (same stack trace for `maestral ls`, for example.

```
$ maestral status

Account:      *** (Basic)
Usage:        --
Status:       Paused
Sync errors:  0
```

Normally `maestral stop` stops the daemon, but if I try a command and then stop it with Ctrl-C, the daemon goes to 100% CPU and has to be killed.

**Comment by ceamac** [comment]
DBus was unable to start gnome-keyring secrets service.  Fixing that made the problem go away.

And I see the keyring can be changed form the ini file anyway.

**Comment by samschott** [comment]
@ceamac, glad you found the reason!

I know its been a while but you still have the original traceback? It should be shown in the logs which can be accessed with `maestral logs show -e`. The traceback which you have posted may appear confusing because the original error as thrown by the daemon is not properly transferred to the CLI. It would be good to see where exactly the `jeepney.wrappers.DBusErrorResponse` error is raised to handle it a bit more elegantly and print a more useful message.

**Comment by ceamac** [comment]
The log is not that old, but I can reproduce it again by recompiling gnome-keyring-daemon.

The log doesn't show anything useful
```
2022-01-03 12:58:21 daemon INFO: Starting daemon
2022-01-03 12:58:21 manager INFO: Connected
2022-01-03 12:58:25 sync INFO: Sync aborted
2022-01-03 12:58:25 manager INFO: Paused
2022-01-03 13:00:59 daemon INFO: Starting daemon
2022-01-03 13:00:59 manager INFO: Connected
```

I don't know how to obtain the original stack trace, but I suppose it is very similar to this:
```
$ keyring set user pass
Password for 'pass' in 'user': 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/keyring", line 33, in <module>
    sys.exit(load_entry_point('keyring==23.4.0', 'console_scripts', 'keyring')())
  File "/usr/lib/python3.9/site-packages/keyring/cli.py", line 132, in main
    return cli.run(argv)
  File "/usr/lib/python3.9/site-packages/keyring/cli.py", line 68, in run
    return method()
  File "/usr/lib/python3.9/site-packages/keyring/cli.py", line 85, in do_set
    set_password(self.service, self.username, password)
  File "/usr/lib/python3.9/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/usr/lib/python3.9/site-packages/keyring/backends/chainer.py", line 58, in set_password
    return keyring.set_password(service, username, password)
  File "/usr/lib/python3.9/site-packages/keyring/backends/SecretService.py", line 87, in set_password
    collection = self.get_preferred_collection()
  File "/usr/lib/python3.9/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/usr/lib/python3.9/site-packages/secretstorage/collection.py", line 161, in get_default_collection
    return Collection(connection)
  File "/usr/lib/python3.9/site-packages/secretstorage/collection.py", line 44, in __init__
    self._collection.get_property('Label')
  File "/usr/lib/python3.9/site-packages/secretstorage/util.py", line 64, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/usr/lib/python3.9/site-packages/secretstorage/util.py", line 46, in send_and_get_reply
    return self._connection.send_and_get_reply(msg, unwrap=True)
  File "/usr/lib/python3.9/site-packages/jeepney/io/blocking.py", line 190, in send_and_get_reply
    return unwrap_msg(msg_in)
  File "/usr/lib/python3.9/site-packages/jeepney/wrappers.py", line 214, in unwrap_msg
    raise DBusErrorResponse(msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.TimedOut] ("Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)",)
```

This is the point where it throws the exception
```
$ maestral start
Starting Maestral...        [OK]
- Linking new account for 'maestral' config
- Retrieving auth code from Dropbox
? How would you like to you link your account? Print auth URL to console
- Open the URL below to retrieve an auth code:
- ***
? Enter the auth code: ***
Traceback (most recent call last):
```

And this is the contents of maestral.ini:
```
[auth]
account_id = dbid:***
keyring = keyring.backends.SecretService.Keyring

[app]
notification_level = 15
log_level = 20
update_notification_interval = 604800

[sync]
path = 
excluded_items = []
reindex_interval = 1209600
max_cpu_percent = 20.0
keep_history = 604800
upload = True
download = True

[main]
version = 16.0.0
```

Not sure this helps too much.

**Comment by samschott** [comment]
Thanks, that's very helpful!
