### ISSUE TITLE
503 error crashes 

### ISSUE THREAD

**Issue by ajdunlap** [samschott/maestral#596]
**Describe the bug**
Maestral created an "An unexpected error occurred" dialog with the following text:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/maestral/client.py", line 125, in convert_api_errors
    yield
  File "/usr/lib/python3.10/site-packages/maestral/client.py", line 1117, in wait_for_remote_changes
    res = self.dbx.files_list_folder_longpoll(last_cursor, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/dropbox/base.py", line 2083, in files_list_folder_longpoll
    r = self.request(
  File "/usr/lib/python3.10/site-packages/dropbox/dropbox_client.py", line 301, in request
    self.check_and_refresh_access_token()
  File "/usr/lib/python3.10/site-packages/dropbox/dropbox_client.py", line 369, in check_and_refresh_access_token
    self.refresh_access_token(scope=self._scope)
  File "/usr/lib/python3.10/site-packages/dropbox/dropbox_client.py", line 409, in refresh_access_token
    res.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://api.dropboxapi.com/oauth2/token

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/maestral/manager.py", line 806, in _handle_sync_thread_errors
    yield
  File "/usr/lib/python3.10/site-packages/maestral/manager.py", line 632, in download_worker
    has_changes = self.sync.wait_for_remote_changes(
  File "/usr/lib/python3.10/site-packages/maestral/sync.py", line 2946, in wait_for_remote_changes
    has_changes = client.wait_for_remote_changes(last_cursor, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/maestral/client.py", line 1116, in wait_for_remote_changes
    with convert_api_errors():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/maestral/client.py", line 142, in convert_api_errors
    raise os_to_maestral_error(exc, dbx_path, local_path)
maestral.errors.MaestralApiError: Could not sync file or folder. 503 Server Error: Service Unavailable for url: https://api.dropboxapi.com/oauth2/token
```

**To Reproduce**
Not sure.

**Expected behaviour**
Based on the 503 server error it seems like this is a problem on Dropbox's side, but Maestral should probably handle it more gracefully?

**System:**

 - Maestral version: 1.5.3
 - Python version: 3.10.1
 - OS: Manjaro
 - Desktop environment: Xfce
 - PyQt version (for Linux GUI): 5.15.6

**Additional context**

**Comment by samschott** [comment]
@ajdunlap, which version of the `dropbox` package do you have installed? Maestral v1.5.3 requires `dropbox>=11.26.0` which improves error handling when refreshing the access token.

**Comment by ajdunlap** [comment]
Ah I have 11.25.0, I guess that is the problem. Thanks!

**Comment by samschott** [comment]
Did updating the `dropbox` package resolve this? If yes, I'll close the issue.

**Comment by ajdunlap** [comment]
I have not been able to try yet because my distribution hasn't updated the python dropbox package, but I think it's fine to close the issue.
