### ISSUE TITLE
1.5.3, "Unexpected error. Please restart to continue syncing" after login

### ISSUE THREAD

**Issue by haagensen** [samschott/maestral#603]
Hello,

I'm running Maestral on ElementaryOS 6.1. After upgrading to 1.5.3 it's begun to give me messages "Unexpected error. Please restart to continue syncing" just after I log in in the machine. Today's log shows the following:

```
2022-02-09 08:29:33 daemon INFO: Starting daemon
2022-02-09 08:29:33 manager INFO: Connected
2022-02-09 08:29:41 sync INFO: Fetching remote changes
2022-02-09 08:29:42 sync INFO: Indexing local changes...
2022-02-09 08:29:42 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "/home/christian/.pyenv/versions/3.9.6/lib/python3.9/site-packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
    yield
  File "/home/christian/.pyenv/versions/3.9.6/lib/python3.9/site-packages/maestral/manager.py", line 780, in startup_worker
    self.sync.upload_local_changes_while_inactive()
  File "/home/christian/.pyenv/versions/3.9.6/lib/python3.9/site-packages/maestral/sync.py", line 1609, in upload_local_changes_while_inactive
    events, local_cursor = self._get_local_changes_while_inactive()
  File "/home/christian/.pyenv/versions/3.9.6/lib/python3.9/site-packages/maestral/sync.py", line 1660, in _get_local_changes_while_inactive
    index_entry = self.get_index_entry(dbx_path_lower)
  File "/home/christian/.pyenv/versions/3.9.6/lib/python3.9/site-packages/maestral/sync.py", line 803, in get_index_entry
    entry = self._db_manager_index.get(dbx_path_lower)
  File "/home/christian/.pyenv/versions/3.9.6/lib/python3.9/site-packages/maestral/utils/orm.py", line 467, in get
    return self.create(**row)
  File "/home/christian/.pyenv/versions/3.9.6/lib/python3.9/site-packages/maestral/utils/orm.py", line 409, in create
    col = getattr(self.model, key)
AttributeError: type object 'IndexEntry' has no attribute 'symlink_target'
2022-02-09 08:29:42 manager INFO: Shutting down threads...
2022-02-09 08:29:42 sync INFO: Sync aborted
2022-02-09 08:29:42 manager INFO: Paused
2022-02-09 08:29:57 sync INFO: Sync aborted
2022-02-09 08:29:57 manager INFO: Paused
2022-02-09 08:34:44 main INFO: Migrating database after update from pre v1.5.3
```
Things seems to get back to normal without issues after restarting (`maestral stop` and `maestral start`).

It may be useful to know my computer dual boots ElementaryOS and Windows, so my Dropbox folder is on a separated NTFS partition which I use within both OSs -- but it's mounted at boot time (/etc/fstab), so I'm not sure if it's really related to some "symlink problem".

Thanks!

**Comment by samschott** [comment]
That looks suspiciously like trying to access the database with the daemon version 1.5.2.

One change from v1.5.3 is consistent handling of symlinks. This required adding a new column "symlink_target" to the database tables storing sync events and and index entries. It appears that after that column was added in your database, when first running v1.5.3, you started v1.5.2 again (maybe from a different venv?) and it complained because it does not know how to handle the new table layout.
