### ISSUE TITLE
Maestral does not start when restarting computer

### ISSUE THREAD

**Issue by sebmos** [samschott/maestral#607]
**Describe the bug**
Whenever I (re)start my Mac, I get a dialog warning "Could not start Maestral" ("Could not start or connect to sync daemon. Please try again and contact the developer if this issue persists.")
When closing that dialog and starting Maestral manually, it it works fine. 

**To Reproduce**
Restart computer (no other steps necessary)

**Expected behaviour**
Maestral to start automatically

**System:**

 - Maestral version: 1.5.2
 - Python version: 3.9.1
 - OS: macOS 12.1
 - Desktop environment: n/a
 - PyQt version (for Linux GUI): n/a

**Additional context**
This has been going on since I started using Maestral around the time ATP.fm mentioned it a few months ago.

The error log shows only the following line:
```
Contents/Resources/app_packages/toga_cocoa/app.py:115: DeprecationWarning: There is no current event loop
```

In the Maestral settings, I enabled the "Start Maestral on login" option.

**Comment by samschott** [comment]
Otherwise, have you set the daemon to autostart indecently with `maestral autostart -Y`? If yes, this may result in a race condition during startup.

**Comment by sebmos** [comment]
Apologies for the late response! I had another crash today, after which a new version was downloaded -s o I'm not sure I was on the very latest, and whether I had the fix for #522 already - although I had downloaded the latest version at the time I raised the bug.

Regarding #522, I'm on a 4 GHz Core i7, which isn't new, but (I think) faster than a Core 2 Duo. But we'll see if the problem goes away now that I'm definitely on the latest version.

I don't think I used the CLI to enable auto-start, but it's been a while and anything is possible, so just to be safe, I ran `maestral autostart -N`. Feel free to close the issue for now, I can always re-open if I get another crash!

**Comment by sebmos** [comment]
I just had the problem again - again after a restart. I'm on version 1.6.1 at the moment. The log (`maestral log show`) showed the following:

```
2022-04-18 21:39:34 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "Contents/Resources/app_packages/Pyro5/client.py", line 278, in connect_and_handshake
  File "Contents/Resources/app_packages/Pyro5/socketutil.py", line 283, in create_socket
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/daemon.py", line 548, in start_maestral_daemon_process
  File "Contents/Resources/app_packages/maestral/daemon.py", line 360, in wait_for_startup
  File "Contents/Resources/app_packages/maestral/daemon.py", line 356, in wait_for_startup
  File "Contents/Resources/app_packages/Pyro5/client.py", line 182, in _pyroBind
  File "Contents/Resources/app_packages/Pyro5/client.py", line 342, in __pyroCreateConnection
  File "Contents/Resources/app_packages/Pyro5/client.py", line 304, in connect_and_handshake
Pyro5.errors.CommunicationError: cannot connect to /Users/sebastian/Library/Application Support/maestral/maestral.sock: [Errno 2] No such file or directory
2022-04-18 21:39:34 daemon ERROR: Daemon is running but not responsive, killing now
```

The previous line lines up with when I shut down my Mac:
```
2022-04-18 21:32:40 manager INFO: Paused
```

The next line is the daemon being started normally:
```
2022-04-18 21:41:17 daemon INFO: Starting daemon
[...]
```
