### ISSUE TITLE
Upgrade 1.5 => 1.6 Masses of dot ~ files duplicating storage usage.

### ISSUE THREAD

**Issue by hb9eue** [samschott/maestral#641]
Hi Devs

I upgraded from 1.5 to 1.6.

Immediately I got spammed by sync errors, but 'let it run' for a while to see if this would fix itself after a while.

Then I got warnings, that my Dropbox Quota was full.

So I started investigating the issue and noticed: For every file in my dropbox, a second file starting with a dot and trailed by ~ and some hex digits was created, effectively doubling the storage needed.

Why is this happeing? How can I fix this? Can I just delete all those duplicate files?

Example:

3407660   2 drwxr-xr-x  4 benoit users      8 21. Mär 09:08  .
3407453   2 drwxr-xr-x  7 benoit users      7 16. Jan 17:05  ..
3408031 330 -rw-r--r--  1 benoit users 334127 13. Dez 21:00  Archive.zip
3457705 330 -rw-r--r--  1 benoit users 334127 13. Dez 21:00  .Archive.zip.~4d81663a

-Benoît-

**Comment by samschott** [comment]
Hi Benoit, could you answer a couple of questions to debug this?

1. Which operating system are you on?
2. Is really every file affected or only many of them? How about folders?
3. What do the sync errors say?
4. Could you provide the log output? You can view the logs as described at https://maestral.app/docs/logging.

**Comment by hb9eue** [comment]
Hi Samschott

* Debian Linux 11.2
* Filesystem on NFS (that is why I don't use the original client)
* Only files affected, not directories. Not every file is duplicated that way, but I stopped syncinc after getting spammed by sync errors.

MAYBE IMPORTANT: The same directory is also synced to NextCloud which worked flawlessly with Maestral 1.5

Logs:
maestral.exceptions.InsufficientSpaceError: Could not upload file. You do not have enough space on Dropbox to move or copy the files.

Well that is after the Dropbox got full because of the duplicate files...

Searching the first error in the log. It's about this one:

```
2022-03-21 09:09:40 sync INFO: Syncing ↑ 6/11
2022-03-21 09:09:43 sync INFO: Syncing ↑ 10/11
2022-03-21 09:09:45 sync INFO: Syncing ↑ 3/104
2022-03-21 09:09:51 sync INFO: Syncing ↑ 4/104
2022-03-21 09:09:53 sync INFO: Syncing ↑ 5/104
2022-03-21 09:09:57 sync INFO: Syncing ↑ 17/104
2022-03-21 09:10:00 sync INFO: Syncing ↑ 27/104
2022-03-21 09:10:01 sync INFO: Could not sync .INTERNET.docx.~15c6cfd
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/maestral/errorhandling.py", line 94, in convert_api_errors
    yield
  File "/usr/local/lib/python3.9/dist-packages/maestral/client.py", line 894, in _upload_session_finish_helper
    md = self.dbx.files_upload_session_finish(
  File "/usr/local/lib/python3.9/dist-packages/dropbox/base.py", line 3339, in files_upload_session_finish
    r = self.request(
  File "/usr/local/lib/python3.9/dist-packages/dropbox/dropbox_client.py", line 348, in request
    raise ApiError(res.request_id,
dropbox.exceptions.ApiError: ApiError('e6065b4ee48a417d9e4992b45314a898', UploadSessionFinishError('content_hash_mismatch', None))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/maestral/sync.py", line 2205, in _create_remote_entry
    res = self._on_local_file_created(event, client)
  File "/usr/local/lib/python3.9/dist-packages/maestral/sync.py", line 2391, in _on_local_file_created
    md_new = client.upload(
  File "/usr/local/lib/python3.9/dist-packages/maestral/client.py", line 748, in upload
    res = self._upload_session_finish_helper(
  File "/usr/local/lib/python3.9/dist-packages/maestral/errorhandling.py", line 851, in wrapper
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/maestral/errorhandling.py", line 843, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/maestral/client.py", line 894, in _upload_session_finish_helper
    md = self.dbx.files_upload_session_finish(
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/maestral/errorhandling.py", line 96, in convert_api_errors
    raise dropbox_to_maestral_error(exc, dbx_path, local_path)
maestral.exceptions.DataCorruptionError: Could not upload file. Data corruption during upload. Please try again.
```

**Comment by hb9eue** [comment]
I deleted all ".*.~??????" files and restarted maestral, which also deleted the duplicate files from the Dropbox cloud, no sync errors this time.

Then I started the NextCloud sync agent and after syncing his few changes, he is also happy and not causing duplicates.

*shurg*

**Comment by hb9eue** [comment]
Sync errors are back:

```
2022-03-22 10:20:29 sync INFO: Could not sync prt-cbl-core1FILE-157.161.20.250-SW-202009111040.smattrace.tar.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/maestral/errorhandling.py", line 94, in convert_api_errors
    yield
  File "/usr/local/lib/python3.9/dist-packages/maestral/client.py", line 894, in _upload_session_finish_helper
    md = self.dbx.files_upload_session_finish(
  File "/usr/local/lib/python3.9/dist-packages/dropbox/base.py", line 3339, in files_upload_session_finish
    r = self.request(
  File "/usr/local/lib/python3.9/dist-packages/dropbox/dropbox_client.py", line 348, in request
    raise ApiError(res.request_id,
dropbox.exceptions.ApiError: ApiError('55bb5ac1ee814d57bf0454b90685a58d', UploadSessionFinishError('content_hash_mismatch', None))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/maestral/sync.py", line 2205, in _create_remote_entry
    res = self._on_local_file_created(event, client)
  File "/usr/local/lib/python3.9/dist-packages/maestral/sync.py", line 2391, in _on_local_file_created
    md_new = client.upload(
  File "/usr/local/lib/python3.9/dist-packages/maestral/client.py", line 748, in upload
    res = self._upload_session_finish_helper(
  File "/usr/local/lib/python3.9/dist-packages/maestral/errorhandling.py", line 851, in wrapper
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/maestral/errorhandling.py", line 843, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/maestral/client.py", line 894, in _upload_session_finish_helper
    md = self.dbx.files_upload_session_finish(
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/maestral/errorhandling.py", line 96, in convert_api_errors
    raise dropbox_to_maestral_error(exc, dbx_path, local_path)
maestral.exceptions.DataCorruptionError: Could not upload file. Data corruption during upload. Please try again.
2022-03-22 10:20:29 sync INFO: Could not sync prt-cbl-core1FILE-157.161.20.250-SW-202009111038.ribRouteSS.tar.gz
```

**Comment by hb9eue** [comment]
I have an idea... one of my colleagues dumped a large ammount of data in a shared Nextcloud folder which was not excluded from syncing.

I excluded that folder from syncing and since I don't see those data corruption messages anymore.

**Comment by samschott** [comment]
Interesting, it would be good to know what exactly when also syncing with NextCloud. In general, I think it is good that we are doing more robust integrity checks now.
