### ISSUE TITLE
Error when reading a team's space usage

### ISSUE THREAD

**Issue by Roy-Orbison** [samschott/maestral#643]
**Describe the bug**
Maestral fails with an "Unexpected error" toast notification as soon as I open the program.

**To Reproduce**
Open Maestral, the error occurs immediately.

**Expected behaviour**
Re-sync as usual.

**System:**
 - Maestral version: GUI & daemon both 1.6.0
 - Python version: 3.9.7
 - OS: Kubuntu 21.10
 - Desktop environment: KDE Plasma 5.22.5
 - PyQt version (for Linux GUI): 5.15.4
 - Qt version: 5.15.2

**Additional context**
Closing and reopening does not help.

Log after upgrade:
```text
2022-03-22 11:48:06 daemon INFO: Starting daemon
2022-03-22 11:48:06 main INFO: Scheduling reindex after update from pre v1.6.0
2022-03-22 11:48:08 manager INFO: Connected
2022-03-22 11:48:21 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/manager.py", line 805, in _handle_sync_thread_errors
    yield
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/manager.py", line 752, in startup_worker
    self.client.get_space_usage()
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/client.py", line 521, in get_space_usage
    return convert_space_usage(res)
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/client.py", line 1538, in convert_space_usage
    res.allocation.get_team().usage, res.allocation.get_team().allocation
AttributeError: 'TeamSpaceAllocation' object has no attribute 'usage'
2022-03-22 11:48:21 manager INFO: Shutting down threads...
2022-03-22 11:48:21 sync INFO: Sync aborted
2022-03-22 11:48:21 manager INFO: Paused
2022-03-22 11:48:31 sync INFO: Sync aborted
2022-03-22 11:48:31 manager INFO: Paused
2022-03-22 11:48:39 daemon INFO: Starting daemon
2022-03-22 11:48:39 manager INFO: Connected
2022-03-22 11:48:41 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/manager.py", line 805, in _handle_sync_thread_errors
    yield
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/manager.py", line 752, in startup_worker
    self.client.get_space_usage()
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/client.py", line 521, in get_space_usage
    return convert_space_usage(res)
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/client.py", line 1538, in convert_space_usage
    res.allocation.get_team().usage, res.allocation.get_team().allocation
AttributeError: 'TeamSpaceAllocation' object has no attribute 'usage'
2022-03-22 11:48:41 manager INFO: Shutting down threads...
2022-03-22 11:48:41 sync INFO: Sync aborted
2022-03-22 11:48:41 manager INFO: Paused
```

**Comment by mark-oei** [comment]
Hit similar issue after being prompted to upgrade to 1.6 on macOS High Sierra.

No way to stay on 1.6 as it was stucked. Reverted back to 1.5.x and select skip on 1.6 when prompted again.

Log file says:

```
022-03-22 01:18:30 daemon INFO: Starting daemon
2022-03-22 01:18:30 manager INFO: Connected
2022-03-22 01:18:32 sync INFO: Fetching remote changes
2022-03-22 01:18:33 sync INFO: Indexing local changes...
2022-03-22 01:18:34 manager ERROR: Database transaction error
Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/sync.py", line 1513, in _database_access
  File "Contents/Resources/app_packages/maestral/sync.py", line 782, in iter_index
  File "Contents/Resources/app_packages/maestral/database/orm.py", line 251, in select_iter
  File "Contents/Resources/app_packages/maestral/database/core.py", line 49, in execute
sqlite3.OperationalError: no such column: TRUE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/manager.py", line 805, in _handle_sync_thread_errors
  File "Contents/Resources/app_packages/maestral/manager.py", line 790, in startup_worker
  File "Contents/Resources/app_packages/maestral/sync.py", line 1588, in upload_local_changes_while_inactive
  File "Contents/Resources/app_packages/maestral/sync.py", line 1683, in _get_local_changes_while_inactive
  File "Contents/Resources/app_packages/maestral/sync.py", line 783, in iter_index
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/contextlib.py", line 135, in __exit__
  File "Contents/Resources/app_packages/maestral/sync.py", line 1536, in _database_access
  File "Contents/Resources/app_packages/maestral/sync.py", line 1513, in _database_access
  File "Contents/Resources/app_packages/maestral/sync.py", line 782, in iter_index
  File "Contents/Resources/app_packages/maestral/database/orm.py", line 251, in select_iter
  File "Contents/Resources/app_packages/maestral/database/core.py", line 49, in execute
maestral.exceptions.DatabaseError: Database transaction error. The index file at "/Users/Marcus/Library/Application Support/maestral/maestral.db" cannot be read. Please check that you have sufficient permissions and rebuild the index if necessary.
2022-03-22 01:18:34 manager INFO: Shutting down threads...
2022-03-22 01:18:34 sync INFO: Sync aborted
2022-03-22 01:18:34 manager INFO: Paused
2022-03-22 01:19:50 sync INFO: Sync aborted

```

**Comment by samschott** [comment]
@mark-oei, could you open a new issue for that? This seems to be unrelated to the original issue and might be a problem with the version of SQLite that comes with macOS High Sierra.

**Comment by samschott** [comment]
@Roy-Orbison, thanks for reporting, this was a stupid oversight on my side. The attribute we should be reading is `TeamSpaceAllocation.used` and not `TeamSpaceAllocation.usage`.

**Comment by Roy-Orbison** [comment]
Mistakes happen. Cheers for getting on to it quickly. Didn't seem like a data loss scenario, is it?

**Comment by mark-oei** [comment]
@samschott , sure, happy to do that. Thank you for looking into the error.

**Comment by samschott** [comment]
> Mistakes happen. Cheers for getting on to it quickly. Didn't seem like a data loss scenario, is it?

Nope, just an error when reading the space usage reported by the Dropbox API, specific to users with team accounts. Just a very annoying one, because it causes a high-level crash instead of failing silently and reporting an incorrect usage...
