### ISSUE TITLE
"Setting up" error upon upgrade to 1.6 on macOS High Sierra

### ISSUE THREAD

**Issue by mark-oei** [samschott/maestral#644]
**Describe the bug**
Hit the "Setting up" error immediately after upgrade to 1.6. Unable to proceed. Reverted back to 1.5.x. Skipping 1.6 for now.

Notification says 
"Database transaction error. The index file at "/Users/Marcus/Library/Application Support/maestral/maestral.db" cannot be read."

**To Reproduce**
On macOS High Sierra, upgrade to 1.6 and get this error.

**Expected behaviour**
Expect to finish setting up and start syncing.

**System:**
 - Maestral version: 1.6 GUI
 - Python version: 2.7.16
 - OS: macOS High Sierra 10.13.6

**Additional context**
Log file

```
022-03-22 01:18:30 daemon INFO: Starting daemon
2022-03-22 01:18:30 manager INFO: Connected
2022-03-22 01:18:32 sync INFO: Fetching remote changes
2022-03-22 01:18:33 sync INFO: Indexing local changes...
2022-03-22 01:18:34 manager ERROR: Database transaction error
Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/sync.py", line 1513, in _database_access
  File "Contents/Resources/app_packages/maestral/sync.py", line 782, in iter_index
  File "Contents/Resources/app_packages/maestral/database/orm.py", line 251, in select_iter
  File "Contents/Resources/app_packages/maestral/database/core.py", line 49, in execute
sqlite3.OperationalError: no such column: TRUE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/manager.py", line 805, in _handle_sync_thread_errors
  File "Contents/Resources/app_packages/maestral/manager.py", line 790, in startup_worker
  File "Contents/Resources/app_packages/maestral/sync.py", line 1588, in upload_local_changes_while_inactive
  File "Contents/Resources/app_packages/maestral/sync.py", line 1683, in _get_local_changes_while_inactive
  File "Contents/Resources/app_packages/maestral/sync.py", line 783, in iter_index
  File "Contents/Resources/Support/Python/Resources/lib/python3.9/contextlib.py", line 135, in __exit__
  File "Contents/Resources/app_packages/maestral/sync.py", line 1536, in _database_access
  File "Contents/Resources/app_packages/maestral/sync.py", line 1513, in _database_access
  File "Contents/Resources/app_packages/maestral/sync.py", line 782, in iter_index
  File "Contents/Resources/app_packages/maestral/database/orm.py", line 251, in select_iter
  File "Contents/Resources/app_packages/maestral/database/core.py", line 49, in execute
maestral.exceptions.DatabaseError: Database transaction error. The index file at "/Users/Marcus/Library/Application Support/maestral/maestral.db" cannot be read. Please check that you have sufficient permissions and rebuild the index if necessary.
2022-03-22 01:18:34 manager INFO: Shutting down threads...
2022-03-22 01:18:34 sync INFO: Sync aborted
2022-03-22 01:18:34 manager INFO: Paused
2022-03-22 01:19:50 sync INFO: Sync aborted

```

**Comment by samschott** [comment]
Yeah, I can confirm that this is an issue with how we query the database being incompatible with the version of SQLite that ships with macOS High Sierra.

**Comment by samschott** [comment]
v1.6.1 is now out with a fix.
