### ISSUE TITLE
Unexected Error: Please restart to continue

### ISSUE THREAD

**Issue by mike-nolan** [samschott/maestral#648]
**Describe the bug**

Since updating to `v1.6.0`, Maestral has paused syncing and is displaying an `Unexpected Error` notification. Restarting Maestral and system restarts have not solved the issue. Something to note is the account Maestral is syncing is a Dropbox Business Account.

**Error Log**

```log
2022-03-23 10:17:31 daemon INFO: Starting daemon
2022-03-23 10:17:31 manager INFO: Connected
2022-03-23 10:17:32 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/manager.py", line 805, in _handle_sync_thread_errors
  File "Contents/Resources/app_packages/maestral/manager.py", line 752, in startup_worker
  File "Contents/Resources/app_packages/maestral/client.py", line 521, in get_space_usage
  File "Contents/Resources/app_packages/maestral/client.py", line 1538, in convert_space_usage
AttributeError: 'TeamSpaceAllocation' object has no attribute 'usage'
2022-03-23 10:17:32 manager INFO: Shutting down threads...
2022-03-23 10:17:32 sync INFO: Sync aborted
2022-03-23 10:17:32 manager INFO: Paused
```

**System:**
 - Maestral version: `GUI v1.6.0, daemon v1.6.0`
 - Python version: `3.8.5`
 - OS: `macOS Monterey 12.3`

**Additional context**

Screenshot of the notification shown:

![notification_screenshot](https://user-images.githubusercontent.com/5537232/159678201-98542aad-59e8-4b90-a4ab-4110ba998903.png)

**Comment by cornexo** [comment]
I have the same issue, same configuration.

**Comment by ntodd** [comment]
I am seeing the same error in the logs. M1 Mac with a Dropbox Business account.

**Comment by samschott** [comment]
Apologies for this, v1.6.1 is now out with a fix. This was an error when querying the space usage for Team accounts.

**Comment by mike-nolan** [comment]
Confirmed fixed on my end. Thanks, @samschott !

**Comment by cornexo** [comment]
Thank you!

**Comment by ubidefeo** [comment]
@samschott 
I'm on 1.6.1 but still get this error

the daemon pauses and if I try "resume syncing" I get this "restart" error
<img width="249" alt="CleanShot 2022-04-03 at 18 19 13@2x" src="https://user-images.githubusercontent.com/1894487/161437576-2802057e-e1e3-4732-b1d0-e20544c44121.png">

**Comment by ubidefeo** [comment]
Never mind, I got confused by not having the version of the GUI app available but the daemon's.
Please consider exposing the GUI version too

**Comment by dinomite** [comment]
@ubidefeo Would you expand on your comment? I'm getting this error, but when I do "Check for updates…" Maestral says it's up to date (1.6.1).
