### ISSUE TITLE
`ModuleNotFoundError: No module named '_curses'` when running `maestral activity`

### ISSUE THREAD

**Issue by frozenpandaman** [samschott/maestral#699]
Seems the bug in #533 & #591 has popped up again after updating to 1.6.3:

```
$ maestral activity                                              
Traceback (most recent call last):
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/runpy.py", line 86, in _run_code
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 41, in <module>
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 36, in freeze_support_cli
  File "Contents/Resources/app_packages/click/core.py", line 1130, in __call__
  File "Contents/Resources/app_packages/click/core.py", line 1055, in main
  File "Contents/Resources/app_packages/click/core.py", line 1657, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 1404, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 760, in invoke
  File "Contents/Resources/app_packages/maestral/cli/common.py", line 107, in wrapper
  File "Contents/Resources/app_packages/click/core.py", line 760, in invoke
  File "Contents/Resources/app_packages/maestral/cli/common.py", line 32, in wrapper
  File "Contents/Resources/app_packages/maestral/cli/cli_info.py", line 85, in activity
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/curses/__init__.py", line 13, in <module>
ModuleNotFoundError: No module named '_curses'
```

The workaround in that earlier issue still works.

Using Python 3.9.13 on macOS 12.3.1, Maestral v1.6.3 installed via Homebrew.

**Comment by samschott** [comment]
Damn, apparently moving the app bundle to Python 3.10 was a bit premature.

The problem is: the macOS app bundle, whether installed through Homebrew or otherwise, come with its own CPython library. It turns out that the Python 3.10 library which we are using does not currently link against libcurses, therefore the missing module error and the missing functionality.

Fixing this will be annoying because we are using the Python build from the BeeWare project at https://github.com/beeware/Python-Apple-support. Essentially, we could either revert to using their Python 3.9 build or move to their newest build of Python 3.10 which again support curses (a patch which I submitted). However, the latter can only be used on macOS 10.15 and higher. This means we either take a step back, or leave some users behind...

**Comment by frozenpandaman** [comment]
Dang, annoying! Thanks for looking into this. How much of a hassle would it be (if even possible at all) to distribute two separate Mac versions, one using Python 3.10 for 10.15+ users, and another with Python 3.9 for users on older OSes? Or – is there any downside on still using Python 3.9 for the time being?

**Comment by slifty** [comment]
Just to have some relevant factoids for the discussion / decision:

1. Catalina came out October, 2019 (so about 2.5 years ago)
2. It looks like around 96% of MacOS homebrew [users in the past 30 days](https://formulae.brew.sh/analytics/os-version/30d/) are on 10.15+
3. If you want a longer window, [93% in the past year](https://formulae.brew.sh/analytics/os-version/365d/)

<img width="913" alt="image" src="https://user-images.githubusercontent.com/208884/172182619-b5a6b354-d924-474c-9e4c-e9d65fa3817b.png">

**Comment by samschott** [comment]
@slifty, thanks for the info, this is quite useful! I am lacking this insight from GitHub releases downloads and don't collect any analytics whatsoever which might be helpful here. Essentially, I am flying blind. At least now I have some info about the homebrew subset of users.

Also, I never expected this project to become something which requires a "project policy" or any form of release planning. I started it way before I would have called myself a software engineer. However, it might be time to give users a better way to plan ahead.

**Comment by philippgerard** [comment]
I just ran into this, too.

Any idea when this will be resolved, @samschott ? I think it's good to cut out some dead wood, in the best tradition of Apple, in case you're still contemplating what to do with <10.15 users.

**Comment by samschott** [comment]
Soon :)
