### ISSUE TITLE
Re-authorising Dropbox token hangs

### ISSUE THREAD

**Issue by johnfrombluff** [samschott/maestral#713]
**Describe the bug**

I was prompted by the GUI that the Dropbox authorisation token had expired and I needed to re-authorise. I clicked on the link in the dialog box, got the token and pasted it into the dialog box and pressed "Link". Then the spinner appeared, and spun for approximately 4 hours before I rebooted in frustration. The same behaviour exhibited after a reboot.

**To Reproduce**

Follow the steps above.

**Expected behaviour**

Maestral re-authorised, and if it's an operation that can be expected to take more than a few seconds, provides a progress meter.

**System:**

 - Maestral version: 1.6.3
 - Python version:  3.10.5
 - OS: [e.g. Ubuntu]  Fedora Silverblue 36
 - Desktop environment: [e.g. Gnome 3.32] Gnome 42.3
 - PyQt version (for Linux GUI): 5.15.2,  6.3.0

**Additional context**

Nothing more to add

**Comment by samschott** [comment]
Thanks for the report. This looks like a bug in the Linux GUI, I’ll see if I can reproduce this.

In the meantime, could you try to refresh the token through the CLI with the following command?
ˋˋˋ
maestral auth link --relink
ˋˋˋ
This should hopefully work without problems or at least print a helpful error message.

**Comment by dwu** [comment]
I'm seeing the same behavior when linking a maestral instance on a new machine: maestral hangs after auth code input. This happens on both the GUI and the CLI.

When increasing the debug log verbosity the hang occurs after the following log statements when executing `maestral auth link` in the CLI. `Path root nsid` contains a namespace id, `User home path` is empty.

```
2022-07-31 17:48:17 manager INFO: Connected
2022-07-31 17:48:35 dropbox_client DEBUG: Refreshing access token.
2022-07-31 17:48:35 dropbox_client DEBUG: Request to users/get_current_account
2022-07-31 17:48:36 client DEBUG: Path root type: user
2022-07-31 17:48:36 client DEBUG: Path root nsid: <namespace-id>
2022-07-31 17:48:36 client DEBUG: User home path:
```

**System:**
- Maestral version: 1.6.3
- Python version: 3.10.5
- OS: Archlinux
- PyQt version (for Linux GUI): version installed via pip; PyQt6-6.3.1

**Comment by johnfrombluff** [comment]
Thank you for your quick and helpful reply!  Sadly, didn't work:
`[john@lounge ~]$ maestral auth link --relink
- Linking new account for 'maestral' config
- Retrieving auth code from Dropbox
? How would you like to you link your account? Open Dropbox website
? Enter the auth code: CPl-rDRJD3cAAAAAAAAvd0IY0NkoKzjKZE6IRjf4Nag
Traceback (most recent call last):
  File "/home/john/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/john/.local/lib/python3.10/site-packages/maestral/cli/common.py", line 107, in wrapper
    return ctx.invoke(f, proxy, *args, **kwargs)
  File "/home/john/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/john/.local/lib/python3.10/site-packages/maestral/cli/common.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/john/.local/lib/python3.10/site-packages/maestral/cli/cli_core.py", line 344, in auth_link
    link_dialog(m)
  File "/home/john/.local/lib/python3.10/site-packages/maestral/cli/cli_core.py", line 137, in link_dialog
    res = m.link(auth_code)
  File "/home/john/.local/lib/python3.10/site-packages/maestral/main.py", line 198, in link
    return self.client.link(token)
  File "/home/john/.local/lib/python3.10/site-packages/maestral/client.py", line 232, in link
    self._cred_storage.save_creds(
  File "/home/john/.local/lib/python3.10/site-packages/maestral/keyring.py", line 282, in save_creds
    output.ok("Credentials written")
  File "/home/john/.local/lib/python3.10/site-packages/maestral/cli/output.py", line 548, in ok
    echo(message, nl=nl, prefix=Prefix.Ok)
  File "/home/john/.local/lib/python3.10/site-packages/maestral/cli/output.py", line 518, in echo
    click.echo(f"{pre}{message}", nl=nl)
  File "/home/john/.local/lib/python3.10/site-packages/click/utils.py", line 299, in echo
    file.write(out)  # type: ignore
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 5: ordinal not in range(256)
`

**Comment by samschott** [comment]
Uh, this looks like the linking worked but the success message could not be printed. Your terminal stdout seems to be configured with latin-1 encoding?

**Comment by samschott** [comment]
In any case, I've fixed the original issue with relinking not working after the client was already initialised. It was not in the GUI layer after all but in the backend. The fix will be rolled out with the next update.

**Comment by johnfrombluff** [comment]
Wonderful! Thank you Sam :-)
