### ISSUE TITLE
Maestral crashes on launch

### ISSUE THREAD

**Issue by princeofsky** [samschott/maestral#721]
**Describe the bug**
Maestral crashes on launch.

**To Reproduce**

**Expected behaviour**

**System:**

 - Maestral version: 1.6.3
 - Python version: 3.10.6
 - OS: MacOS 10.14.6

**Additional context**
Here's the traceback:
Traceback (most recent call last):
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 43, in <module>
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 14, in main
  File "Contents/Resources/app/maestral_cocoa/app.py", line 44, in <module>
  File "Contents/Resources/app/maestral_cocoa/private/widgets.py", line 17, in <module>
  File "Contents/Resources/app/maestral_cocoa/private/platform.py", line 25, in get_platform_factory
  File "Contents/Resources/app/maestral_cocoa/private/implementation/cocoa/factory.py", line 26, in <module>
  File "Contents/Resources/app_packages/toga_cocoa/libs/__init__.py", line 25, in <module>
  File "Contents/Resources/app_packages/toga_cocoa/libs/appkit.py", line 32, in <module>
  File "Contents/Resources/app_packages/rubicon/objc/runtime.py", line 61, in load_library
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/ctypes/__init__.py", line 374, in __init__
OSError: dlopen(/Library/Frameworks/AppKit.framework/AppKit, 6): no suitable image found.  Did find:
	/Library/Frameworks/AppKit.framework/AppKit: code signature in (/Library/Frameworks/AppKit.framework/AppKit) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)

**Comment by samschott** [comment]
Apologies for the slow response time. This is not a good error message, it suggests that the AppKit framework at `/Library/Frameworks/AppKit.framework/AppKit` does not appear to be properly signed, even though it is distributed with macOS.

Best case scenario: Maestral 1.6.3 was compiled with library validation enabled in a way which is not compatible with macOS Mojave and earlier.

**Comment by samschott** [comment]
Closing as packaging and signing now works differently. Feel free to reopen if this still persists with the latest release.
