### ISSUE TITLE
Maestral won't sync anymore

### ISSUE THREAD

**Issue by janiosarmento** [samschott/maestral#754]
Maestral stopped syncing overnight with an error message.

**To Reproduce**

Just leave Maestral running. The error will popup, and syncing will get paused until it automatically tries restart syncing, in an endless loop.

**Expected behaviour**

No errors or syncingpauses.

**System:**

 - Maestral version: 1.6.3
 - Python version: 3.10 (Macos Bundled)
 - OS: Macos Ventura
 - Desktop environment: Macos
 - PyQt version (for Linux GUI): N/A

**Additional context**
```
Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/errorhandling.py", line 91, in convert_api_errors
  File "Contents/Resources/app_packages/maestral/client.py", line 612, in get_metadata
  File "Contents/Resources/app_packages/dropbox/base.py", line 1670, in files_get_metadata
  File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 323, in request
  File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 473, in request_json_string_with_retry
  File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 593, in request_json_string
  File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 629, in raise_dropbox_error_for_resp
dropbox.exceptions.BadInputError: BadInputError('a61b7d2cccbd4e4d82484dbeffeed437', 'Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/manager.py", line 842, in _handle_sync_thread_errors
  File "Contents/Resources/app_packages/maestral/manager.py", line 827, in startup_worker
  File "Contents/Resources/app_packages/maestral/sync.py", line 1597, in upload_local_changes_while_inactive
  File "Contents/Resources/app_packages/maestral/sync.py", line 1850, in apply_local_changes
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/concurrent/futures/_base.py", line 608, in result_iterator
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/concurrent/futures/_base.py", line 445, in result
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/concurrent/futures/thread.py", line 52, in run
  File "Contents/Resources/app_packages/maestral/sync.py", line 2200, in _create_remote_entry
  File "Contents/Resources/app_packages/maestral/sync.py", line 2362, in _on_local_file_created
  File "Contents/Resources/app_packages/maestral/sync.py", line 2710, in _check_requires_upload
  File "Contents/Resources/app_packages/maestral/client.py", line 197, in wrapper
  File "Contents/Resources/app_packages/maestral/client.py", line 186, in wrapper
  File "Contents/Resources/app_packages/maestral/client.py", line 611, in get_metadata
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/contextlib.py", line 153, in __exit__
  File "Contents/Resources/app_packages/maestral/errorhandling.py", line 93, in convert_api_errors
maestral.exceptions.BadInputError: Bad input to API call. Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata
2022-11-24 04:31:08 manager INFO: Shutting down threads...
2022-11-24 04:31:08 sync INFO: Sync aborted
2022-11-24 04:31:08 manager INFO: Paused
2022-11-24 04:32:02 sync INFO: Fetching remote changes
2022-11-24 04:32:03 sync INFO: Indexing local changes...
```

**Comment by Jook3r** [comment]
I have started using maestral since I got my hands on aarch64 server where I tried to use dropbox and found out its not available for arm arch. It was working fine last night but today I noticed it was not syncing anything with exactly same error as above.

    Bad input to API call
    Error in call to API function "files/get_metadata": Unknown API function: /2/files/get_metadata

**Comment by eimermusic** [comment]
+1

**Comment by pablosproject** [comment]
It's a problem on Dropbox side, look [here](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/API-function-get-metadata-started-to-fail/td-p/638921).

They should fix their API and the app will start syncing again

**Comment by rorymullen** [comment]
Same problem here on my mac mini, but oddly Maestral is working on my MacBook air, both M1... 

Hopefully dropbox will get this sorted soon, it's a shame dropbox is so dominant in this space, their product is terrible, thanks Sam for making Maestral!

<img width="251" alt="Screenshot 2022-11-24 at 8 08 20 AM" src="https://user-images.githubusercontent.com/14242126/203728508-a0a50a5c-d451-49a4-a44e-61f2bdc9f36c.png">

**Comment by Jook3r** [comment]
Okay, just before I read above responses. I tried stopping daemon completely and tried restarting it. Now I get this error too even though its a headless server. Is it relevant to the issue?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/desktop_notifier/base.py", line 204, in send
    platform_nid = await self._send(notification, notification_to_replace)
  File "/usr/local/lib/python3.6/dist-packages/desktop_notifier/dbus.py", line 113, in _send
    self.interface = await self._init_dbus()
  File "/usr/local/lib/python3.6/dist-packages/desktop_notifier/dbus.py", line 78, in _init_dbus
    self.bus = await MessageBus().connect()
  File "/usr/local/lib/python3.6/dist-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/usr/local/lib/python3.6/dist-packages/dbus_next/message_bus.py", line 72, in __init__
    get_bus_address(bus_type))
    File "/usr/local/lib/python3.6/dist-packages/dbus_next/_private/address.py", line 98, in get_bus_address
      return get_session_bus_address()
    File "/usr/local/lib/python3.6/dist-packages/dbus_next/_private/address.py", line 57, in get_session_bus_address
      'DBUS_SESSION_BUS_ADDRESS not set and could not get DISPLAY environment variable to get bus address'
  dbus_next.errors.InvalidAddressError: DBUS_SESSION_BUS_ADDRESS not set and could not get DISPLAY environment variable to get bus address
```

**Comment by Jook3r** [comment]
Yes I installed vnc a few days ago, it probably thinks there is a display when there is none. I think even with this error once api error is resolved maestral will work fine. :)

**Comment by jschmid** [comment]
I have to same issue on 1Password for Android. As https://github.com/samschott/maestral/issues/754#issuecomment-1326090593 mentioned, it must be an issue on Dropbox side, not Maestral.

**Comment by ricir** [comment]
Same issue both on Maestral and Dropsync on Android. Definitely a Dropbox issue.

**Comment by rorymullen** [comment]
Maestral is working again for me now...

**Comment by pablosproject** [comment]
Yeah, looks like they fixed it. @janiosarmento consider closing this now.

**Comment by alex27riva** [comment]
For me is not working:
![immagine](https://user-images.githubusercontent.com/5512235/203744880-3b6bb3b1-bc8a-4ba5-9e3d-7920750384e1.png)
I'm on Fedora 37

**Comment by hb9eue** [comment]
I am also still getting this error. Running Maestral 1.6.3

**Comment by pablosproject** [comment]
I think the rollout of solution on their end will take some time to reach all zones.

**Comment by janiosarmento** [comment]
Closing since it's not an issue of Maestral's.
