### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by jeanpaulrh** [samschott/maestral#824]
Hi, today my computer restarted without a reason (didn't have time to investigate yet) and after restart Maestral showed me a message about an error restarting after login.
In the log I found this;

```
Traceback (most recent call last):
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/config/main.py", line 106, in _get_conf
    conf = registry[config_name]
KeyError: 'maestral'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/daemon.py", line 460, in start_maestral_daemon
    maestral_daemon = expose(Maestral)(config_name, log_to_stderr=log_to_stderr)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/main.py", line 151, in __init__
    self._state = MaestralState(self.config_name)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/config/main.py", line 167, in MaestralState
    return _get_conf(config_name, state_path, DEFAULTS_STATE, _state_instances)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/config/main.py", line 110, in _get_conf
    conf = UserConfig(
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/config/user.py", line 137, in __init__
    self._load_from_ini(self.config_path)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/config/user.py", line 211, in _load_from_ini
    self.read(path, encoding="utf-8")
  File "/usr/lib/python3.10/configparser.py", line 698, in read
    self._read(fp, filename)
  File "/usr/lib/python3.10/configparser.py", line 1021, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid start byte
2023-02-04 09:22:06 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/Pyro5/client.py", line 310, in connect_and_handshake
    sock = socketutil.create_socket(connect=connect_location,
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/Pyro5/socketutil.py", line 283, in create_socket
    sock.connect(connect)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/daemon.py", line 532, in start_maestral_daemon_process
    wait_for_startup(config_name, timeout)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/daemon.py", line 348, in wait_for_startup
    raise exc
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/daemon.py", line 344, in wait_for_startup
    maestral_daemon._pyroBind()
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/Pyro5/client.py", line 214, in _pyroBind
    return self.__pyroCreateConnection(True)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/Pyro5/client.py", line 376, in __pyroCreateConnection
    connect_and_handshake(conn)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/Pyro5/client.py", line 336, in connect_and_handshake
    raise errors.CommunicationError(err) from x
Pyro5.errors.CommunicationError: cannot connect to /run/user/1000/maestral/maestral.sock: [Errno 2] No such file or directory
2023-02-04 09:22:06 daemon ERROR: Daemon is running but not responsive, killing now

```

So I tried to delete the package and reinstall it (I'm using pip installation), but after reinstallation I started 

`maestral gui`

and I got this error 

`QImage::pixel: coordinate (0,0) out of range
Traceback (most recent call last):
  File "/home/gianpaolo/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/cli/cli_core.py", line 303, in gui
    run(config_name)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral_qt/main.py", line 625, in run
    maestral_gui.load_maestral()
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral_qt/main.py", line 187, in load_maestral
    self.mdbx = self.get_or_start_maestral_daemon()
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral_qt/main.py", line 225, in get_or_start_maestral_daemon
    return MaestralProxy(self.config_name)
  File "/home/gianpaolo/.local/lib/python3.10/site-packages/maestral/daemon.py", line 650, in __init__
    raise CommunicationError(f"Could not get proxy for '{config_name}'")
Pyro5.errors.CommunicationError: Could not get proxy for 'maestral'
`
Any suggestion?
Thanks.

**Comment by samschott** [comment]
I suspect the relevant line is the following:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid start byte
```
This, together with the preceding lines, indicates that Maestral has trouble reading it's "state" file where it saves data such as the timestamp of the last sync. This file has a simple ini format, similar to the config file.

File corruption could have happened for example during a non-graceful shutdown.

On Linux, the file should be located at `~/.local/share/maestral/maestral.state`, though the location may vary depending on how `$XDG_DATA_DIR` is configured on your machine.

You could do either of the following:
1. Open the state file manually in a text editor and check for any non-unicode characters.
2. If the above does not work, delete the file. Maestral might ask you to re-link on the next startup and will then proceed with a quick re-sync to ensure everything is up-to-date.

**Comment by jeanpaulrh** [comment]
Thanks. I had to delete the file (it was a binary file so I deleted to speed up the resolution) and re-link the account.
