### ISSUE TITLE
requests ChunkedEncodingError when connection is reset by Dorpbox

### ISSUE THREAD

**Issue by SamSchott** [SamSchott/maestral#89]
## Error in Maestral

**RuntimeError** in **bugsnag/notification.py:127**
ChunkedEncodingError

[View on Bugsnag](https://app.bugsnag.com/university-of-cambridge/maestral/errors/5e543d6e382ec9001b916660?event_id=5e543d6e0055e21cf8db0000&i=gh&m=ci)

## Stacktrace

  Traceback (most recent call last):
    File "urllib3/response.py", line 425, in _error_catcher
    File "urllib3/response.py", line 507, in read
    File "http/client.py", line 457, in read
    File "http/client.py", line 501, in readinto
    File "socket.py", line 589, in readinto
    File "ssl.py", line 1071, in recv_into
    File "ssl.py", line 929, in read
  ConnectionResetError: [Errno 54] Connection reset by peer

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "requests/models.py", line 750, in generate
    File "urllib3/response.py", line 564, in stream
    File "urllib3/response.py", line 529, in read
    File "contextlib.py", line 130, in __exit__
    File "urllib3/response.py", line 443, in _error_catcher
  urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "maestral/sync/monitor.py", line 1725, in download_worker
    File "maestral/sync/monitor.py", line 240, in wrapper
    File "maestral/sync/monitor.py", line 1300, in get_remote_dropbox
    File "maestral/sync/monitor.py", line 1408, in apply_remote_changes
    File "concurrent/futures/_base.py", line 428, in result
    File "concurrent/futures/_base.py", line 384, in __get_result
    File "concurrent/futures/thread.py", line 57, in run
    File "maestral/sync/monitor.py", line 240, in wrapper
    File "maestral/sync/monitor.py", line 1612, in _create_local_entry
    File "maestral/sync/client.py", line 115, in wrapper
    File "maestral/sync/client.py", line 285, in download
    File "dropbox/base.py", line 1240, in files_download_to_file
    File "dropbox/dropbox.py", line 523, in _save_body_to_file
    File "requests/models.py", line 753, in generate
  requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))

[View full stacktrace](https://app.bugsnag.com/university-of-cambridge/maestral/errors/5e543d6e382ec9001b916660?event_id=5e543d6e0055e21cf8db0000&i=gh&m=ci)

*Created by Sam Schott via Bugsnag*

**Comment by SamSchott** [comment]
Closing because issue cannot be reproduced. Will be reopened if it occurs in version  > 0.5.2.

**Comment by SamSchott** [comment]
An error linked to this issue has been reopened in Bugsnag
[**RuntimeError** in **bugsnag/notification.py:127**](https://app.bugsnag.com/university-of-cambridge/maestral/errors/5e543d6e382ec9001b916660?event_id=5e90772a0059b41e16b40000&i=gh&m=ra)

**Comment by SamSchott** [comment]
This issue has been unlinked from an error in Bugsnag
[**RuntimeError** in **bugsnag/notification.py:127**](https://app.bugsnag.com/university-of-cambridge/maestral/errors/5e543d6e382ec9001b916660?event_id=5e9218fe0059a06711110000&i=gh&m=ul)
