### ISSUE TITLE
Maestral won't start at all - ERROR: database disk image is malformed

### ISSUE THREAD

**Issue by cobyism** [samschott/maestral#908]
**Describe the bug**

Left my laptop (macbook air m2) to sync my dropbox folder overnight, but it seems it restarted itself at some point. When I went to reopen Maestral, I get errors no matter which way I start the application. I also cannot seem to rebuild the index using the provided CLI command.

When starting the GUI:

![CleanShot 2023-05-17 at 13 19 22](https://github.com/samschott/maestral/assets/296432/365f7035-2cc0-4466-89a4-e0a49b8f0a40)

Pressing OK shows the following logs:

![CleanShot 2023-05-17 at 13 19 31](https://github.com/samschott/maestral/assets/296432/6bee3874-9042-48e1-b3f1-773528552c79)

When I attempt to start maestral via the CLI, here's what I see:

![CleanShot 2023-05-17 at 13 32 45](https://github.com/samschott/maestral/assets/296432/2e0b488b-ccc0-49b3-9e71-cbba1b59e673)

Here's the output of `maestral log show`:

```
2023-05-17 13:33:10 daemon INFO: Starting daemon
2023-05-17 13:33:10 daemon ERROR: database disk image is malformed
Traceback (most recent call last):
  File "app_packages/maestral/daemon.py", line 461, in start_maestral_daemon
  File "app_packages/maestral/main.py", line 202, in __init__
  File "app_packages/maestral/sync.py", line 578, in __init__
  File "app_packages/maestral/database/orm.py", line 252, in __init__
  File "app_packages/maestral/database/orm.py", line 423, in _has_table
  File "app_packages/maestral/database/core.py", line 32, in execute
sqlite3.DatabaseError: database disk image is malformed
2023-05-17 13:33:39 daemon ERROR: Could not communicate with daemon
Traceback (most recent call last):
  File "app_packages/Pyro5/client.py", line 310, in connect_and_handshake
  File "app_packages/Pyro5/socketutil.py", line 283, in create_socket
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app_packages/maestral/daemon.py", line 537, in start_maestral_daemon_process
  File "app_packages/maestral/daemon.py", line 348, in wait_for_startup
  File "app_packages/maestral/daemon.py", line 344, in wait_for_startup
  File "app_packages/Pyro5/client.py", line 214, in _pyroBind
  File "app_packages/Pyro5/client.py", line 376, in __pyroCreateConnection
  File "app_packages/Pyro5/client.py", line 336, in connect_and_handshake
Pyro5.errors.CommunicationError: cannot connect to /Users/[REDACTED]/Library/Application Support/maestral/maestral.sock: [Errno 2] No such file or directory
2023-05-17 13:33:39 daemon ERROR: Daemon is running but not responsive, killing now
```

I also get effectively the same output when I run `maestral rebuild-index`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "app/maestral_cocoa/__main__.py", line 41, in <module>
  File "app/maestral_cocoa/__main__.py", line 36, in freeze_support_cli
  File "app_packages/click/core.py", line 1130, in __call__
  File "app_packages/click/core.py", line 1055, in main
  File "app_packages/click/core.py", line 1657, in invoke
  File "app_packages/click/core.py", line 1404, in invoke
  File "app_packages/click/core.py", line 760, in invoke
  File "app_packages/maestral/cli/common.py", line 105, in wrapper
  File "app_packages/maestral/daemon.py", line 652, in __init__
  File "app_packages/maestral/main.py", line 202, in __init__
  File "app_packages/maestral/sync.py", line 578, in __init__
  File "app_packages/maestral/database/orm.py", line 252, in __init__
  File "app_packages/maestral/database/orm.py", line 423, in _has_table
  File "app_packages/maestral/database/core.py", line 32, in execute
sqlite3.DatabaseError: database disk image is malformed
```

Here's a screenshot of the MacOS error console filtered on `maestral`, in case it adds any info:

![CleanShot 2023-05-17 at 13 30 28](https://github.com/samschott/maestral/assets/296432/9dfd8ea1-d4f1-40ed-9070-fb9f30dfd46b)

**To Reproduce**

Given I was not present at the computer at the time it restarted, I'm not entirely sure how I could reproduce this error, and I haven't attempted to work out how to reproduce it. If there's anything I can do to aid in troubleshooting this let me know and I'll provide what info I can.

**Expected behaviour**

If the system restarts unexpectedly, I would expect maestral to be able to handle this event and successfully recover when the system comes back up and the maestral application is started again. At the very least, if the maestral application does get into a state with an issue, I would expect some built-in CLI command (even if for devs/power users) to be able to successfully repair whatever database/index has become corrupt.

**System:**

 - Maestral version: `1.7.2`
 - Python version: `3.11.2`
 - OS: MacOS 13.3.1 (a) (22E772610a)
 - Desktop environment: MacOS
 - PyQt version (for Linux GUI): `N/A`

**Additional context**

`N/A`

**Comment by samschott** [comment]
Thanks for the detailed report, including error logs!

It looks like you have run into an unfortunate combination of multiple issues. At the root of it, as you have reported, is an issue with opening the local Sqlite database.

> If the system restarts unexpectedly, I would expect maestral to be able to handle this event and successfully recover when the system comes back up and the maestral application is started again.

This should indeed be the case. Before a regular restart, macOS will send SIGTERM to all running applications, and Maestral will handle this by shutting down its sync threads and quitting within < 1 sec. If it receives a SIGKILL (force quit), it will exit less gracefully, but should still remain in a consistent state since database transactions are atomic (they either succeed or don't modify the database at all).

There are some very rare scenarios were database corruption can still occur, https://sqlite.org/howtocorrupt.html has a good writeup of those.

The first are programming errors, e.g., if non-sqlite code accidentally writes to the database file (this can happen when trying to write to another already closed file descriptor). I'll have a look at file write issued by Maestral, but I don't think this should be happening anywhere. Another possibility is power loss during or after a DB transaction. Due to a quirk of how writes to disk are often kept in the disk's buffer while being reported as completed, power failure may result in the disk buffer not being flushed and files being corrupted. Guarding against this will be practically impossible.

In addition to this root cause, Maestral should certainly handle the DB error more transparently instead of showing a generic startup failure. I'll look into that. I also agree that better instructions or even a CLI command to recover from this would be useful.

In the meantime, you can recover from this manually by (1) making sure that Maestral is not running (also check in Activity Monitor for any daemon processes left over from bad shutdowns) and (2) delete the DB and sync state files:

```
~/Library/Application Support/maestral/maestral.db
~/Library/Application Support/maestral/maestral.state
```

When starting Maestral again, it will perform a full resync and repopulate the database.

**Comment by cobyism** [comment]
Thanks for the great answer! I'll attempt manual recovery as suggested. 🙇‍♂️ 🙏 ✨

**Comment by cobyism** [comment]
@samschott Deleting `maestral.db` and `maestral.state` and restarting Maestral worked fine. Thanks again!

Would it ever make sense to make a command available to users to cover this scenario? i.e. something like `maestral full-resync --confirm`? Probably unnecessary, especially if it's an option to rejig the order of operations as per #914 I guess…

**Comment by samschott** [comment]
Glad it worked! I'm not sure if a custom command makes sense here because (1) this scenario should be very rare and (2) there is really only one action left to take, so automatically forcing a rebuild is a safe option.
