### ISSUE TITLE
Module not found error:  No module named 'desktop_notifier.dummy'

### ISSUE THREAD

**Issue by macpingel** [samschott/maestral#940]
**Describe the bug**
Maestral crashes on startup - Module not found error:  No module named 'desktop_notifier.dummy'

**To Reproduce**
My application folder is quite full, so I installed Maestral in /Applications/Utilities. I startup Maestral by its application-icon in the dock when needed. After the install, everything works.
When I startup Maestral 2 or 3 days later again, I get the error mentioned above. I shutdown the computer overnight, no sleep mode.
When I reinstall, everything works again.

**Expected behaviour**
Maestral starts up normally on demand from /Applications/Utilities

**System:**
 - MacBook Pro
 - Maestral version: 1.7.3
 - Python version: no python installed
 - OS: macOS 13.4.1

**Additional context**

Traceback (most recent call last):
  File "app/maestral_cocoa/__main__.py", line 42, in <module>
  File "app_packages/maestral/daemon.py", line 96, in freeze_support
  File "app_packages/maestral/daemon.py", line 378, in start_maestral_daemon
  File "app_packages/maestral/main.py", line 46, in <module>
  File "app_packages/maestral/sync.py", line 63, in <module>
  File "app_packages/maestral/notify.py", line 37, in <module>
  File "app_packages/desktop_notifier/main.py", line 151, in __init__
  File "app_packages/desktop_notifier/main.py", line 98, in get_implementation
ModuleNotFoundError: No module named 'desktop_notifier.dummy'

**Comment by macpingel** [comment]
The error didn't occur for some time now, might have been outside the scope of Maestral. 1.8.0 working fine.
