### ISSUE TITLE
Fedora 38: importlib-resources cannot be imported.

### ISSUE THREAD

**Issue by ricardojpinheiro** [samschott/maestral#942]
**Describe the bug**
I tried to install maestral into my newly installed Fedora 38 Linux here, but I couldn't. It keeps me telling that it cannot import name "path" from "importlib_resources". 

**To Reproduce**
So, I did the install sequence, using the following command:
python3 -m pip install maestral[gui]

Then, I got this traceback:
ricardo@aragorn:~$ maestral start
Starting Maestral...Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ricardo/.local/lib/python3.11/site-packages/maestral/daemon.py", line 378, in start_maestral_daemon
    from .main import Maestral
  File "/home/ricardo/.local/lib/python3.11/site-packages/maestral/main.py", line 46, in <module>
    from .sync import SyncDirection, SyncEngine
  File "/home/ricardo/.local/lib/python3.11/site-packages/maestral/sync.py", line 63, in <module>
    from . import notify
  File "/home/ricardo/.local/lib/python3.11/site-packages/maestral/notify.py", line 17, in <module>
    from desktop_notifier import DesktopNotifier, Urgency, Button
  File "/home/ricardo/.local/lib/python3.11/site-packages/desktop_notifier/__init__.py", line 2, in <module>
    from .main import DesktopNotifier, Button, ReplyField, Notification, Urgency
  File "/home/ricardo/.local/lib/python3.11/site-packages/desktop_notifier/main.py", line 29, in <module>
    from .base import (
  File "/home/ricardo/.local/lib/python3.11/site-packages/desktop_notifier/base.py", line 22, in <module>
    from importlib_resources import path as resource_path
ImportError: cannot import name 'path' from 'importlib_resources' (/home/ricardo/.local/lib/python3.11/site-packages/importlib_resources/__init__.py)

I tried to install importlib-resources (pip install importlib-resources), but it the failure still remains.

**System:**
- PyQt5: 5.15.9.
- Maestral 1.7.3:
- Python 3.11.4. 
- OS: Fedora 38.
- Desktop environment: Gnome 44.

**Additional context**
Well, I hope it can be fixed soon, Maestral is so cool, way better than Dropbox official client.

**Comment by jnraptor** [comment]
I fixed it by downgrading importlib-resources from 6.0.0to 5.13.0:

`pip install --force-reinstall "importlib-resources==5.13.0"`

**Comment by nrbeaton** [comment]
FYI same issue on Ubuntu, both using pipx and installing directly with pip.

**Comment by penserbjorne** [comment]
Same here.

Fixed with `python3 -m pip install --force-reinstall "importlib-resources==5.13.0" --upgrade 'maestral[gui]'` inside the virtualenv.

Not possible to fix with pipx.

Thanks.

**Comment by samschott** [comment]
The issue was in one of the dependencies, `desktop-notifier`, which relied on a API that was removed in importlib-resources v6.0. Its been updated to use Python's stlib `importlib.resources` instead now.
