### ISSUE TITLE
Unexpected error leading to a pause (`KeyError: 'error'`)

### ISSUE THREAD

**Issue by slifty** [samschott/maestral#961]
**Describe the bug**
I have an issue where maestral moves to a `paused` state unexpectedly.  When viewing the logs I see:

```
2023-08-21 10:10:10 manager ERROR: Unexpected error
Traceback (most recent call last):
  File "Contents/Resources/app_packages/maestral/manager.py", line 841, in _handle_sync_thread_errors
  File "Contents/Resources/app_packages/maestral/manager.py", line 826, in startup_worker
  File "Contents/Resources/app_packages/maestral/sync.py", line 1597, in upload_local_changes_while_inactive
  File "Contents/Resources/app_packages/maestral/sync.py", line 1850, in apply_local_changes
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/concurrent/futures/_base.py", line 608, in result_itera
tor
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/concurrent/futures/_base.py", line 438, in result
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/concurrent/futures/thread.py", line 52, in run
  File "Contents/Resources/app_packages/maestral/sync.py", line 2202, in _create_remote_entry
  File "Contents/Resources/app_packages/maestral/sync.py", line 2453, in _on_local_folder_created
  File "Contents/Resources/app_packages/maestral/errorhandling.py", line 849, in wrapper
  File "Contents/Resources/app_packages/maestral/client.py", line 1077, in make_dir
  File "Contents/Resources/app_packages/dropbox/base.py", line 1174, in files_create_folder_v2
  File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 323, in request
  File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 473, in request_json_string_with_retry
  File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 593, in request_json_string
  File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 645, in raise_dropbox_error_for_resp
KeyError: 'error'
2023-08-21 10:10:10 manager INFO: Shutting down threads...
2023-08-21 10:10:10 sync INFO: Sync aborted
2023-08-21 10:10:10 manager INFO: Paused
```

**To Reproduce**
Unclear how to reproduce yet, but I'll update if I can find a way.

**Expected behaviour**
Ideally this error would be handled and syncing would continue

**System:**

 - Maestral version: 1.8.0
 - Python version: 3.10.1
 - OS: MacOS 12.6
 - Desktop environment: MacOS
 - PyQt version (for Linux GUI): N/A

**Additional context**
Looking at #939 I'm not seeing error logs that look quite like this, so I wanted to open a more specific issue.

**Comment by samschott** [comment]
Looks like this is an issue with rate limiting errors (code 429) that are returned by the Dropbox API having a different format than what is expected by the Dropbox Python SDK. I'll flag this with the Dropbox team.

**Comment by samschott** [comment]
I've flagged in this in the Dropbox forum at https://www.dropboxforum.com/t5/Discuss-Dropbox-Developer-API/429-rate-limit-errors-without-quot-error-quot-tag/m-p/709587#M3542.

**Comment by samschott** [comment]
Should be fixed now, the issue was indeed on the Dropbox side.

**Comment by slifty** [comment]
Thank you so much for digging in and getting it fixed!
