### ISSUE TITLE
Not working on Fedora 39

### ISSUE THREAD

**Issue by alex27riva** [samschott/maestral#996]
**Describe the bug**
I get `ModuleNotFoundError: No module named 'importlib_metadata'` when starting Maestral.

**To Reproduce**
Run `maestral start` from terminal

**System:**

 - Maestral version:  maestral 1.8.0 
 - Python version: 3.12
 - OS: Fedora 39 Silverblue (beta)
 - Desktop environment: GNOME 45.0

**Additional context**

Stracktrace:

```
Traceback (most recent call last):
  File "/var/home/alessandro/.local/bin/maestral", line 5, in <module>
    from maestral.cli import main
  File "/var/home/alessandro/.local/lib/python3.12/site-packages/maestral/cli/__init__.py", line 6, in <module>
    from .cli_main import main
  File "/var/home/alessandro/.local/lib/python3.12/site-packages/maestral/cli/cli_main.py", line 6, in <module>
    from .cli_core import start, stop, gui, pause, resume, auth, sharelink
  File "/var/home/alessandro/.local/lib/python3.12/site-packages/maestral/cli/cli_core.py", line 15, in <module>
    from .common import (
  File "/var/home/alessandro/.local/lib/python3.12/site-packages/maestral/cli/common.py", line 13, in <module>
    from ..constants import DEFAULT_CONFIG_NAME
  File "/var/home/alessandro/.local/lib/python3.12/site-packages/maestral/constants.py", line 11, in <module>
    from importlib_metadata import metadata, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by mjg** [comment]
`importlib_metadata` has been renamed to `importlib.metadata` in python's standard lib. Maestral will have to adjust.

**Comment by entodoays** [comment]
After reinstalling I'm getting this error:
¹¹¹
Traceback (most recent call last):
  File "/home/username/.local/bin/maestral", line 5, in <module>
    from maestral.cli import main
  File "/home/username/.local/lib/python3.12/site-packages/maestral/cli/__init__.py", line 6, in <module>
    from .cli_main import main
  File "/home/username/.local/lib/python3.12/site-packages/maestral/cli/cli_main.py", line 6, in <module>
    from .cli_core import start, stop, gui, pause, resume, auth, sharelink
  File "/home/username/.local/lib/python3.12/site-packages/maestral/cli/cli_core.py", line 15, in <module>
    from .common import (
  File "/home/username/.local/lib/python3.12/site-packages/maestral/cli/common.py", line 13, in <module>
    from ..constants import DEFAULT_CONFIG_NAME
  File "/home/username/.local/lib/python3.12/site-packages/maestral/constants.py", line 11, in <module>
    from importlib_metadata import metadata, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib_metadata'

¹¹¹

**Comment by Gragt** [comment]
If you installed Maestral with pipx, you can fix this by injecting the module into maestral:

```
pipx inject maestral importlib-metadata
```

**Comment by samschott** [comment]
Apologies for this, it seems somehow `importlib_metadata` was left off the dependency list. Installing the latest version manually will fix this until I cut a new release:
```
pip3 install -U importlib_metadata
```

I'm not relying on the builtin `importlib.metadata` here because it has breaking API changes across the supported Python versions 3.8 to 3.12. In a couple
