### ISSUE TITLE
.mignore file causes sync error due to new Dropbox business folder structure

### ISSUE THREAD

**Issue by DaGaMs** [samschott/maestral#999]
**Describe the bug**

Dropbox recently changed how folders are organised for business accounts. The top-level directory in the dropbox root directory is not writeable to the user any more, but instead contains sub-folders for the various groups you're a member of, and a folder with your full name as a "private" space. 

Now, when I put the `.mignore` file in the top-level directory, I always get this error message in the maestral log:

```
2023-11-10 20:53:04 sync INFO: Could not sync .mignore
Traceback (most recent call last):
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/maestral/errorhandling.py", line 90, in convert_api_errors
    yield
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/maestral/client.py", line 923, in _upload_helper
    md = self.dbx.files_upload(
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/dropbox/base.py", line 3210, in files_upload
    r = self.request(
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/dropbox/dropbox_client.py", line 351, in request
    raise ApiError(res.request_id,
dropbox.exceptions.ApiError: ApiError('f83b74a47e3a471ab4de5b2cf0122231', UploadError('path', UploadWriteFailed(reason=WriteError('no_write_permission', None), upload_session_id='pid_upload_session:ABIHCmsQXv3-yUSYqyde1axtA0vxhu_k-PA026FXyvpq14ZYsA')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/maestral/sync.py", line 2311, in _create_remote_entry
    status = self._on_local_file_modified(event)
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/maestral/sync.py", line 2490, in _on_local_file_modified
    md_new = self.client.upload(
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/maestral/client.py", line 870, in upload
    res = self._upload_helper(
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/maestral/client.py", line 331, in wrapper
    return func(__self, *args, **kwargs)
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/maestral/client.py", line 923, in _upload_helper
    md = self.dbx.files_upload(
  File "/opt/gridware/depots/1a8f5697/el7/pkg/apps/python3/3.8.1/gcc-4.8.5/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/users/bschuster/gridware/share/python/3.8.1/lib/python3.8/site-packages/maestral/errorhandling.py", line 92, in convert_api_errors
    raise dropbox_to_maestral_error(exc, dbx_path, local_path)
maestral.exceptions.InsufficientPermissionsError: Could not upload file. You do not have permissions to write to the target location.
```

**System:**

 - Maestral version: 1.8.0
 - Python version: 3.8.1
 - OS: [e.g. Ubuntu] Debian
 - Desktop environment: [e.g. Gnome 3.32] na
 - PyQt version (for Linux GUI): na

**Additional context**

**Comment by samschott** [comment]
Thanks for the report! Darn it, this sounds like it will be a bit of a pain to adapt to.

Are all of the sub-folders still synching correctly in this new model?

**Comment by DaGaMs** [comment]
I _think_ so. But I only installed maestral _after_ the migration to the new (forced) folder structure, so it did a clean sync from scratch and all seems ok.

I am having an issue where, after adding a fairly large amount of data all at once, maestral now is stuck on syncing, ie files are queued but no uploads are happening. However, I very much doubt this has anything to do with this issue. More likely some indexing issue, or maybe I ran into some API limits (no idea how to find out).

**Comment by samschott** [comment]
> More likely some indexing issue, or maybe I ran into some API limits (no idea how to find out).

This may well be API limits. You can check the logs for "backoff" of "ratelimit" messages after increasing the log level to DEBUG with `maestral log level DEBUG`. No need to restart Maestral for this, log level changes take effect immediately.

**Comment by DaGaMs** [comment]
No `backoff` or `ratelimit` messages. All I get is a few successful API calls, and then an infinite sequence of `Request to files/upload_session/append_v2`:

```
2023-11-11 11:01:12 sync INFO: Syncing ↑ 173/573
2023-11-11 11:01:13 dropbox_client DEBUG: Request to files/upload_session/append_v2
2023-11-11 11:01:13 dropbox_client DEBUG: Request to files/get_metadata
2023-11-11 11:01:13 dropbox_client DEBUG: Request to files/upload_session/append_v2
2023-11-11 11:01:13 dropbox_client DEBUG: Request to files/upload_session/append_v2
2023-11-11 11:01:13 dropbox_client DEBUG: Request to files/upload_session/append_v2
2023-11-11 11:01:13 dropbox_client DEBUG: Request to files/upload_session/append_v2
2023-11-11 11:01:13 dropbox_client DEBUG: Request to files/upload_session/append_v2
2023-11-11 11:01:14 dropbox_client DEBUG: Request to files/upload_session/append_v2
[...]
```

However no syncing happens, it seems to make these API calls and wait for a response over and over again.

Last night, I also tried a re-indexing. This morning I saw this message:

```
✓ Sync is not running. Rebuilding scheduled for next startup.
```

Presumably the same issue/some sort of timeout? I stopped/started the daemon again, then I get the above behaviour with the very many `append_V2` calls.

**Comment by aaronrudkin** [comment]
My business account just got migrated to this and it caused a pretty near total SNAFU with the client. Basically, as best as I can tell, here's what happened:

1. As described above, the business account now has a folder in the root with my name on it, and other folders in the root that are shared folders from within the business (externally shared folders seem unaffected?). So now instead of `~/business_dropbox/`, all of my files are expected to be in `~/business_dropbox/My Name/`. 
2. Maestral detects everything in the new folder structure as new files, and downloads them all, leaving me with two copies of every file in my Dropbox.
3. I'm still making changes in folders in my root, because I didn't realize this occurred. Every one of those changes gets into a loop of errors trying to write to the root of the Dropbox, which Dropbox thinks I don't have permission to do. The errors ust cascade and case and the GUI hangs and the log is filled with messages of the type:

```Traceback (most recent call last):
  File "app_packages/maestral/sync.py", line 2312, in _create_remote_entry
  File "app_packages/maestral/sync.py", line 2491, in _on_local_file_modified
  File "app_packages/maestral/client.py", line 866, in upload
  File "app_packages/maestral/client.py", line 331, in wrapper
  File "app_packages/maestral/client.py", line 918, in _upload_helper
  File "support/python-stdlib/contextlib.py", line 155, in __exit__
  File "app_packages/maestral/errorhandling.py", line 92, in convert_api_errors
maestral.exceptions.InsufficientPermissionsError: Could not upload file. You do not have permissions to write to the target location.
2025-01-06 11:35:10 sync INFO: Could not sync 486.jpg
Traceback (most recent call last):
  File "app_packages/maestral/errorhandling.py", line 90, in convert_api_errors
  File "app_packages/maestral/client.py", line 919, in _upload_helper
  File "app_packages/dropbox/base.py", line 3214, in files_upload
  File "app_packages/dropbox/dropbox_client.py", line 351, in request
dropbox.exceptions.ApiError: ApiError('2befaa9971[truncated]', UploadError('path', UploadWriteFailed(reason=WriteError('no_write_permission', None), upload_session_id='pid_upload_session:ABIIsFnlDR
6gHrNv[truncated]')))```

To solve it, what I did was:

- Close and stop maestral
- Identify when this cutoff happened
- Use terminal to find all files changed in my Dropbox since the cutover
- Take everything from the old root out of the Dropbox and then move the recently modified files back into the new structure
- Start maestral

I think my use case of a migration of account types mid-stream is not something you can easily work around, so I'd ignore that entirely. But I do think better handling the cascade of write errors might be useful if possible for future users that have this happen. Thanks.
